import json
import archive_generation as a
r=a.IMAGE_ROOT
refs=[r/'qdao_original_roster_v14_hd/recovery-20260921/06-generation/S01-edge-final-v1/raw.png',r/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/walk/S/16.png',r/'qdao_original_roster_v14_hd/recovery-20260921/06-generation/S16-edge-final-v3/raw.png',r/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',r/'designs/jubaozhai-ui/02-characters.png']
prompt='''Use case: precise-object-edit / identity-preserve. Edit ONLY THE LEGS AND BOOTS of IMAGE 1 into a neighboring walk-cycle phase, preserving the rest of IMAGE 1 and its canvas exactly. Single south-facing walk frame S16 for the 06 thunder caster boy in 五行奇谈.
IMAGE 1 is the MAIN EDIT TARGET and the absolute lock for the complete canvas composition, original drawing scale, head/hair size and position, face, expression, torso/shoulder/robe volume, hands, staff and talisman sizes and positions. Keep its clean native high-resolution painting, transparent canvas margins and entire upper-body drawing unchanged. Do not alter overall character size, body proportions or framing. Treat all pixels above the hips as the fixed established reference.
IMAGE 2 is old S16: use ONLY its KNEE/LEG/BOOT POSE, not its colors or raster quality. IMAGE 3 is a clean S16 pose explanation: again use ONLY its knee/boot angles and relation, never its smaller body size, head or upper body. IMAGE 4 supports identity details only; image 5 is the user-confirmed PRIMARY ART STYLE, clean bright refined rounded Daoist chibi hand painting, no UI/scenery.
THE ONLY ART CHANGE: redraw the lower legs and boots of image1 into the precise S16 phase from images2 and3. SCREEN-LEFT boot reaches low forward toward the viewer, exposing part of the dark bottom sole; SCREEN-RIGHT boot is farther back, more upright, with its front/top visible and its lowest edge slightly above the screen-left boot sole. Follow images2/3 for relative knee bend, leg separation, boot angles and sole exposure. Maintain the boot and leg physical size of image1. Keep this a restrained adjacent walking phase: do not exaggerate a kick, do not make the left boot high, do not swap legs, do not make an idle stance. Naturally repaint only the necessary lower-trouser folds where the changed knees join; keep image1's waist, upper robe, face, hands and props intact. This is a genuinely drawn new movement phase, not a pasted leg collage.
Preserve exact image1 identity: round smiling amber-eyed boy, brown tied hair and gold ribbons, white/ivory gold-trimmed robe, navy trousers, gold-black boots, turquoise beads, yin-yang forehead and belt, gold staff in screen-left hand and gold talisman in screen-right hand. Keep naturally colored clean antialiased silhouette edges and true transparent alpha; do not copy fluorescent magenta/red-purple fringe from old inputs. No new shadow, glow, ground, background, matte or checkerboard pixels. Do not simplify details or add ornaments.
OUTPUT: one complete square transparent RGBA PNG, matching image1's native canvas and full-body composition, at least 1024x1024; preserve its full head-to-feet canvas occupancy with no size adjustment. No crop, sprite sheet, multiple frames, text labels, frame borders or comparison. Only the S16 leg/boot pose differs from image1; all upper-body sizes and placement remain fixed.'''
print(json.dumps(a.prepare('S16-edge-final-v4',prompt,[str(p.resolve()) for p in refs]),ensure_ascii=True))
