import json
import archive_generation as a
r=a.IMAGE_ROOT
refs=[r/'qdao_original_roster_v14_hd/recovery-20260921/06-generation/S16-edge-final-v2/raw.png',r/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/walk/S/16.png',r/'qdao_original_roster_v14_hd/recovery-20260921/06-generation/S01-edge-final-v1/raw.png',r/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',r/'designs/jubaozhai-ui/02-characters.png']
prompt='''Use case: identity-preserve. Precise one-change edit of the first image, S16 south-facing walk frame of the 06 thunder caster boy for 五行奇谈. Output one complete transparent full-body frame, native at least 1024x1024, preferably 1254x1254.
REFERENCES: Image 1 is the actual high-resolution EDIT TARGET (S16 version2). Image 2 is the ORIGINAL S16 POSE LOCK; image 1 already closely follows it. Image 3 is neighboring S01 and is BODY/HEAD/HANDS/PROPS SCALE REFERENCE ONLY, never leg-pose reference. Image 4 is identity details only. Image 5 is the user-approved PRIMARY ART STYLE: bright clean rounded Daoist chibi high-quality hand painting, no UI or scenery.
The ONLY required correction: the character in image1 is currently about 5 percent too large compared with image3. Natively redraw its complete character volume about 5 percent smaller within the same canvas, keeping all character proportions and pose. Match the modest head/face size, hand size, gold talisman size and ritual-staff size of image3. Let the flowing robe's overall width become comparable to image3 rather than the overly broad hem of image1. Maintain the same beautiful crisp painted detail and soft rounded materials. This is a native drawing revision, not a blurred scaled raster.
COMPOSITION SCALE: for a 1254 square canvas, aim for real character silhouette height about 1130 to 1140 pixels, highest hair around y=60 to 65 and the lowest forward boot sole around y=1190 to 1200. Do not enlarge the head, face, hands, talisman or staff independently. Keep the whole character centered with every hair tip, ribbon, sleeve, robe hem and boot fully inside the transparent canvas.
ABSOLUTE S16 POSE INVARIANT: keep the first image's precise walk phase and use image2 to resolve any ambiguity. The SCREEN-LEFT boot projects LOW and FORWARD toward the viewer, exposing its dark BOTTOM SOLE. The SCREEN-RIGHT boot is behind, more upright, its top/front visible, slightly higher than the screen-left sole. Keep the S16 knees, leg separation, left/right boot angles and hand positions exactly as image1/image2. Do not copy S01 knees, leg pose or boot angles from image3. Do not swap legs, do not turn into standing, do not lift the left boot higher, do not exaggerate stepping. Both props remain in the same hands and at the same angles relative to the body.
Preserve character identity, brown tied hair and gold ribbon, happy expression, ivory/gold robe, navy pants, gold/black shoes, turquoise beads, yin-yang forehead and belt, gold ritual staff and gold talisman. Keep clean local-material colored antialiasing and real transparent alpha. No fluorescent magenta or red-purple edge contamination, no colored fringe or glow. Some older reference inputs have chroma defects: never reproduce those defects. No ground/shadow, no background/checkerboard pixels, no comparison sheet, no text labels, no extra frame. Make only this restrained size correction to S16 and preserve its exact phase.'''
print(json.dumps(a.prepare('S16-edge-final-v3',prompt,[str(p.resolve()) for p in refs]),ensure_ascii=True))
