import archive_generation as a
import json
root=a.IMAGE_ROOT
refs=[root/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/idle/SW.png',root/'qdao_original_roster_v14_hd/recovery-20260921/06-final/runtime/walk/SW/01.png',root/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',root/'designs/jubaozhai-ui/02-characters.png']
prompt='''Use case: identity-preserve. Single independent idle game sprite for 五行奇谈, 06 thunder caster boy, SW front three-quarter view facing lower-left.
Input image 1 is the EDIT TARGET and STRICT POSE LOCK: keep its exact independent IDLE stance, head angle, arm positions, facial expression, hand grip, gold ritual staff and talisman in their same hands, facing and costume silhouette. Both feet firmly planted, no lifted foot, no walking, no stride.
Input image 2 is the clean current SW walking character for BODY VOLUME, MATERIAL and CHARACTER SCALE REFERENCE ONLY. Its character body volume must match the result so this boy does not shrink when switching from walking to standing. NEVER transfer its walking leg pose; feet and standing posture come only from image 1. Input image 3 is identity/costume/prop details only. Image 4 is the user-approved PRIMARY ART STYLE: refined bright clean rounded Daoist chibi hand-painted render, no UI elements or other people.
Deliver fresh native high-resolution hand-painted artwork, not raster enlargement: same large round head, warm brown tied hair, gold ribbons and turquoise beads, ivory white gold-bordered robe, navy trousers, black/gold shoes, talisman and ritual staff. Preserve all recognizable costume and ornaments while removing every fluorescent magenta/red-purple chroma fringe and spill from old input 1 and identity image 3. Clean natural local colors at silhouette edges and inner gaps, true smooth transparent alpha, no colored matte or halo, no added effects. Keep navy cloth and cool hair shadows as in clean image 2.
CRITICAL SCALE CORRECTION: render the entire full-body standing character LARGER within the square canvas. For a 1254x1254 canvas the highest real hair tip should be near y=45 to 50 and the lowest real sole near y=1200 to 1208; actual subject silhouette height should be about 1150 to 1160 pixels (92% of canvas). Keep head-to-body proportions unchanged; increase the complete character's composition size through the new native drawing, never extend hair or feet artificially. Do not leave the large 8-10% top and bottom margins of an undersized sprite. Keep safe 3-4% empty top and bottom margins, and all lateral robe/staff/ribbon extremities inside the image. A single centered complete full-body sprite, not a sprite sheet or comparison.
Output one square genuinely transparent RGBA PNG, native at least 1024x1024 (1254x1254 suitable), complete full character and all props. No crop, text, UI, ground plane, shadow, glow, color background, checkerboard pixels, extra characters. Preserve original idle SW stance exactly, with body volume matching clean walking reference while both feet stay planted.'''
print(json.dumps(a.prepare('idle-SW-edge-final-v2',prompt,[str(p.resolve()) for p in refs]),ensure_ascii=True))
