import json,datetime,hashlib
from pathlib import Path
r=Path(__file__).resolve().parents[2];out=Path(__file__).parent
snap=json.loads((out/'SE-NW-source-snapshot.json').read_text(encoding='utf-8'))
bad={1:'近RIGHT承重靴鞋跟在右、鞋头向左；16的同脚为跟左/头右，接地瞬间横向翻向，不是单纯正面透视。',2:'延续01，近RIGHT承重靴鞋头仍向左，靴轴偏离SE右下行进方向；屈膝承重相位本身保留。',3:'近RIGHT支撑靴仍跟右/头左，随后04转接近正面；须纠正同一支撑段的外向鞋轴。',12:'近RIGHT前摆靴鞋头向左且外侧底缘横展，与14–16已转正的同脚右下鞋轴不连续；保留高膝经过。',13:'近RIGHT前摆靴延续12的左偏鞋头；与14正确跟左/头右衔接存在反向鞋轴，须只修靴横向旋转。'}
sekeep={4:'支撑靴接近正前缩短，无横向外撇；远脚抬起有合理露底。',5:'近RIGHT后脚抬跟、远LEFT前摆鞋头右前，保留。',6:'近RIGHT后蹬靴趾下、远LEFT前鞋右前，露底为踝俯仰。',7:'双空姿态可辨，前鞋右前、后鞋折回，保留。',8:'远LEFT前靴下降，鞋尖右前；近RIGHT后折。',9:'远LEFT低位支撑鞋跟左/鞋头右，方向正确；近RIGHT后折。',10:'远LEFT屈膝承重，低鞋头右前；近RIGHT高折。',11:'远LEFT支撑鞋头右前，近RIGHT回收；无明确外撇。',14:'近RIGHT前鞋已转为右下，远LEFT蹬离；修正有效保留。',15:'近RIGHT前鞋已转右下、远LEFT后折，短暂双空；保留。',16:'近RIGHT下降靴跟左/头右，正确沿SE；作为01–03局部修靴对照，保留。'}
nw={1:'近LEFT低靴头朝左前、远RIGHT后折，靴跟透视与竹弓同向原则一致。',2:'近LEFT低位承重靴朝左前，膝踝连续；保留。',3:'近LEFT低靴朝左前，远RIGHT高折露底属于回收。',4:'近LEFT大腿支撑、远RIGHT小腿前摆，脚尖沿左前；与12深度相反，不按屏幕位置换腿。',5:'近LEFT抬跟、远RIGHT小腿前摆，靴轴未横拧。',6:'近LEFT后蹬伸踝、远RIGHT高前摆，后鞋露底为俯仰。',7:'双空，近LEFT后大鞋露底、远RIGHT前小鞋，靴轴随膝踝。',8:'远RIGHT前小鞋下降、近LEFT后大鞋折高，方向保留。',9:'远RIGHT小腿承重被近LEFT前景高折腿遮挡，低鞋朝左前。',10:'远RIGHT低支撑、近LEFT高折至身后，鞋尖没有独立外旋。',11:'近LEFT前摆、远RIGHT支撑后移到屏中右，是前后经过而非突然换腿。',12:'近LEFT大前摆腿、远RIGHT低后腿；与04有近远层次差，靴轴正确。',13:'近LEFT前靴头左前、远RIGHT抬跟；屏左下位置不是外八。',14:'近LEFT前鞋朝左前、远RIGHT后蹬，后跟抬起合理。',15:'双空前后腿，前鞋头左前、后靴折回，露底不判外八。',16:'近LEFT前鞋下降朝左前、远RIGHT高折，接回01同脚承重。'}
rows=[]
for s in snap['rows']:
 if s['character']!='musician': continue
 d=s['direction'];n=s['frame'];issue=d=='SE' and n in bad
 rows.append({**s,'decision':'must_correct' if issue else 'retain','finding':bad[n] if issue else (sekeep[n] if d=='SE' else nw[n]),'correctionScope':'ONLY near anatomical RIGHT boot yaw; preserve hip/knee/ankle location, support/swing phase, torso/head scale, qin and arms' if issue else None})
report={'schemaVersion':1,'reviewer':'finish_se_nw','reviewedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Same-direction static visual comparison only; user now1200ms/cycle, timing not reviewed here','bambooManifestPath':snap['bambooManifestPath'],'bambooManifestSha256':snap['bambooManifestSha256'],'referenceStatus':'User-confirmed current bamboo version from manifest sequences[].frames[].file; manifest older pending flags are not used as user approval evidence.','method':'Actually viewed 32+32 full-frame contact sheets and original-pixel lower-leg/boot crops; compare toe/heel/knee/ankle axes and within-musician continuity, no frame-number phase transfer. PIL QA only.','revisedPriorJudgment':'Previously SE01–03 and12–13 were attributed to foreshortening. Native-pixel heel/toe positions and16→01→03→04 continuity plus the approved same-direction reference establish true opposite boot yaw, so that prior all-clear conclusion is superseded for these five frames.','mustCorrect':['run/SE/01','run/SE/02','run/SE/03','run/SE/12','run/SE/13'],'retainCount':27,'handAndGroundingConclusion':'LEFT upper qin/RIGHT lower strings remains anatomically connected; hands carry qin together and need not copy free bow arm swing. No additional concrete shoulder/elbow, support-side or airborne pose defect identified beyond five boot yaw corrections. Do not copy bamboo phase numbering, outfit, weapon or leg lengths.','referenceFrames':[s for s in snap['rows'] if s['character']=='bamboo'],'frames':rows,'assetMutation':'none; only QA crops/contact sheets and provenance JSON created'}
(out/'SE-NW-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'mustCorrect':report['mustCorrect'],'retain':report['retainCount'],'frames':len(rows),'referenceFrames':len(report['referenceFrames'])}))

