from pathlib import Path
import json,hashlib,datetime
from PIL import Image
import numpy as np
D=Path(__file__).parent;F=D/'final-v3'
ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'))
save=lambda p,o:Path(p).write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf8')
prep=read(D/'preparation.json');J=Image.open(F/'joined.png').convert('RGB')
save(F/'visual-review.json',{'reviewedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'image':ref(F/'joined.png'),'reviewMethod':'Whole native1254 square, complete bottom return, two bottom corners and repair-top band viewed at original size.','inspectedImages':[ref(p) for p in (F/'qa').glob('*.png')],'localVisualAccepted':True,'formalAccepted':False,'wholeTileAccepted':False,'findings':['New native top area follows canonical large ivory slabs and diagonal narrow course.','Initial bottom blend showed a doubled perimeter bevel; rejected. A narrow native AI redraw repaired the physical contour, followed by explicit measured vertical registration with max11px and no horizontal shift.','Final native view and bottom strip have a single perimeter highlight and bevel, without a transparency-boundary seam or abrupt color step.','The new cross joint ends at the perimeter.','New core and176-row bottom return must apply together; current source remains pixel exact below local3133.','Native left halo is retained for future r07_c09 work and does not claim existing coverage in that tile.'],'maxDx':0,'maxDy':11,'actualModel':None,'actualQuality':None})
prior=prep['sourceTile'];patches=[]
for name,crop,tile,dest,src in [('new-core',[115,0,1254,1024],'r07_c10',[0,1933,1139,2957],None),('bottom-return',[115,1024,1254,1200],'r07_c10',[0,2957,1139,3133],prior)]:
 p=F/(name+'.png');J.crop(crop).save(p);patches.append({'name':name,'asset':ref(p),'cropFromJoinedLTRB':crop,'destinationTile':tile,'destinationTileLTRB':dest,'requiredPriorSource':src,'nativeScale':1,'mustApplyTogether':True})
m={'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'appearance':'tianyong_festival','tile':'r07_c10','tileGlobalOrigin':[36864,24576],'nativeScale':1,'windowTileLocalLTRB':[-115,1933,1139,3187],'windowGlobalLTRB':[36749,26509,38003,27763],'joined':ref(F/'joined.png'),'visualReview':ref(F/'visual-review.json'),'assembly':ref(F/'assembly.json'),'localVisualAccepted':True,'formalAccepted':False,'patches':patches,'sourceCheckpoint':prep['savedCheckpoint'],'requiresPriorManifest':prep['requiresPriorManifest'],'note':'Root review and ROI validation before publication. Preserve all source pixels outside explicit rectangles.'}
save(F/'manifest.json',m)
save(F/'joined.png.generation.json',{'operation':'native AI edit, bounded measured registration and native-preserving composite','sources':[ref(D/'native.png'),ref(D/'repair-v1/native.png'),ref(D/'context.png')],'assembly':ref(F/'assembly.json'),'output':ref(F/'joined.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'noUpscale':True,'formalAccepted':False})
fragment=Image.open(prior['file']).convert('RGBA');fragment.paste(J.crop((115,0,1254,1200)).convert('RGBA'),(0,1933));fragment.save(F/'r07_c10-fragment.png')
coverage=int(np.count_nonzero(np.array(fragment)[:,:,3]==255));assert coverage==5831680
save(F/'r07_c10-fragment.png.generation.json',{'operation':'1:1 native patch composition','sources':[prior,ref(F/'joined.png')],'manifest':ref(F/'manifest.json'),'output':ref(F/'r07_c10-fragment.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'coveragePixels':coverage,'noUpscale':True,'formalAccepted':False})
save(D.parent/'local-source-checkpoint.json',{'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tile':'r07_c10','fragment':ref(F/'r07_c10-fragment.png'),'nativeScale':1,'coveragePixels':coverage,'formalAccepted':False,'rootPublished':False,'manifest':ref(F/'manifest.json'),'previousManifest':prep['requiresPriorManifest'],'contextJoined':ref(F/'joined.png'),'bottomReturn':patches[1]})
print(json.dumps({'manifest':ref(F/'manifest.json'),'joined':ref(F/'joined.png'),'localCoveragePixels':coverage}))
