from pathlib import Path
from PIL import Image,ImageFilter
import numpy as np,json,hashlib,datetime,shutil
D=Path(r'D:/work/image/qdao_city_tiles_4k_20260916/builtin_q64_production/parallel_20261005/tianyong_festival/r05_c10/r04_c01-v1');R=D/'post-surface-repair-v1';F=D/'final-v6';F.mkdir(exist_ok=True);Q=F/'qa';Q.mkdir(exist_ok=True)
ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
host=Path(r'C:/Users/luyua/.codex/generated_images/01a11b05-7488-7d11-bfe3-c3b64c8f7651/exec-80c0c985-b2b4-46ec-81d6-820cf26ff311.png');shutil.copy2(host,R/'native.png');N=Image.open(R/'native.png').convert('RGB');assert N.size==(1254,1254)
rec={'operation':'builtin AI localized ivory railing surface continuity repair','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'output':ref(R/'native.png'),'host':ref(host),'preparation':ref(R/'preparation.json'),'request':ref(R/'request.json'),'configTarget':json.loads(Path(r'D:/work/image/config/image-generation.json').read_text(encoding='utf-8-sig')),'actualSubmittedModel':None,'actualSubmittedQuality':None,'actualReturnedModel':None,'actualReturnedQuality':None,'actualReturnedPixels':list(N.size),'nativeScale':1,'formalAccepted':False}
(R/'native.png.generation.json').write_text(json.dumps(rec,indent=2),encoding='utf-8')
J=np.array(Image.open(D/'final-v5/joined.png').convert('RGB'));M=Image.open(R/'repair-mask.png').convert('L');W=np.maximum(np.array(M)/255,np.array(M.filter(ImageFilter.GaussianBlur(4)))/255);J[650:1904]=np.rint(J[650:1904]*(1-W[:,:,None])+np.array(N)*W[:,:,None]).astype(np.uint8)
Image.fromarray(J).save(F/'joined.png');Image.fromarray(J[:1254]).save(F/'main1254.png');Image.fromarray(np.rint(W*255).astype(np.uint8)).save(F/'post-repair-ownership.png')
for name,box in [('main1254',[0,0,1254,1254]),('lower-native',[0,1024,1254,2278]),('middle-overlap',[0,700,1254,1500]),('right-upper',[920,0,1254,1200]),('right-lower',[900,1024,1254,2278]),('left-perimeter',[105,1139,260,2278]),('return-tail',[0,2050,1254,2278]),('post-repair-native',[990,900,1230,1350])]:Image.fromarray(J).crop(box).save(Q/(name+'.png'))
asm=json.loads((D/'final-v5/assembly.json').read_text(encoding='utf-8'));asm.update({'output':ref(F/'joined.png'),'postRepairSource':ref(R/'native.png'),'postRepairWindowGlobalLTRB':[36749,19991,38003,21245],'postRepairPlacementXY':[0,650],'postRepairWeight':ref(F/'post-repair-ownership.png'),'postRepairReason':'Repair small source ownership step in the ivory railing face with actual native AI pixels; no registration, resizing or drawing.'});(F/'assembly.json').write_text(json.dumps(asm,indent=2),encoding='utf-8');print(json.dumps(ref(F/'joined.png')))
