from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib,shutil
D=Path(r"D:/work/image/qdao_city_tiles_4k_20260916/builtin_q64_production/parallel_20261005/tianyong_festival/r05_c10/r04_c01-v1");R=D/'coupled-whole-object-v1';R.mkdir(exist_ok=True)
ref=lambda p:{"file":str(p),"sha256":hashlib.sha256(Path(p).read_bytes()).hexdigest()}
prev=D/'alignment-repair-v3';host=Path(r"C:/Users/luyua/.codex/generated_images/01a11b05-7488-7d11-bfe3-c3b64c8f7651/exec-d2b0234f-93f9-41e1-9cbf-c80a4dfb2f45.png");shutil.copy2(host,prev/'native.png');(prev/'rejection.json').write_text(json.dumps({'status':'rejected-never-used','reason':'Reordered fixed lower motifs and shortened plaque; narrow seam repair abandoned in favor of whole-object coupled native redraw.','output':ref(prev/'native.png'),'actualReturnedModel':None,'actualReturnedQuality':None},indent=2),encoding='utf-8')
prep=json.loads((D/'preparation.json').read_text(encoding='utf-8'));south=prep['coupledBottom'];S=np.array(Image.open(south['file']).convert('RGBA'));N=np.array(Image.open(D/'alignment-repair-v2/native.png').convert('RGBA'))
C=np.zeros((1254,1254,4),np.uint8);C[115:,115:]=S[:1139,:1139];C[:230]=N[674:904]
Image.fromarray(C).save(R/'source-composite.png')
mask=np.zeros((1254,1254),np.uint8);mask[230:1120,180:710]=255;mask[180:420,115:1139]=255;mask[C[:,:,3]==0]=255
target=C.copy();target[mask==255]=0;Image.fromarray(target).save(R/'edit-target.png');Image.fromarray(mask).save(R/'mask.png')
world=[36749,20365,38003,21619];master=Path(r"D:/work/image/tianyong_festival_hd_20260910/tianyong_city_master_6144.png");Image.open(master).convert('RGB').resize((1254,1254),Image.Resampling.BICUBIC,box=tuple(v*3/32 for v in world)).save(R/'layout-reference-only.png')
prompt="""Use case: precise-object-edit / outpainting. Repaint the COMPLETE lower red hanging plaque and all its gold beads/red silk tassel as ONE coherent connected object in LAST IMAGE4. Return a native opaque1254x1254 square, same world position and crop.
Image1 is approved style; image2 is nearby native material/foliage swatch only; image3 is the exact same-world master layout; image4 is the sole edit target.
The TOP180 pixels of image4 are the already-made true upper red plaque at its intended native position, continue this exact body downward. Match its red side edges, width and gold floral ornament position exactly. The side floor, ivory wall and plants and bottom floor are true accepted native pixels. The missing central region contains the remainder of this SAME red plaque, rounded hem, two rounded gold beads below it, and one full bright red silk tassel. The entire object is inside this crop; its tassel ends above the unmasked bottom floor. Follow the canonical vertical footprint for these parts but use the authentic top anchor width and position. No duplicated or disconnected plaque, bead, ornament, tassel or edge. Maintain a clean straight connected hanging object, same camera, scale and lighting.
At the top repair band also smoothly connect the neighboring planter/floor and ivory wall to the fixed side pixels; retain their footprint. Surrounding ground is warm pale stone paving with soft wall/plant cast shadows, not extra ornament. Broad bevels, clean rounded Q handpainting. Gold cloud/floral motifs matching the existing top anchor, no invented readable characters or long gold outline. No fracture, crack, scratch, chipped edge, polygon line, text, figures, UI, watermark, zoom, rotation, warp or reframing. All opaque pixels outside the repair band remain unchanged. Fill the transparent regions, preserving original texture density."""
refs=[Path(r"D:/work/image/designs/gameplay-ui/04-guild.png"),D/'nearby-native-material-swatch.png',R/'layout-reference-only.png',R/'edit-target.png'];req={'prompt':prompt,'referenced_image_paths':[str(p) for p in refs],'transparent_background':False}
(R/'request.json').write_text(json.dumps(req,ensure_ascii=False,indent=2),encoding='utf-8')
(R/'preparation.json').write_text(json.dumps({'globalCropLTRB':world,'mainNativeYOffset':1024,'actualBottomSource':south,'upperActualNative':ref(D/'alignment-repair-v2/native.png'),'upperSourceCropLTRB':[0,674,1254,904],'sourceComposite':ref(R/'source-composite.png'),'mask':ref(R/'mask.png'),'references':[ref(p) for p in refs],'nativeScale':1,'noWarp':True,'scope':'Whole plaque lower body, beads and entire tassel; coupled return must include full object and ground perimeter.','configTarget':json.loads((D/'request.json').read_text(encoding='utf-8'))['configSnapshot'],'actualSubmittedModel':None,'actualSubmittedQuality':None},ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(req))

