"""Prepare exact targeted NW animation edit requests. Does not call image generation."""
from pathlib import Path
from datetime import datetime,timezone
import argparse,hashlib,json
HERE=Path(__file__).resolve().parent; GEN=HERE.parent/'05-generation'; ROOT=HERE.parents[2]
PHASES={
2:'Just after first left-shoe contact: the screen-LEFT shoe remains planted, left knee softens slightly. The screen-RIGHT rear shoe heel lifts slightly more while its toe still touches ground. Tiny change from image1, same support leg.',
3:'First recoil: screen-LEFT shoe stays planted, bearing weight with softly bent knee. Screen-RIGHT rear shoe has now lifted a little off the ground behind, its knee bent, purple sole partially visible. Right shoe moves slightly toward left support ankle but stays in its own lane.',
4:'Before first passing: screen-LEFT shoe flat under hip supports. The screen-RIGHT bent knee swings forward; its raised boot moves upward in the picture toward the support ankle, right boot is just behind support ankle, toe points diagonally upper-left. Do not change the support leg.',
5:'First passing: screen-LEFT shoe flat on the ground under hip is support. The screen-RIGHT knee bends forward upper-left; RIGHT boot is lifted and tucked beside, a little HIGHER in the picture than the left support boot. RIGHT boot points diagonally upper-left, its heel raised and toe angled down. Show boot SIDE/top, not its entire sole. This is a small passing step with just one lifted boot; right shin shorter by foreshortening. Both boots remain clearly separate in their own lanes.',
6:'After first passing: screen-LEFT shoe is still grounded under hip with heel just beginning to rise. Screen-RIGHT shoe swings farther ahead toward upper-left, higher in picture, toe now rising and heel lowering; right knee starting to straighten. Keep right shoe airborne and forward.',
7:'Preparing opposite contact: screen-LEFT shoe trails, toe planted, heel raised, some purple sole visible on LEFT. Screen-RIGHT leg reaches ahead upper-left with boot almost flat, right heel still a small gap above ground. Short stride, not a kick.',
8:'Immediately before opposite contact: screen-LEFT shoe trails, toe planted, heel raised with purple sole visible on LEFT. Screen-RIGHT boot reaches ahead upper-left almost flat, right heel only a tiny gap above ground. Almost like09 but right heel not yet grounded.',
10:'Just after opposite right-shoe contact: screen-RIGHT shoe remains planted under hip, right knee softens slightly. Screen-LEFT rear shoe heel lifts a little more while left toe still touches ground. Keep right support, a very small change from09.',
11:'Second recoil: screen-RIGHT shoe stays planted bearing weight. Screen-LEFT rear shoe has now lifted a little off ground behind, knee bent and purple sole partially visible. Left shoe moves slightly toward right support ankle but stays in its own screen-left lane.',
12:'Before second passing: screen-RIGHT shoe flat under hip supports. Screen-LEFT knee swings forward; raised left boot moves upward in picture toward support ankle, just behind the support ankle. Left boot points upper-left. Do not change support leg.',
13:'Second passing: screen-RIGHT shoe flat on ground under hip is support. Screen-LEFT knee bends forward upper-left; LEFT boot is lifted and tucked beside, a little HIGHER in picture than right support boot. LEFT boot points diagonally upper-left with heel raised and toe angled down. Show boot SIDE/top, not entire sole. Small passing step, only LEFT boot airborne. Two separate boots remain in their own leg lanes.',
14:'After second passing: screen-RIGHT shoe still grounded under hip, heel just starting to rise. Screen-LEFT shoe swings farther ahead upper-left and higher in picture, toe now rising and heel lowering, left knee starting to straighten. Left boot airborne and forward.',
15:'Preparing loop contact: screen-RIGHT shoe trails, toe planted, heel raised, some purple sole visible on RIGHT. Screen-LEFT leg reaches ahead upper-left, boot almost flat, left heel still a small gap above ground. Short stride, same body size as01.',
16:'Immediately before loop contact: screen-RIGHT rear shoe toe planted with heel raised and purple sole visible on RIGHT. Screen-LEFT boot extends a short step ahead upper-left, almost flat, left heel only tiny gap above ground. Almost like01 but left heel not grounded. Tiny change to01; crown and torso stay at same height.'}
def main():
 p=argparse.ArgumentParser();p.add_argument('--frame',type=int,required=True);p.add_argument('--version',type=int,default=1);p.add_argument('--base',required=True);p.add_argument('--phase-ref');p.add_argument('--extra',default='');p.add_argument('--short',action='store_true');a=p.parse_args()
 arc=GEN/f'NW{a.frame:02d}-single-v{a.version}';arc.mkdir(exist_ok=True);assert not (arc/'request.json').exists()
 refs=[GEN/a.base/'raw.png',ROOT/'qdao_original_roster_v13/candidate/05_celestial_musician_girl/idle/NW.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
 more=''
 if a.phase_ref:refs.append(GEN/a.phase_ref/'raw.png');more=' Image4 is the adjacent phase reference, use it to keep body size and walk continuity; newly draw the requested intermediate phase.'
 assert all(r.is_file() for r in refs)
 prompt=f'''Use case: identity-preserve EDIT. Edit IMAGE1 into ONE NEW NW walking-animation frame NW{a.frame:02d}. Preserve the same rear-left camera facing away to upper-left, the entire head, crown, long hair, upper torso, instrument, hands, robe details and original anatomy. Only naturally redraw legs, boots and a subtle responding hem/ribbon motion into the next real walking phase.
REQUIRED BOOT POSE NW{a.frame:02d}: {PHASES[a.frame]}
Left and right mean sides of the PICTURE. Do not cross leg lanes, exchange legs, grow extra limbs, change direction or repeat the previous pose. Two correctly attached legs and two boots, at least one supporting foot touching invisible ground. Small walk, no jump or wide kick. This is newly generated animation art, not a mirrored/warped/interpolated/translated duplicate.
Image1 is edit target and phase/body-size reference. Image2 is original NW identity and camera reference (old512 margins are NOT a framing guide). Image3 is confirmed PRIMARY ART STYLE reference: bright rounded clean refined hand-painted material and lighting, no UI. {more}
One complete full-body chibi figure, native square1254x1254 or larger, minimum1024. Crown near3% and support sole97%, large94% figure height with safe margins, same body size in every phase and almost no bob. True transparent RGBA background, preserve translucent lavender ribbons and genuine purple costume. No shadow, colored matte, checkerboard, writing, frames or other objects.'''
 if a.short:
  prompt=f'Use case: identity-preserve EDIT. Create ONE new animation phase NW{a.frame:02d} by editing IMAGE1. Keep its character, costume, hair, crown, instrument, rear-left camera facing away toward upper-left and whole body size. NEW LEG ACTION: '+a.extra+' Image2 locks original NW character/camera. Image3 is the confirmed PRIMARY art style reference, match its polished clean bright rounded hand painting; no UI. Draw one complete full-body figure native1254x1254 transparent RGBA minimum1024, crown3%/feet97%, two legs and two boots, no extra limbs or shadows, no text or background. Newly draw the requested real walk phase, do not mirror, warp, copy or interpolate. Preserve translucent lavender ribbons and all genuine purple clothing.'
 elif a.extra:prompt+='\n'+a.extra
 req={'tool':'built-in image_gen','configSnapshot':json.loads((ROOT/'config/image-generation.json').read_text(encoding='utf-8')),'actual_request':{'prompt':prompt,'referenced_image_paths':[r.as_posix() for r in refs],'started_at':datetime.now(timezone.utc).isoformat()},'reference_bindings_at_start':[{'path':r.as_posix(),'sha256':hashlib.sha256(r.read_bytes()).hexdigest()} for r in refs]}
 (arc/'prompt.txt').write_bytes(prompt.encode());(arc/'request.json').write_text(json.dumps(req,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps({'archive':str(arc),'request':req['actual_request']}))
if __name__=='__main__':main()
