from pathlib import Path
import sys,json
sys.dont_write_bytecode=True
T=Path(__file__).resolve().parent;R=T/'repairs';sys.path.insert(0,str(T));import helper as h
starts=[0,1024,2048,2842]
DETAILS={('north',1):'Golden broad rounded tree leaves and cropped wooden platform. Rejoin each golden leaf cluster cleanly across the horizontal splice, keeping the same main leaf positions and tree silhouette, never making a straight foliage edge.',('north',2):'Golden leaves on left, deep emerald/lime leaves on right, pale stone wall behind. Connect the leaf clusters and the exposed wall seamlessly through the horizontal splice, without changing cluster density.',('north',3):'Emerald/lime foliage on left, pale upright wall above and natural rounded coastal rock below, turquoise water at right. The horizontal boundary and narrow flat dark-blue strip along the upper wall at far right are splice artifacts. Unify the pale wall and cliff as one continuously shaded stone structure: preserve upper wall alignment and lower cliff footprint, resolve their junction with a plausible rounded bevel and matching material. Keep shoreline foam and the small pale rock at lower-center.',('north',4):'Water and the pale cliff at left. Make the water ripple paths continuous and transition pale wall into the existing rounded coastal rock at left. Remove the flat dark-blue pasted strip beside the upper wall. Retain all shoreline endpoints and sparse water highlights.',('east',1):'Turquoise water, sparse long pale caustics and cropped leaves at lower-right. Reconnect the broken caustic curves across the central vertical splice with one coherent water surface, smoothly matching neighboring pigment; no new dense ripple network.',('east',2):'Rounded green and lime tree crowns above turquoise water. Rejoin split leaf clusters, remove the hard vertical brightness band, preserve the same outer canopy silhouette, branch positions and foliage density.',('east',3):'Green canopy and bushes before warm wooden railing at right. Rejoin split leaves and branches across the center vertical splice, matching the smooth painted materials and original canopy silhouette. Preserve every wooden rail and post unchanged.',('east',4):'Central wooden railing post has incorrectly spliced left/right halves at x627. Reconstruct one complete coherent wooden post with the existing rounded cap, same footprint and rail endpoints; reconcile the rope/carving detail to one physically consistent continuous post. Restore continuous bevels on stone curb at bottom. Also remove the horizontal pasted foliage strip at y230 on the left. Keep all other posts, leaves and architecture exactly where they are.'}
def prepare(axis,i):
 d=R/(axis+'-joint');target=d/f's{i}-target.png';refs=[target.as_posix(),h.STYLE];notes=[]
 for j in [i-1,i+1]:
  f=d/'native'/f's{j}.png'
  if 1<=j<=4 and f.exists():
   refs.append(f.as_posix());delta=abs(starts[i-1]-starts[j-1]);direction=('LEFT' if j<i else 'RIGHT') if axis=='north' else ('UPPER' if j<i else 'LOWER');notes.append(f'Image{len(refs)} is the repaired {direction} adjacent segment; align their shared {1254-delta}px overlap, use only as boundary context.')
 orientation='horizontal y627' if axis=='north' else 'vertical x627'
 prompt=f'Use case: precise shared-edge native map repair. Image1 is the EDIT TARGET, an exact native1254x1254 crop spanning two adjacent map tiles. Image2 is the approved PRIMARY painting style only; no UI. Repair the artificial {orientation} splice visible through Image1 as one uninterrupted scene. '+DETAILS[(axis,i)]+' '+' '.join(notes)+' Retain exact crop, camera, object counts, main outlines and all endpoints at the four image borders. Keep the outer200px away from the seam substantially unchanged; work through the middle band on both sides of the join and necessary connected contours. Correct geometry by real drawing, no blur or feathering. Bright clean rounded Taoist Q fantasy handpainting, restrained warm highlights and cool soft shadows, native crisp detail. Match existing original texture density, no added objects, no extra cracks, no foliage densification, no noise or oversharpening. Same square1254 composition.'
 call={'prompt':prompt,'referenced_image_paths':refs,'transparent_background':False};h.p.write(d/f's{i}.call.json',call);(d/f's{i}.prompt.txt').write_text(prompt,encoding='utf8');print(json.dumps(call))
def ingest(axis,i,source):
 d=R/(axis+'-joint');h.p.ROOT=d;call=h.p.read(d/f's{i}.call.json');p=h.p.ingest(source,f's{i}',d/f's{i}.prompt.txt',call['referenced_image_paths'],'native_shared_edge_repair');j=h.p.read(str(p)+'.generation.json');j['evidence']['toolOutputHintFile']=str(d/'evidence'/f's{i}.tool-result.json');h.p.write(str(p)+'.generation.json',j)
if __name__=='__main__':
 if sys.argv[1]=='prepare':prepare(sys.argv[2],int(sys.argv[3]))
 elif sys.argv[1]=='ingest':ingest(sys.argv[2],sys.argv[3],sys.argv[4])

