from pathlib import Path
import json,hashlib,datetime
from PIL import Image
import numpy as np
D=Path(__file__).parent;F=D/'final-v1';T=D.parents[1]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def ref(p):return {'file':str(p),'sha256':sha(p)}
def save(p,o):Path(p).write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf8')
prep=json.loads((D/'preparation.json').read_text(encoding='utf-8-sig'))
J=Image.open(F/'joined.png').convert('RGB');j=np.array(J);C=np.array(Image.open(D/'context.png').convert('RGB'))
a=json.loads((F/'assembly.json').read_text(encoding='utf8'));a['native']=ref(D/'repair-v2/selected-native.png');a['repairSelection']=ref(D/'repair-v2/selection.json');a['blendException']='For the repaired diagonal band x80..680, use the complete AI-redrawn contour until y1120, then smoothstep y1120..1200 to the correctly matched source endpoints; never mix mismatched contours at y1040.';a['repairedBandCompleteNativeAbove1120']=True
save(F/'assembly.json',a)
review={'reviewedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'image':ref(F/'joined.png'),'reviewMethod':'Full 1254 native image, full right and bottom return strips, lower-right corner, and complete repaired diagonal strip viewed at original pixel size.','inspectedImages':[ref(p) for p in (F/'qa').glob('*.png')],'localVisualAccepted':True,'formalAccepted':False,'wholeTileAccepted':False,'findings':['New rectangular ivory paving follows the canonical world layout and the real right/bottom finished context.','The initial native bevel differed from the bottom source and the first AI repair did not resolve its angle. They were not accepted as final.','A second AI inpaint redrew the entire lower-left diagonal strip. Complete generated contour is retained above y1120 and only matched lower endpoints transition to existing context. This removes the double edge without geometric warping.','Right return contours remain continuous, source beyond x1200 is exact, and bottom source beyond y1200 is exact.','No resize, geometric registration, tone adjustment or blur was applied.','New core, right return, and r08_c10 bottom return must be applied together after r04_c04 manifest.'],'actualModel':None,'actualQuality':None,'limitations':['Only this native patch and its returns are accepted locally. Full tile, exterior neighbor and city review are required.']}
save(F/'visual-review.json',review)
prior={**prep['northPriorFragment'],'tile':'r07_c10','tileLocalLTRB':[0,0,4096,4096],'nativeScale':1}
patches=[]
for name,crop,tile,dest,src in [('new-core',[0,0,1024,1139],'r07_c10',[1933,2957,2957,4096],None),('right-return',[1024,0,1200,1139],'r07_c10',[2957,2957,3133,4096],prior),('bottom-return',[0,1139,1200,1200],'r08_c10',[1933,0,3133,61],prep['sourceTile'])]:
 p=F/(name+'.png');J.crop(crop).save(p);patches.append({'name':name,'asset':ref(p),'cropFromJoinedLTRB':crop,'destinationTile':tile,'destinationTileLTRB':dest,'requiredPriorSource':src,'nativeScale':1,'mustApplyTogether':True})
m={'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'appearance':'tianyong_festival','tile':'r07_c10','tileGlobalOrigin':[36864,24576],'nativeScale':1,'windowTileLocalLTRB':[1933,2957,3187,4211],'windowGlobalLTRB':[38797,27533,40051,28787],'joined':ref(F/'joined.png'),'visualReview':ref(F/'visual-review.json'),'assembly':ref(F/'assembly.json'),'localVisualAccepted':True,'formalAccepted':False,'patches':patches,'sourceCheckpoint':prep['savedCheckpoint'],'requiresPriorManifest':prep['requiresPriorManifest'],'note':'Root review and ROI validation before publication. Coupled return source is an explicitly derived local representation of previous c04 manifest, not a root checkpoint rollback.'}
save(F/'manifest.json',m)
save(F/'joined.png.generation.json',{'operation':'native-preserving composite after local AI structural inpaint','sources':[ref(D/'native.png'),ref(D/'repair-v2/native.png'),ref(D/'context.png')],'assembly':ref(F/'assembly.json'),'output':ref(F/'joined.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'noUpscale':True,'formalAccepted':False})
fragment=Image.open(prep['northPriorFragment']['file']).convert('RGBA');fragment.paste(J.crop((0,0,1200,1139)).convert('RGBA'),(1933,2957));fragment.save(F/'r07_c10-fragment.png')
coverage=int(np.count_nonzero(np.array(fragment)[:,:,3]==255));assert coverage==2463657
save(D.parent/'local-source-checkpoint.json',{'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tile':'r07_c10','fragment':ref(F/'r07_c10-fragment.png'),'nativeScale':1,'coveragePixels':coverage,'formalAccepted':False,'rootPublished':False,'manifest':ref(F/'manifest.json'),'previousManifest':prep['requiresPriorManifest'],'contextJoined':ref(F/'joined.png'),'bottomReturn':patches[2]})
save(D/'repair-v1/rejected.json',{'localVisualAccepted':False,'reason':'Lower diagonal still diverged by up to26 pixels from original lower edge; do not use','retention':'Temporary until root accepts repaired final and provenance closure allows PNG cleanup.'})
print(json.dumps({'manifest':ref(F/'manifest.json'),'joined':ref(F/'joined.png'),'newTilePixelsAdded':1166336,'localCoveragePixels':coverage,'rootPublished':False},indent=2))
