async (action,direction,frame,attempt=1)=>{
const root="D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/characters/02_fire_talisman_boy";
const target=root+"/frames/"+action+"/"+direction+"/"+String(frame).padStart(2,"0")+".png";
const structure=root+"/frames/"+(action==="attack"?"attack/E/02.png":"run/SE/01.png");
const refs=[{path:target,role:"EDIT TARGET: current six-card frame, preserve pose and full canvas framing"},{path:"D:/work/image/q_daoist_character_pack_4096/02_fire_talisman_boy_transparent_4096.png",role:"committed authoritative identity: anatomical right hand exactly five red cards and left hand bronze bell"},{path:"D:/work/image/designs/jubaozhai-ui/02-characters.png",role:"approved painted style; ignore UI and scenery"},{path:structure,role:"actually viewed correct FIVE-card structure example only, never copy its body pose or change target framing"}];
if(attempt>1 && action==="run" && (frame===8||frame===9))refs.push({path:root+"/work/root-fan-fix/root-fan-cast-run-SE-07-20261003-v1-native.png",role:"correct five-card fan at SAME half-cycle: anatomical LEFT leg extends down on screen-right, RIGHT leg folds behind on screen-left; only preserve target silhouette, no extra leg"});
for(const ref of refs){const h=await tools.exec_command({cmd:"(Get-FileHash -Algorithm SHA256 -LiteralPath '"+ref.path.replace(/'/g,"''")+"').Hash.ToLowerInvariant()",max_output_tokens:90});ref.sha256=h.output.trim();if(!/^[a-f0-9]{64}$/.test(ref.sha256))throw new Error("Reference SHA unavailable");}
const phase=action==="attack"?"Remove the lowest/rightmost almost-horizontal sixth talisman card only.":"Remove the rightmost/lower-right outermost sixth talisman card only.";
const prompt=(attempt>1?"CRITICAL: This is a tiny fan retouch ONLY. Keep EXACTLY image1 body silhouette, TWO legs/TWO shoes, head, arms and bell without moving them. The front extended leg stays at SCREEN RIGHT, folded trailing leg stays SCREEN LEFT. NEVER replace this with image4 running pose. Image5 if supplied shows the correct same-half-cycle anatomy; still keep original image1 pose. Image4 is ONLY card count, IGNORE ALL its body/legs. ":"")+"Use case: precise-object-edit. Image1 is the EDIT TARGET. It incorrectly has SIX distinct red talisman paper rectangles with six gold flame emblems. "+phase+" After edit there MUST be exactly FIVE separate rectangular red cards, FIVE gold flame emblems and FIVE top card ends. Keep the remaining five original cards, their gold border art, fan arrangement and the existing right-hand grip position. Do not add a thin sixth card sliver behind them. Repaint only the small fan region and any tiny surface exposed by removal. Preserve image1 body pose, face expression, head/pony/crown pixel size and position, arms, hands, bronze bell, robe, legs, both shoe axes, stance and full-canvas composition as faithfully as possible. No pose resynthesis, no character resize or recenter, no change to the left-hand bell or right-hand talisman ownership. Image2 is identity, image3 approved rendering, image4 only confirms the FIVE-card structure; retain target pose. Output one native square RGBA transparent image at least1024 pixels; no background, ground, shadow, text, glow or detached effects. Target configuration GPT Image2.5 Sunburst/max is host-managed.";
const id="root-fan-cast-"+action+"-"+direction+"-"+String(frame).padStart(2,"0")+"-20261003-v"+attempt;
const recpath="records/"+id+".json";
const record={call_id:id,requested_slot:action+"/"+direction+"/"+String(frame).padStart(2,"0"),submittedAt:new Date().toISOString(),userTimezone:"America/New_York",route:"builtin",tool:"image_gen.imagegen",configSnapshot:{model:"gpt-image-2.5-sunburst",quality:"max",builtin_product:"ChatGPT Images 2.5",verified_on:"2026-10-01",batchContinued:true},submittedParameters:{model:null,quality:null,prompt,transparent_background:true,referenced_image_paths:refs.map(x=>x.path)},actualModel:null,actualQuality:null,prompt:"prompts/"+id+".txt",references:refs,status:"submitted",outputFiles:[]};
const initial=JSON.stringify(record);
await tools.apply_patch("*** Begin Patch\n*** Add File: "+root+"/prompts/"+id+".txt\n+"+prompt+"\n*** Add File: "+root+"/"+recpath+"\n+"+initial+"\n*** End Patch");
let result;
try{result=await tools.image_gen__imagegen({prompt,referenced_image_paths:refs.map(x=>x.path),transparent_background:true});}
catch(e){record.status="failed";record.endedAt=new Date().toISOString();record.rawError=String(e);await tools.apply_patch("*** Begin Patch\n*** Update File: "+root+"/"+recpath+"\n@@\n-"+initial+"\n+"+JSON.stringify(record)+"\n*** End Patch");return{ok:false,slot:record.requested_slot,error:String(e)};}
generatedImage(result);
const host=result.output_hint?.match(/as ([^\r\n]+\.png) by default/)?.[1];
record.endedAt=new Date().toISOString();record.status=host?"native_generated_unreviewed":"returned_path_unresolved";
record.evidence={receipt:"records/"+id+".receipt.json",hostOutput:host??null,toolResultKeys:Object.keys(result),modelReturned:false,qualityReturned:false};
if(host){const rel="work/root-fan-fix/"+id+"-native.png";await tools.exec_command({cmd:"New-Item -ItemType Directory -Force -Path '"+root+"/work/root-fan-fix' | Out-Null\nCopy-Item -LiteralPath '"+host.replace(/'/g,"''")+"' -Destination '"+root+"/"+rel+"' -ErrorAction Stop",max_output_tokens:200});record.outputFiles=[rel];record.native={sourceFile:root+"/"+rel};}
await tools.apply_patch("*** Begin Patch\n*** Add File: "+root+"/records/"+id+".receipt.json\n+"+JSON.stringify({call_id:id,returnedAt:record.endedAt,nativePath:host,output_hint:result.output_hint,actualModel:null,actualQuality:null,toolResultKeys:Object.keys(result)})+"\n*** Update File: "+root+"/"+recpath+"\n@@\n-"+initial+"\n+"+JSON.stringify(record)+"\n*** End Patch");
return{ok:!!host,slot:record.requested_slot,path:record.native?.sourceFile,host,record:recpath,action,direction,frame};
}
