import json,hashlib,shutil
from pathlib import Path
from PIL import Image,ImageDraw
import numpy as np
R=Path('E:/work/image/qdao_city_tiles_4k_20260916/builtin_q64_production')
T=R/'lanxian_day/triple_r08_c06_c08'
im=Image.open(T/'output_v2/r08_c08.png')
sheet=Image.new('RGB',(1800,1800),'white')
for iy,y in enumerate((1024,2048,3072)):
 for ix,x in enumerate((1024,2048,3072)):
  crop=im.crop((x-300,y-300,x+300,y+300)); sheet.paste(crop,(ix*600,iy*600))
sheet.save(T/'qa_v2/c08-nine-intersections.png')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
S=R/'lanxian_spring/r08_c08'
assert not list((S/'native').glob('*.png')) if (S/'native').exists() else True
assert not list((S/'guides').glob('*.png')) if (S/'guides').exists() else True
for d in ('guides','prompts','native','qa','output'): (S/d).mkdir(exist_ok=True)
day=T/'output_v2/r08_c08.extended.png'
neighbor=R/'lanxian_spring/pair_r08_c06_c07/output/r08_c07-extended-context-v6.png'
mother=Image.open(day).convert('RGB');assert mother.size==(4326,4326)
left=Image.open(neighbor).convert('RGB')
mother.paste(left.crop((4096,0,4211,4326)),(0,0))
m=S/'guides/day-v2-geometry-left-spring-v6-context.png';mother.save(m)
patches=[]
for r in range(4):
 for c in range(4):
  id=f'r{r+1:02d}_c{c+1:02d}';box=(c*1024,r*1024,c*1024+1254,r*1024+1254)
  out=S/'guides'/f'{id}.layout-only.png';i=mother.crop(box);i.save(out);j=out.with_name(f'{id}.input-preview.jpg');i.save(j,quality=95,subsampling=0)
  patches.append({'id':id,'row':r+1,'column':c+1,'cropInExpanded':list(box),'guide':str(out),'guideSha256':sha(out),'submittedJpeg':str(j),'submittedJpegSha256':sha(j)})
for r in range(4):
 for c in range(3):
  a=np.asarray(Image.open(S/'guides'/f'r{r+1:02d}_c{c+1:02d}.layout-only.png'));b=np.asarray(Image.open(S/'guides'/f'r{r+1:02d}_c{c+2:02d}.layout-only.png'))
  assert np.array_equal(a[:,-230:],b[:,:230])
for r in range(3):
 for c in range(4):
  a=np.asarray(Image.open(S/'guides'/f'r{r+1:02d}_c{c+1:02d}.layout-only.png'));b=np.asarray(Image.open(S/'guides'/f'r{r+2:02d}_c{c+1:02d}.layout-only.png'))
  assert np.array_equal(a[-230:],b[:230])
p=S/'plan.json';shutil.copy2(p,S/'plan.before-final-day-guides-20260918.json');d=json.loads(p.read_text(encoding='utf-8-sig'))
d.update(status='native_generation_ready',patches=patches,geometryAuthority='final lanxian_day c08 triple output_v2; only accepted spring c07 115px west halo replaces corresponding reference pixels')
d['guidePreparation']={'status':'ready_unified_style_reference','guideOnly':True,'motherCoversExpanded4326':True,'source':str(day),'sourceSha256':sha(day),'mother':str(m),'motherSha256':sha(m),'nativePatchGuidePixels':[1254,1254],'adjacentGuideOverlapPixels':230,'all24GuideOverlapsIdentical':True,'leftNeighborAcceptedHaloWidth':115,'leftNeighborSourceBox':[4096,0,4211,4326],'sourceUpscaled':False}
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
src=R/'lanxian_day/r08_c08/assemble_builtin_single_v1.py'
dst=S/'assemble_builtin_single_v1.py';assert not dst.exists()
dst.write_text(src.read_text(encoding='utf-8').replace('lanxian_day','lanxian_spring'),encoding='utf-8')
print('Spring16 guides ready. No native artwork generated by this script. All24 overlaps exactly identical.')
