from pathlib import Path
from PIL import Image
import hashlib,json,datetime
ROOT=Path(__file__).resolve().parents[2]
OUT=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
p25=ROOT/'qdao_chibi_roster_v11/25_lion_drum_guard';p27=ROOT/'qdao_chibi_roster_v11/27_ink_kite_ranger'
old=read(ROOT/'docs/style-audit-20260910/continuation/review-roster.json')['files']
listed={e['path']:e['sha256'] for e in read(p25/'manifest.json')['files']}
frames=[]
for direction in ['S','W','E','N']:
 for num in range(1,5):
  rel=f'walk/{direction}/{num:02d}.png';p=p25/rel;im=Image.open(p).convert('RGBA');box=im.getchannel('A').getbbox()
  frames.append(dict(path=p.relative_to(ROOT).as_posix(),sha256=sha(p),manifest_sha_matches=sha(p)==listed[rel],size=list(im.size),alpha_bbox=box,touches_canvas=bool(box and (box[0]==0 or box[1]==0 or box[2]==im.width or box[3]==im.height))))
prior=[dict(path=p,sha256=sha(ROOT/p),unchanged_from_previous_review=sha(ROOT/p)==e['current_sha256']) for p,e in old.items() if '/27_' in p]
new27=[dict(path=p.relative_to(ROOT).as_posix(),sha256=sha(p)) for p in (p27/'sources').glob('*.png')]
screen_path='client_ui_refresh_20260908/qa/11-result-native.png'
record=next(e for e in read(ROOT/'docs/style-audit-20260910/continuation/snapshot.json')['records'] if e['path']==screen_path)
screen=dict(path=screen_path,sha256=sha(ROOT/screen_path),snapshot_sha256=record.get('sha256'),unchanged_from_snapshot=sha(ROOT/screen_path)==record.get('sha256'),classification='historical_native_unity_QA_capture',current_runtime_status='Not verified by this asset-folder audit.',runtime_repository='E:/work/mmorpg-client',in_repo_runtime_result_view_found=False,evidence=['client_ui_refresh_20260908/build_review.py:1 describes actual Unity captures','client_ui_refresh_20260908/build_review.py:14 lists 11-result-native.png as battle result','client_ui_refresh_20260908/qa/mcp-battle-capture-start.cs calls external ClientBattleUiQaCapture.StartCaptureAll()','client_ui_refresh_20260908/README.md:3 identifies external client Assets/Resources'],search_scope='Read-only .cs/.py search for battle result view/build definitions in image repository; external runtime not inspected or changed.',action='Keep screenshot as historical evidence. Current result-window skin must be verified and revised in the runtime client task.')
items=[dict(id='25_cardinal_crop',status='resolved_in_formal_image_delivery',producer_qc_status=read(p25/'qc.json')['status'],production_manifest='qdao_chibi_roster_v11/25_lion_drum_guard/manifest.json',old_source='qdao_chibi_roster_v11/25_lion_drum_guard/sources/cardinal.png',old_source_excluded=True,exclusion_record='qdao_chibi_roster_v11/25_lion_drum_guard/sources/rejected_sources.json',replacement='Four individually generated 2x2 cardinal sources composed into cardinal_assembled.png; retained 512px frame canvases and foot anchor (256,471).',visual='Directly reviewed all 16 delivered S/W/E/N frames on dark background: intact boots, hair and gear; no crop crossing or incorrect facing among these four directions.',evidence='docs/style-repair-20260911/nonproduction-25-cardinal-final.jpg',frames=frames),dict(id='27_proportion',status='unresolved_nonproduction_source',formal_manifest_exists=(p27/'manifest.json').exists(),formal_portrait_exists=(p27/'portrait.png').exists(),formal_walk_exists=(p27/'walk').exists(),old_portrait_same_as_new_copy=(p27/'source/portrait_raw.png').read_bytes()==(p27/'sources/portrait_raw.png').read_bytes(),visual='Directly viewed new E/W 2x2 sheets. Lean long-legged anime-like silhouette and relatively small face remain; these do not resolve the previous short-body chibi proportion concern.',action='Continue revision with active character producer, keeping narrow-eye/high-ponytail identity. Do not count raw drafts as approved production assets.'),dict(id='27_diagonal_direction_crop',status='unresolved_nonproduction_source',producer_status=(p27/'STATUS.md').read_text(encoding='utf-8-sig').strip(),formal_manifest_exists=(p27/'manifest.json').exists(),formal_qc_exists=(p27/'qc.json').exists(),available_new_sources=new27,old_sources=prior,conclusion='Old diagonal and SW sources unchanged. New folder contains E/W sheets and an explicitly rejected N identity sheet, with no completed diagonal exports or 8-direction manifest. No evidence of resolution; rejected drafts remain nonproduction.'),dict(id='brown_result_capture',**screen)]
result=dict(checked_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),status='scoped_followup_complete_nonproduction_work_remains',scope='Only previous 27 proportion, 25 cardinal crop, 27 diagonal direction/crop risks and historical brown result capture; not a whole-roster audit.',items=items,assets_modified=False)
(OUT/'nonproduction-followup.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
print('25 cardinal SHA matches:',sum(e['manifest_sha_matches'] for e in frames),'/16; canvas touches:',sum(e['touches_canvas'] for e in frames))
print('27 formal manifest:',(p27/'manifest.json').exists());print('Historical result unchanged:',screen['unchanged_from_snapshot'])
