import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
from PIL import Image
import numpy as np
B=Path('E:/work/image/qdao_city_tiles_4k_20260916/builtin_q64_production')
A=B/'penglai_joint_c12_batch_20260917/audit_20260918'
P=A/'pending_single_reference_prompts';P.mkdir(exist_ok=True)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def writej(p,obj):
 assert not p.exists(),p
 p.write_text(json.dumps(obj,ensure_ascii=False,indent=2),encoding='utf-8')
prompts={
'r02_c01':"Edit the single visible reference image, preserving this exact crop. Redraw this exact full bleed Penglai Mid-Autumn map crop at native1254x1254, highest available visual quality. Lock fixed isometric camera and precise blue-violet stone paving, diagonal bridge railing across lower half, rounded left pillar and right partial ball post. The narrow left strip is exact shared neighbor context: remove its vertical color boundary naturally while connecting the railing and ground joints cleanly, preserving edge crossings and dimensions. Bright readable indigo moonlight with gentle cream amber highlights, smooth round Q-style architecture, clean crisp beveled edges with modest stone facets. No redesign, perspective changes, added stones, characters, signs, text, grain noise, dirty fissures, artificial sharpening or blur. Entire image must remain an opaque continuous scene, never transparent or isolated cutout.",
'r02_c02':"Edit only the single attached reference image, keeping its exact framing and camera. Redraw this full bleed Penglai Mid-Autumn crop at native 1254 by 1254, highest visual fidelity available. Preserve every broad paving slab, diagonal grout line, lower-left blue-violet rounded ball finial and lower-right partial golden lantern lip. Lock the pillar silhouette and all border crossings. Bright indigo moonlight and soft amber pools illuminate clean lilac stone. Use rounded Q-style fantasy game shapes, crisp readable bevels and smooth restrained stone facets. Do not add slab joints, cracks, grain, text, people, objects, sharpening halos, blur, transparent areas or borders. Output one fully opaque scene.",
'r02_c03':"Edit only this single reference, preserving the exact crop, fixed isometric camera and geometry. Repaint this Penglai Mid-Autumn map crop at native 1254 by 1254 with the highest available visual quality. Keep all creamy lilac and violet paving slabs, diagonal grout intersections, raised foundation lip along the top, partial stool legs at upper right and cropped golden lantern cap at lower left. Preserve every footprint, count and edge crossing. Gentle amber illumination should blend naturally into indigo moonlight. Rounded clean Q-style architecture, crisp contours and modest soft stone facets. No new geometry, objects, people, lettering, grain, cracks, blur, artificial sharpening, transparency, collage or frame.",
'r02_c04':"Edit the single attached reference. Preserve this exact full-bleed framing, camera and every paving-slab contour in a native 1254 by 1254 Penglai Mid-Autumn map crop. The upper paving receives creamy amber light and the lower-right paving fades into cool violet moonlight. Keep the cropped raised doorway steps and stool leg along the top, and preserve exact slab count, grout intersections and all edge crossings. Use highest available fidelity, rounded Q-style clean stone bevels and restrained smooth shading. Do not change perspective or scale, add seams or objects, or introduce cracks, dirt, noise, words, people, transparency, blur or sharpening halos.",
'r03_c01':"Edit only the single attached reference, keeping the exact square crop and isometric camera. Redraw at native 1254 by 1254 with highest available clarity. Preserve the diagonal blue-violet bridge railing at the top, its warm-lit rectangular openings, the curved stone arch below, the slim partial right pillar, and the blue water filling the lower-left opening. Lock the arch curve, stone joints and all border crossings. The narrow left neighbor strip contains an artificial vertical color seam: reconstruct a natural continuous wall and connected calm water reflections across it. Bright clean Mid-Autumn moonlight with gentle amber highlights, rounded Q-style stone and crisp bevels. No added joints, props, text, grain, cracks, blur, sharpness halos or transparency.",
'r03_c02':"Redraw only the single reference image at native 1254 by 1254, preserving its exact crop and camera. This Penglai Mid-Autumn bridge detail has a tall rounded blue-violet pillar on the left, two warm-lit rectangular railing openings, diagonal capstone and outer wall, and a glowing round golden paper lantern resting near the upper right. Keep their exact sizes, silhouettes, positions and all border crossings. Rebuild clear lantern ribs, modest rim thickness, clean rounded stone bevels and continuous grout joints with smooth indigo and amber lighting. Highest available visual fidelity, friendly rounded Q-style game art. No new openings, decorations, words, characters, cracks, dirt, grain, blur, halos or transparent areas.",
'r03_c03':"Edit the single attached Penglai Mid-Autumn reference at native 1254 by 1254 and the highest available visual quality. Keep its exact crop, scale and fixed isometric camera. Preserve the large blue-violet ball-topped stone pillar just right of center, the diagonal railing crossing behind it, the warm round lantern cropped at upper left and the broad paving-slab network in the background. Lock the ball, cylindrical pillar, railing openings, floor seams and all edge crossings. Repaint with crisp rounded Q-style contours, smooth stone facets, gentle indigo moonlight and amber highlights. No changed proportions, new joints or props, people, signs, grain, cracks, blur, artificial sharpening, frames or transparency.",
'r03_c04':"Edit only the single attached reference, maintaining exact framing and fixed camera. Redraw this Penglai Mid-Autumn map crop at native 1254 by 1254 with the highest available fidelity. Preserve the broad lilac paving slabs and their diagonal intersections, the near-horizontal stone railing along the bottom, its cropped warm-lit openings, the blue ball post cropped at right and the small golden roof tip at lower right. Keep the slab count, line positions, footprints and border crossings unchanged. Bright readable indigo moonlight with modest amber accents, clean rounded Q-style stone bevels and calm smooth surfaces. No added objects, words, people, dirty texture, cracks, grain, blur, halos or transparent background.",
'r04_c01':"Edit this single exact reference crop into a native 1254 by 1254 Penglai Mid-Autumn game-map detail at highest available quality. Keep the camera, scale and all edge crossings. Preserve the curved underside of the bridge arch entering from the top right, the tall rightmost stone supports, the blue water surface and its broad connected lighter-blue reflection shapes. The left 230-pixel neighbor context has a vertical color/pattern join; repaint that transition as uninterrupted water while preserving the shoreline and reflection crossings at the outer edges. Rounded clean Q-style stone, calm bright indigo water with clear smooth reflection contours. No new objects, foam, tiny ripples, texture noise, dirty cracks, blur, sharpening halos, text, people or transparency.",
'r04_c02':"Edit only the single reference image, preserving its exact crop, scale and fixed isometric camera. Render native 1254 by 1254 at highest available clarity. Retain the broad blue-violet bridge wall, left rounded support columns descending to water, the precise diagonal waterline along the base, the broad connected blue reflection patterns, and the small golden teardrop roof finial cropped at right. Keep every slab joint, silhouette and border crossing. Bright Mid-Autumn indigo shading with small warm golden highlights, clean rounded Q-style stone and crisp controlled water contours. No new geometry, objects, cracks, grain, text, people, blur, halos or transparent areas.",
'r04_c03':"Edit the single attached reference into a native 1254 by 1254 Penglai Mid-Autumn map detail at highest available visual quality. Preserve the exact camera and crop. Keep the tall central blue-violet stone pillar, its rounded shoulder, the bridge wall and warm-lit railing openings behind, and the golden roof edge sweeping diagonally across the bottom with its rounded teardrop finial at lower left. Preserve exact roof slope, tile count, tube ridge segments, joints and border crossings. Clean rounded Q-style Chinese fantasy art, smooth indigo stone and restrained amber roof highlights, crisp readable bevels. No new ornaments, grain, cracks, dirty noise, blur, sharpening halos, text, people, transparency or border.",
'r04_c04':"Edit only the single attached reference, locking its exact framing and fixed isometric camera. Repaint at native 1254 by 1254 with highest available fidelity. Preserve the cropped stone railing and warm rectangular openings across the top, the blue-violet supporting wall behind, and the golden roof filling the lower two-thirds. Keep the diagonal rounded ridge tube, its segment joints, every broad roof-tile lane and the darker violet shadow crossing the lower-left tiles. Match all border crossings and geometry precisely. Rounded clean Q-style fantasy game architecture with smooth controlled highlights and crisp tile contours. No new tiles or ornaments, grain, cracks, dirt, blur, artificial sharpening, people, text, frames or transparency."
}
queue=[]
for id,prompt in prompts.items():
 t=B/'penglai_mid_autumn/r09_c12';assert not (t/'native'/f'{id}.png').exists()
 pp=P/f'{id}.prompt.txt';assert not pp.exists();pp.write_text(prompt,encoding='utf-8')
 ref=t/'guides'/f'{id}.input-preview.jpg'
 queue.append({'appearance':'penglai_mid_autumn','tile':'r09_c12','id':id,'status':'pending_native_generation','tool':'image_gen.imagegen','toolArgs':{'referenced_image_paths':[ref.as_posix()],'prompt':prompt},'promptFile':pp.as_posix(),'promptSha256':sha(pp),'references':[{'path':ref.as_posix(),'sha256':sha(ref)}],'expectedNativePixels':[1254,1254],'preserveOriginalSourceBytes':True,'modelSelectorAvailable':False,'qualitySelectorAvailable':False,'backendModelVerified':False})
writej(A/'mid-autumn-resume-queue.json',{'schemaVersion':1,'createdAtUtc':datetime.now(timezone.utc).isoformat(),'requestedProduct':'ChatGPT Images 2.5','route':'builtin_image_gen','noPaidApi':True,'nativeComplete':4,'nativeMissing':12,'jobs':queue,'resumeInstructions':['Re-inspect each exact reference before generation.','Use referenced_image_paths, not conversation image fallback, while every target has a local path.','After each successful tool return immediately copy original bytes and persist exact prompt, actual references, tool args and output hint; validate native dimensions and alpha.','Preserve existing unsubmitted prompt versions; when recording a successful source make canonical prompt metadata match the exact actual call, retaining the old prompt in an archive.','After 16 sources assemble single tile, then join to current Mid-Autumn pair output/v3. Inspect six full internal lines, full cross-tile line, crossings and all repair borders before ledger selection.']})
error="unable to read referenced image at `E:\\work\\image\\qdao_city_tiles_4k_20260916\\builtin_q64_production\\penglai_mid_autumn\\r09_c12\\guides\\r02_c01.input-preview.jpg`: fs sandbox helper failed with status exit code: 1: windows sandbox failed: helper_unknown_error: apply deny-read ACLs"
writej(A/'image-tool-failure.json',{'createdAtUtc':datetime.now(timezone.utc).isoformat(),'tool':'image_gen.imagegen','toolArgs':queue[0]['toolArgs'],'error':error,'result':'no_output_image_returned','successfulNativeOutputs':0,'requestedProduct':'ChatGPT Images 2.5','backendModelVerified':False,'modelSelectorAvailable':False,'qualitySelectorAvailable':False,'viewImageAlsoFailed':True,'referenceShownViaApprovedBase64Read':True,'paidApiUsed':False,'numLastImagesFallbackUsed':False})
triple=B/'penglai_day/r09_c10_c11_c12_joint/output/triple-12288x4096.png';im=Image.open(triple).convert('RGB')
repairs=[]
for id,box,roi,prompt in [
('water-boundary-upper',[7565,2100,8819,3354],[8060,2300,8400,3270],"Edit the single attached native crop of the Penglai daylight bridge and water. Preserve exactly the crop, camera, curved bridge arch, every stone joint, waterline and outer border crossings. Repair the narrow vertical transition around the center where water reflections and the stone shade have visibly different brush density or brightness. Reconstruct continuous calm cyan reflection shapes and a natural stone lighting transition without changing the arch curve or adding geometry. Use the same clean rounded Q-style fantasy game art, native 1254 by 1254, highest available clarity. Keep the four outer edges unchanged. No blur used to hide the seam, noisy texture, sharpened halos, new objects, letters, people, transparency or framing."),
('water-boundary-lower',[7565,2842,8819,4096],[8060,2920,8400,4096],"Edit only the attached Penglai daylight water crop at native 1254 by 1254 with highest available fidelity. Maintain exact camera, scale, crop and all reflection lines crossing the outer edges. Repair the narrow vertical join near the center: the cyan reflection bands, blue body color and brush density must form one continuous calm water surface with no visible stripe, duplicate contours or abruptly cut highlights. Preserve the large reflection shapes, use clean smooth Q-style game-water contours, and retain the same bright blue palette. Keep all four outer edges unchanged. No new foam or props, noisy ripples, grain, blur masking, sharpening halos, text, characters, transparency or border.")]:
 ref=A/f'{id}.reference.png';assert not ref.exists();im.crop(box).save(ref)
 pp=P/f'{id}.prompt.txt';assert not pp.exists();pp.write_text(prompt,encoding='utf-8')
 repairs.append({'id':id,'appearance':'penglai_day','status':'pending_native_repair','sourceTriple':str(triple),'sourceSha256':sha(triple),'sourceCropLTRB':box,'proposedPasteROIInTriple':roi,'reference':{'path':ref.as_posix(),'sha256':sha(ref)},'toolArgs':{'referenced_image_paths':[ref.as_posix()],'prompt':prompt},'promptFile':pp.as_posix(),'promptSha256':sha(pp),'acceptance':'Use only defect ROI after checking return geometry. Recheck all four paste borders plus overlap between repairs, full c11/c12 boundary and crossings. Preserve zero-mask pixels exactly; no new selected candidates before these pass.'})
writej(A/'day-repair-queue.json',{'coordinateSystem':'triple PNG top-left; c11/c12 seam at x=8192','status':'blocked_by_builtin_reference_path_read','jobs':repairs})
old=B/'penglai_day/r09_c10_c11_joint/output/extended-context.png';new=B/'penglai_day/r09_c10_c11_c12_joint/output/extended-context.png'
l=np.asarray(Image.open(old));n=np.asarray(Image.open(new));assert np.array_equal(l[:,:8192],n[:,:8192])
asm=json.loads((new.parent/'assembly.json').read_text(encoding='utf-8'))
for src in asm['sources']:
 assert sha(Path(src['contextPath']))==src['contextSha256'];assert sha(Path(src['assemblyPath']))==src['assemblySha256']
review={'createdAtUtc':datetime.now(timezone.utc).isoformat(),'reviewer':'Codex visual review of lossless native-pixel crops','appearance':'penglai_day','tile':'r09_c12','sourceTriple':str(triple),'sourceSha256':sha(triple),'status':'needs_native_seam_repair_not_selected','wholeCityComplete':False,'formallyAccepted':False,'runtimePublished':False,'inspected':{'internalFullLines':['x1024','x2048','x3072','y1024','y2048','y3072'],'eachFullLineLength':4096,'stripWidth':300,'method':'Each lossless strip was displayed as four original-pixel 300x1024 panels; horizontal strips rotated only. No resizing.','allNineInternalIntersections':True,'fullC11C12SharedBoundary':True,'sharedBoundarySlicesY':[0,1024,2048,2842],'newRepairReturnBorders':'not applicable; no successful repair yet'},'internalVerdict':'No obvious structural breaks found along all six full lines and nine intersections. Clean outlines retained.','sharedBoundaryVerdict':'Paving/railing/arch geometry continuous, but a visible narrow water brightness and reflection-density transition remains near the center of the lower c11/c12 overlap. Native repaint required before selecting the triple.','defects':[{'id':'c11_c12_water_band','priority':'repair_required','tripleRegionLTRB':[8060,2300,8400,4096],'evidence':['qa_lossless/boundary_y2048.png','qa_lossless/boundary_y2842.png','qa_lossless/boundary_water_top.png','qa_lossless/boundary_water_bottom.png'],'action':'Two overlapping native 1254 repair references prepared; only local ROI may be used, then all patch borders and full shared boundary must be inspected.'}],'observations':['Old left-side pillar retains more stone facets and fissure detail than new c12 clean stone; old/new brush density needs nearest-camera review.','Existing c10/c11 seam and old repair boundaries inherited unchanged; no claim of new independent reapproval.','Cross-appearance microgeometry, all external neighbors, separate foreground, navigation and runtime tests remain outstanding.'],'oldContextFirst8192ColumnsUnchanged':True,'parentContextAndAssemblyHashesMatch':True,'newlyGeneratedSources':0,'newlySelectedCoordinates':0}
writej(A/'visual-review.json',review)
writej(A/'ledger-update.json',{'schemaVersion':1,'createdAtUtc':datetime.now(timezone.utc).isoformat(),'batch':'penglai_c12_audit_20260918','status':'blocked_no_new_selected_candidates','candidates':[],'repairRecords':[],'newUniqueCandidates':0,'newNativeSources':0,'doNotMergeReason':'No new candidate passed full seam review and no source was generated. Preserve existing selected c10/c11 pair versions.','qa':str(A/'visual-review.json'),'mechanicalAudit':str(A/'mechanical-audit.json'),'resumeQueue':str(A/'mid-autumn-resume-queue.json'),'repairQueue':str(A/'day-repair-queue.json'),'toolFailure':str(A/'image-tool-failure.json')})
print(json.dumps({'queueJobs':len(queue),'repairJobs':len(repairs),'newSelected':0,'audit':str(A)}))