from pathlib import Path
from datetime import datetime,timezone
import json,hashlib
r=Path(r'E:\work\image\qdao_original_roster_v13');c=r/'candidate/00_reference_topright_boy';o=r/'review/00_reference_topright_boy'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
m=json.loads((c/'manifest.json').read_text(encoding='utf-8-sig'));v=json.loads((c/'validation.json').read_text(encoding='utf-8-sig'));f=json.loads((c/'review/fresh-review-input.json').read_text(encoding='utf-8-sig'))
assert m['status']=='passed' and v['status']=='passed' and v['reconstructed_frames']==136 and not v['missing_generation_receipts']
assert {x['path']:x['sha256'] for x in m['files']}==f['reviewed_artifacts']
result={'status':'passed_art_asset_seal','character_id':'00_reference_topright_boy','completed_at_utc':datetime.now(timezone.utc).isoformat(),'delivery_png_count':len(m['files']),'genuine_new_walk_frames':m['generated_walk_count'],'genuine_independent_idle':m['generated_idle_count'],'preserved_original_portrait':'whole4096to1024downsample','common_scale':.88,'frame_ms':30,'cycle_ms':480,'reconstructed_source_frames':136,'missing_generation_receipts':[],'manifest':{'path':str(c/'manifest.json'),'sha256':sha(c/'manifest.json')},'qc':{'path':str(c/'qc.json'),'sha256':sha(c/'qc.json')},'validation':{'path':str(c/'validation.json'),'sha256':sha(c/'validation.json')},'visual':{'path':str(c/'review/visual-review.json'),'sha256':sha(c/'review/visual-review.json')},'browser_input_manifest_sha256':f['reviewed_input_manifest_sha256'],'pngs_unchanged_since_browser_capture':True,'browser_evidence':[str(o/'browser-final-candidate/browser-report.json'),str(o/'browser-final-candidate/browser-sequence-report.json')],'visual_evidence_count':len(f['evidence']),'game_integration':'Handed final SHA to asset_pipeline for actual isolated Unity validation and publish; not claimed completed by this art task.','review_gifs':[str(o/'all-eight-directions-normal.gif'),str(o/'all-eight-directions-half-speed.gif')],'approval_history':str(c/'review/approval-history/20260917T131541-cddb60cd')}
(o/'approval-completion.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
p=o/'HANDOFF.md';t=p.read_text(encoding='utf-8-sig');t=t.replace('approve.py第一轮最终源图重建已通过，第二轮require_visual仍在执行，最终状态以 validation.json 及 approval-completion.json 为准。','approve.py两轮最终源图重建及require_visual验证已全部通过，最终状态和三份SHA见 validation.json 与 approval-completion.json。后续不要再运行pipeline review/import，防止重置已封存状态。');p.write_text(t,encoding='utf-8')
print(json.dumps(result,ensure_ascii=False))
