from pathlib import Path
from PIL import Image
import json,hashlib
r=Path(r'E:\work\image\qdao_original_roster_v13');id='04_mountain_guardian_boy';d=r/'generation'/id/'idle-source-references';d.mkdir(parents=True,exist_ok=True)
p=r/'generation'/id/'idle-eightdir-v3/raw.png';raw=Image.open(p).convert('RGBA');order=['S','SW','W','NW','N','NE','E','SE'];ev=[]
for i,v in enumerate(order):
 x=(i%4)*raw.width/4;y=(i//4)*raw.height/2;box=[round(x),round(y),round(x+raw.width/4),round(y+raw.height/2)];im=raw.crop(box);factor=512/max(im.size);im=im.resize((round(im.width*factor),round(im.height*factor)),Image.Resampling.LANCZOS);bg=Image.new('RGBA',(512,512),(255,0,255,255));bg.alpha_composite(im,((512-im.width)//2,(512-im.height)//2));bg.save(d/f'{v}-source-cell.png');bg.convert('RGB').save(d/f'{v}-reference.jpg',quality=90);ev.append({'direction':v,'source_cell_index':i,'box':box,'whole_cell_reference_scale':factor,'reference_sha256':hashlib.sha256((d/f'{v}-source-cell.png').read_bytes()).hexdigest()})
(d/'reference-provenance.json').write_text(json.dumps({'source':str(p),'source_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'purpose':'reference crops only; not exported idle/walk frames','cells':ev},indent=2),encoding='utf-8')
out=r/'review'/id;out.mkdir(parents=True,exist_ok=True)
(out/'baseline-audit.json').write_text(json.dumps({'id':id,'source_commit':'9adcf9291e4a867601868889a5965f3cd48630ba','portrait_source':str(r/'baseline/q_daoist_character_pack_4096/04_mountain_guardian_boy_transparent_4096.png'),'portrait_sha256':'371bb4d303cc5bde21e73eb4ddba277aebee06b5ad65d81301ea828804263521','existing_walk_found':False,'git_tree_files':['q_daoist_character_pack_4096/04_mountain_guardian_boy_transparent_4096.png','q_daoist_character_pack_4096/prompts/04_mountain_guardian_boy_transparent_4096.prompt.txt','q_daoist_character_pack_4096/records/04_mountain_guardian_boy_transparent_4096.json'],'existing_image_search':'Exact mountain_guardian filename and manifest searches found static portraits and style backups only; character_move_8dir belongs00 and is not used for04.','action_plan':'All128walk plus8independentidle real built-in image_gen; originalportrait exact downsample; no mirror/warp/generated-code poses.','scale_decision':'Common_scale not fixed until S anchors compare to idle; provisional0.84 to keep ~400px subject on512canvas.'},indent=2),encoding='utf-8')
print(d)
