from row_tools import *
out=ROOT
failed=Path('C:/Users/luyua/.codex/generated_images/01a10bb7-4da4-7553-abb9-125e7fe01ccc/exec-b8609515-d5b3-4c28-a729-779e36d01201.png')
params={'model':None,'quality':None,'prompt':(out/'p34-repair.prompt.txt').read_text(),'referenced_image_paths':[str(out/'p34-draft.png'),str(out/'p34.edit-target.png'),str(REPO/'designs/gameplay-ui/04-guild.png')],'transparent_background':False}
write(out/'p34-repair.call.json',params)
write(out/'p34-repair.generation.json',{'file':str(failed),'sha256':sha(failed),'generatedAt':stamp(),'nativePixels':list(Image.open(failed).size),'width':1254,'height':1254,'format':'PNG','tool':'image_gen.imagegen','route':'builtin','toolResultPath':str(failed),'toolResultEvidence':str(out/'p34-repair.tool-result.txt'),'configSnapshot':json.loads((REPO/'config/image-generation.json').read_text(encoding='utf-8-sig')),'submittedParameters':params,'actualModel':None,'actualQuality':None,'unverifiedReason':'Host-managed; model/quality selectors and results not exposed.','prompt':str(out/'p34-repair.prompt.txt'),'references':[ref(Path(p),'edit target' if i==0 else 'geometry reference' if i==1 else 'main approved style') for i,p in enumerate(params['referenced_image_paths'])],'selected':False,'rejectionReason':'Removed real upper-left diagonal grout while removing the erroneous short branch; unsuitable geometry.'})
draft=out/'p34-draft.png'; left=out/'p33.png'; dest=out/'p34.png'
im=Image.open(draft).convert('RGB'); im.paste(Image.open(left).convert('RGB').crop((1024,0,1254,1254)),(0,0));im.save(dest)
write(str(dest)+'.generation.json',{'file':str(dest),'sha256':sha(dest),'createdAt':stamp(),'width':1254,'height':1254,'format':'PNG','tile':'r10_c12','globalPatchXYWH':[48013,38797,1254,1254],'globalCoreXYWH':[48128,38912,1024,1024],'sourcePixelScale':1,'singleNativeGeneration':False,'allPixelsFromNativeAIGeneration':True,'actualModel':None,'actualQuality':None,'unverifiedReason':'Derived from builtin outputs with no model/quality disclosed.','derivedFrom':[{'file':str(s),'sha256':sha(s),'generationRecord':str(s)+'.generation.json'}for s in [draft,left]],'operation':{'kind':'exact_adjacent_overlap_replacement','base':str(draft),'source':str(left),'cropLTRB':[1024,0,1254,1254],'pasteXY':[0,0],'scale':1,'resampling':False,'warp':False,'feather':0,'reason':'p34 draft hallucinated a short grout branch within left230px overlap. Correct geometry already exists in native p33; preserve exact shared pixels.'},'formalAccepted':False,'productionStage':'native pixel detail fragment for parent assembly; not complete4K'})
v=json.loads((out/'p34-draft.png.generation.json').read_text());v['globalPatchXYWH']=[48013,38797,1254,1254];v['globalCoreXYWH']=[48128,38912,1024,1024];v['submittedParameters']['prompt']=(out/'p34-draft.prompt.txt').read_text();v['selectedAsWholePatch']=False;v['selectedRegionLTRB']=[230,0,1254,1254];v['knownDefect']='Extra grout branch in left230px, excluded from derived p34';write(out/'p34-draft.png.generation.json',v);write(out/'p34-draft.call.json',v['submittedParameters'])
print(dest,sha(dest))
