import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
from PIL import Image
R=Path('E:/work/image/qdao_city_tiles_4k_20260916');B=R/'builtin_q64_production';D=B/'penglai_next_c13_plan_20260920';D.mkdir()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
jobs=[]
for app,version in [('penglai_day','output_v2_20260918'),('penglai_mid_autumn','output_v2_20260920')]:
    assert not (B/app/'r09_c13').exists()
    old=json.loads((B/app/'r09_c12/plan.json').read_text(encoding='utf-8-sig'));layout=Path(old['layoutSource']);assert sha(layout)==old['layoutSourceSha256']
    selected=B/app/'r09_c10_c11_c12_joint'/version/'extended-context.png';im=Image.open(selected);assert im.size==(12518,4326)
    dest=D/app;dest.mkdir();edge=dest/'c12-right-overlap-230x4326.png';im.crop((12288,0,12518,4326)).save(edge)
    # Layout previews are explicitly resampled references, never native art or candidates.
    s=Image.open(layout);w,h=s.size;box=[(49152-115)*w/65536,(32768-115)*h/65536,(53248+115)*w/65536,(36864+115)*h/65536]
    crop=dest/'wholemap-c13-extended-layout-reference-only.png';s.resize((1254,1254),Image.Resampling.BICUBIC,box=tuple(box)).save(crop)
    context=dest/'c12-right-neighbor-preview-reference-only.png';im.crop((8192,0,12518,4326)).resize((1254,1254),Image.Resampling.LANCZOS).save(context)
    jobs.append({'appearance':app,'tile':'r09_c13','status':'planned_not_generated','sourceSelectedNeighbor':'r09_c12','candidateParentContext':str(selected),'candidateParentSha256':sha(selected),'requiredSelectedVersion':version,'exactNeighborOverlap':{'path':str(edge),'sha256':sha(edge),'pixels':[230,4326],'sourceBoxLTRB':[12288,0,12518,4326],'futureDestinationLTRB':[0,0,230,4326]},'layoutOnlyReference':{'path':str(crop),'sha256':sha(crop),'source':str(layout),'sourceSha256':sha(layout),'sourcePixels':[w,h],'sourceCropBoxLTRB':box,'pixels':[1254,1254],'resampledReferenceOnly':True},'neighborPreviewReference':{'path':str(context),'sha256':sha(context),'resampledReferenceOnly':True},'finalPixelRectXYWH':[49152,32768,4096,4096],'worldRect':{'x':275,'z':131.25,'width':18.75,'height':18.75},'plannedBaseNativePatches':16,'baseNativeAlreadyGenerated':0})
plan={'schemaVersion':1,'createdAtUtc':datetime.now(timezone.utc).isoformat(),'batch':'penglai_r09_c13_day_and_mid_autumn','status':'plan_prepared_waiting_c12_root_merge_before_generation','wholeCityPixels':[65536,65536],'deliveryTilePixels':[4096,4096],'nativePatchPixels':[1254,1254],'nativeGrid':[4,4],'core':1024,'halo':115,'overlap':230,'jobs':jobs,'route':'builtin_image_gen_only','actualModelQuality':'host-managed, unverified selectors','referenceArtUpscalingDisclosure':'Planning previews may be resampled; never count them as final art. Final candidate must come from new native details.','generationStarted':False,'requiredSequence':['Root first merges completed c12 ledger and verifies parent versions match selected current-batch.','View wholemap layout and exact neighbor context. Generate a fresh day local-structure reference with builtin Image; preserve established geometry, endpoints and camera.','Derive a shared 4326-square layout-only canvas and paste exact saved 230-pixel neighbor context; create 16 integer 1254-square guide crops; validate 24 overlaps.','Generate 16 day native detail patches with exact submitted-reference hashes; mechanically join without source enlargement.','Use the same reviewed day geometry for Mid-Autumn local structure, preserving buildings, road, steps, rail and waterline. Build guides with exact Mid-Autumn neighbor context then generate 16 native details.','Join new candidates to selected c12 context; review every full internal line, junction and external shared edge; repair only evidenced defects; retain all versions and source bytes.','Emit separate incremental ledger for root merge; no formal/runtime acceptance at this local stage.'],'runtimePublished':False,'formallyAccepted':False}
(D/'plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8');print(D/'plan.json')
