from pathlib import Path
p=Path(r'E:\work\image\qdao_chibi_roster_v12\review\verify_review_pages.cjs');t=p.read_text(encoding='utf-8')
t=t.replace("const fs=require('fs');const assert=require('assert');", "const fs=require('fs');const assert=require('assert');\nconst previewSources=JSON.parse(fs.readFileSync('E:/work/image/qdao_chibi_roster_v12/review/site/preview-source-verification.json','utf8'));\nconst expectedPublished=new Set(previewSources.characters.map(c=>c.character_id));\nconst expectedPending=new Set(previewSources.pending);\nconst expectedExported=Number(process.env.QDAO_EXPECTED_EXPORTED||expectedPublished.size);\nassert.equal(expectedPublished.size,expectedExported,'Published preview count does not match requested QA scope');")
t=t.replace("if(/^2[78]_/.test(name)){", "if(expectedPending.has(name)){")
t=t.replace("let directions=0;", "let directions=0,disabled=0;")
t=t.replace("assert(await page.locator('#play').isDisabled());continue;", "assert(await page.locator('#play').isDisabled());disabled++;continue;")
t=t.replace(" for(const dr of ['S','SW','W','NW','N','NE','E','SE']){", " assert(expectedPublished.has(name),'Role missing from verified preview source list: '+name);\n for(const dr of ['S','SW','W','NW','N','NE','E','SE']){")
t=t.replace("candidatesDisabled:2,", "candidatesDisabled:disabled,")
t=t.replace("await page.locator('#character').selectOption('24_lu_dongbin');await page.locator('#play:not([disabled])').waitFor();", "assert.equal(directions,expectedExported*8);assert.equal(disabled,8-expectedExported);\nawait page.locator('#character').selectOption('24_lu_dongbin');await page.locator('#play:not([disabled])').waitFor();",1)
p.write_text(t,encoding='utf-8')
print('QA now checks the published preview source list and optional QDAO_EXPECTED_EXPORTED count')
