from pathlib import Path
p=Path(r'E:\work\image\qdao_chibi_roster_v12\review\approve_lion_guard_20260914.py');t=p.read_text(encoding='utf-8-sig')
t=t.replace('candidate-stable-body/25_lion_drum_guard','candidate-natural-body/29_he_xiangu').replace('25_lion_drum_guard','29_he_xiangu').replace('25-lion-guard','29-he-xiangu-natural').replace('../../review/25_lion_guard_natural_fixes/phase-plan.json','candidate-source-review.json').replace('lu_natural_west','lu_natural_east').replace('5d90d5b04eea74bf5f780e221fc5cfb8e1de313faac344e9258a4e9b45a7b840','1a6ea359e1b8b5d99653b624ceb197d204ab11300c6ce67824c301a18994070e')
t=t.replace('Distinct short-haired sturdy lion drum guard identity, red and ivory cloth costume, dark trousers, wraps and boots; no magical light or fantasy armor.','New plain-cloth He Xiangu identity: youthful dark low bun, ivory crosscollar tunic, pale sage overrobe, dark green sash, full-length pale trousers and ivory flats. White lotus pin on anatomicalRIGHT, single small closed lotus behind anatomicalLEFT shoulder. New portrait uses same costume. No glow, petal skirt or fantasy armor.')
t=t.replace('10 authored lower pre-contact poses remove the prior high-knee march; strong guard strides and modest rear heel lift retained as character motion.','64 newly authored low walking poses across8 directions, real opposing contacts/passing/precontacts and natural arm opposition. Root reviewed every full direction before final idle correction and all6 corrected idle directions afterward; NE/NW independently authored and reviewed by east.')
t=t.replace('3 idle head shapes rebuilt to match same-direction walks; source changes limited to13 whole cells and cycle rotation.','Six neutral idles redrawn to match authored walks;NE/NW independent idle retained. Final same-direction mean dark-head width difference at most2.3percent; source raw silhouette metric is diagnostic and not used to resize.64 walk intrinsic alpha/G/geometry remain identical after new idle references and4px edge cleanup.')
t=t.replace('25 visually approved','29 visually approved')
out=p.with_name('approve_he_natural_20260914.py');out.write_text(t,encoding='utf-8')

