import json,hashlib
from pathlib import Path
R=Path(r'D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/characters/14_short_hair_snow_summoner_girl')
B=R.parent/'09_bamboo_archer_girl/runtime/run'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
out=[]
for d in ['N','NE','NW']:
 for n in ([1,2,5,6,7,8,9,10,13,14,15,16]+([12] if d=='NW' else [])):
  f=f'{n:02}';srcf='01' if d=='N' and n==6 else f
  formal=R/'run'/d/(srcf+'.png');m=read(Path(str(formal)+'.generation.json'))
  gp=Path(m['derivedFrom']['generationRecord']);gp=gp if gp.is_absolute() else R/gp;g=read(gp)
  source=R/m['derivedFrom']['file']
  if not source.exists():source=Path(g['evidence']['toolReturnedPath'])
  assert source.exists(),source
  assert sha(source)==g['sha256'],source
  sr=m['registrationTransform']['sourceRoot'];assert m['registrationTransform']['globalScale']==.8,(d,n)
  left=n<=8;support='LEFT' if left else 'RIGHT';swing='RIGHT' if left else 'LEFT';k=(n-1)%8;position=k//2+1;sub=k%2+1
  detail={1:f'P1 front landing position, variant {sub}/2. The {support} support foot lands IN FRONT OF the hip along the direction of travel, slightly farther away in the ground-plane perspective. Its full sole is flat on the virtual ground and its knee softly flexes under load. The {swing} leg is folded behind with its heel raised. The front landing contact must be visibly forward of the usual under-hip support spot, not merely the same vertical leg.',
   2:f'P2 under-hip passing position, variant {sub}/2. The {support} support foot remains FLAT on the ground almost directly below the hip; the body is passing over it. Knee softly bent, loaded ankle stable, no sole facing the camera. The {swing} knee recovers forward with its heel raised.',
   3:f'P3 slightly rearward load position, variant {sub}/2. The SAME {support} foot is STILL PLANTED FLAT on the virtual ground but now a small visible distance BEHIND the hip along the travel axis. Knee extends as the body has passed this foot. The {swing} knee swings forward, its foot raised and clearly not bearing weight. It is NOT a flight frame and NOT two feet lifted. Show real ankle/heel/toe support behind the body.',
   4:f'P4 rear push-off position, variant {sub}/2. The SAME {support} leg extends farther BEHIND the hip along travel axis. The FRONT BALL/TOES of this boot still press on virtual ground while its heel rises a little, creating a clear final push-off contact. The {swing} knee is forward, its boot lifted ready for the next landing. No flight yet; one real toe-pad contact, no full flat sole floating toward the viewer.'}[position]
  projection={'N':'Exact NORTH rear view. Screen top is forward/deeper, screen bottom is rear/closer. Feet move fore/aft in depth in narrow parallel tracks; do not spread them sideways. LEFT is screen-left, RIGHT screen-right. Front-leg boot upper and rear-leg heel/sole must follow this perspective; avoid showing two complete matching soles.',
   'NE':'Three-quarter rear NORTHEAST view, travelling toward upper-right. A foot IN FRONT of hip goes upper-right/deeper; a foot BEHIND hip goes lower-left/closer. Foot longitudinal axes remain upper-right/lower-left, knee/ankle aligned; no outward splay. Anatomical left is the farther leg, anatomical right nearer.',
   'NW':'Three-quarter rear NORTHWEST view, travelling toward upper-left. A foot IN FRONT of hip goes upper-left/deeper; a foot BEHIND hip goes lower-right/closer. Foot longitudinal axes remain upper-left/lower-right, knee/ankle aligned; no outward splay. Anatomical left is the nearer leg, anatomical right farther.'}[d]
  prompt='Use case: identity-preserve. Edit IMAGE1 as one single production sprite, preserving its canvas and character size. IMAGE1 is the ONLY identity/composition/upper-body reference. IMAGE2 bamboo girl is shoe-axis/perspective reference only, do not copy her character, limbs, props or phase. IMAGE3 is approved painted style.\nChange ONLY the two legs from hip joints downward and the immediately overlapping skirt edge necessary for anatomy. Keep head, ears, neck, shoulders, torso, waist bow, both arms, fox, crystal, their exact scales and positions unchanged. No zoom, no larger head, no longer torso, no recentering.\n'+projection+'\n'+detail+(' For second variant show subtly more knee loading/extension than the first while maintaining the same spatial contact zone; independently drawn actual posture.' if sub==2 else ' This is the earlier pose in the two-frame spatial contact zone.')+'\nExactly two arms and two legs. LEFT arm holds one white fox. RIGHT connected shoulder/elbow/wrist/palm holds one blue snowflake crystal. Same short white bob, furry ears, left hair ornament, white-lilac short fur robe, rear purple bow; no girl tail, no back fox-face belt buckle. Ground plane is invisible: no floor, shadow, background or guide marks. All boots inside the existing full square canvas with margin. Transparent RGBA, sharp detailed painted sprite, no text, no motion trails, no copies.'
  if d=='N' and n==6:prompt+='\nException for this one slot: preserve IMAGE1 head/upper-body size and location exactly, but set the existing connected right forearm palm to a medium swing height, approximately y640 of the1254px native canvas, crystal directly above it; no extra arm. Keep the fox arm unchanged. The required LEFT foot remains planted in P3, do not reproduce the reference landing pose.'
  q={'id':f'north-bamboo-ground2-{d}-{f}-v1','direction':d,'frame':f,'position':position,'variant':sub,'supportLeg':support.lower(),'registrationSourceRoot':sr,'inputFormalFile':str(formal),'inputFormalSha256':sha(formal),'inputNativeSha256':sha(source),'configSnapshot':read(Path('D:/work/image/config/image-generation.json')),'params':{'prompt':prompt,'transparent_background':True,'referenced_image_paths':[str(source),str(B/d/'03.png'),'D:/work/image/designs/jubaozhai-ui/02-characters.png']}}
  (R/'provenance'/(q['id']+'.request.json')).write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf-8');out.append(q)
(R/'provenance/north-bamboo-ground2-requests.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps([{'id':q['id'],'source':q['params']['referenced_image_paths'][0],'root':q['registrationSourceRoot']} for q in out],ensure_ascii=False))
