from pathlib import Path
import importlib.util,json
HERE=Path(__file__).resolve().parent;TOOLS=HERE.parent;ROOT=TOOLS.parents[2]
spec=importlib.util.spec_from_file_location('archive',TOOLS/'archive_generation.py');arc=importlib.util.module_from_spec(spec);spec.loader.exec_module(arc)
prompt='''Use case: precise-object-edit, identity-preserve.
ONE transparent high-resolution SOUTH walking sprite for 06_thunder_caster_boy, S03. Input 1 is the EDIT TARGET, the already approved high-resolution body and pose. Make one very small correction: its SCREEN LEFT supporting boot is tipped upward too much, revealing too much dark underside. Turn ONLY that boot downward to the S03 angle in input 2, with a nearly frontal toe and almost no underside visible. Keep its foot baseline, ankle connection and location unchanged. The SCREEN LEFT knee remains in the same pose; the SCREEN RIGHT bent trailing leg and boot stay unchanged. Do not copy the walking phase from any other reference.
Input 2 is the authoritative old S03 pose reference only. Match its SCREEN LEFT boot angle: almost front-facing gold toe band and very narrow dark bottom rim, not a broad visible sole. Do not copy its low resolution or contaminated edges. Keep input 1 exact head, face, hairstyle, body size, hand placement, staff, plaque, torso, outfit, waist, knees, trailing boot and framing. Do not shrink the character or change figure height to make the boot correction. The currently excellent head size and short chibi proportions of input 1 are locked.
Input 3 is neighboring S02 native source for physical SCALE ONLY, never pose. Input 4 is identity and costume only, never pose or camera. Input 5 is approved PRIMARY STYLE reference: luminous clean rounded hand-painted Daoist chibi finish; ignore its UI/background/text/other characters.
Retain exact front-facing SOUTH mild elevated game camera. Preserve all hair, ornaments, equipment and gold/ivory/navy/turquoise colors. Screen-left hand holds pointed golden lightning staff; screen-right hand holds rectangular talisman. No new props, fingers or limbs. Preserve the entire input 1 composition and native square canvas occupancy, top hair and grounded foot baseline; one complete character, all parts inside frame. Native transparent PNG at least 1024 each side, preferably 1536 if supported. Only whole-cell .88 downsampling and integer foot anchoring at942 follows, no individual bounding-box scaling.
True transparent alpha, empty outside character and between limbs and equipment. Retain clean colored antialiasing. Zero pink/magenta/red/purple/green edge contamination from old references. Correct local material colors on the modified boot edge; do not erode or thicken outlines elsewhere. No halo, glow, shadow, ground, backdrop, fake checkerboard, text or watermark. Return one complete transparent sprite with ONLY the stated supporting boot angle correction.'''
refs=[TOOLS.parent/'06-generation/S03-edge-final-v2/raw.png',ROOT/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/walk/S/03.png',TOOLS.parent/'06-generation/S02-edge-final-v1/raw.png',ROOT/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
print(json.dumps(arc.prepare('S03-edge-final-v3',prompt,[str(p) for p in refs]),ensure_ascii=False))
