from row_tools import ROOT,TASK,REPO,write,sha,stamp
from PIL import Image
patches=[]
for i in range(1,5):
 p=ROOT/f'p3{i}.png'; g=TASK/'guides'/p.name
 patches.append({'id':p.stem,'file':str(p),'sha256':sha(p),'nativePixels':list(Image.open(p).size),'generationRecord':str(p)+'.generation.json','prompt':str(ROOT/(p.stem+'.prompt.txt')),'toolResultEvidence':str(ROOT/(p.stem+'.tool-result.txt')),'coreGlobalRectXYWH':[49152+(i-1)*1024,34816,1024,1024],'guideSource':{'file':str(g),'sha256':sha(g),'productionPixels':False}})
report={'updatedAt':stamp(),'task':'r09_c13 native micro-row 3','appearance':'penglai_mid_autumn','outputDirectory':str(ROOT),'newNativeFragments':4,'newFull4KTiles':0,'formalAccepted':False,'nativeUpscalingPerformed':False,'rowHasFullCoreCoverage':True,'coreCoveragePixels':[4096,1024],'patches':patches,'configTarget':{'model':'gpt-image-2.5-sunburst','quality':'max'},'submittedModel':None,'submittedQuality':None,'actualModel':None,'actualQuality':None,'visualInspection':{'inspectedAt':stamp(),'method':'view_image tool; all generated full images, 1536px row overview, three vertical 512x1024 seam windows at original pixels, 16 original 256x256 patch corner crops','files':[{'file':str(ROOT/f),'sha256':sha(ROOT/f)} for f in ['row3-preview.png','internal-seams-100pct.png','all-patch-corners-100pct.png']],'positiveFindings':['All four generated images are native 1254x1254 PNG and preserve intended macro-geometry.','p31 removed source-guide vertical composite boundary by AI repainting.','Paving grout, lantern/post, railing, steps and planter follow the provided guide without new objects.','All three raw core joins inspected; no gross broken road, missing shape or duplicate object apparent.'],'limitations':['Raw core joins are not pixel-identical in overlap. p32/p33 and p33/p34 can show local painterly surface/tone differences; parent should assess limited seam matching during full-block assembly.','Patch corner inspection covers individual fragment corners only, not cross-row four-patch junctions.','p31 left external boundary to historical c12 and all row2/row4 joins require parent full-block QA.','Stone textures have visible broad brush planes; avoid further sharpening or adding grain.'],'status':'native fragments ready for parent assembly, not accepted 4K delivery'},'preview':str(ROOT/'row3-preview.png'),'retention':'Native fragments and edit targets are current in-process dependencies. No cross-task source deleted.'}
write(ROOT/'row3-report.json',report)
print('row3 report ready')
