from pathlib import Path
import json,datetime
ROOT=Path(__file__).resolve().parents[1]
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
rejections=[]
for prefix,reason,adopted in [('attack-W-01-rejected-raised-paw','Baseline frame incorrectly raised RF before anticipation','runtime/attack/W/01.png')]+[(f'attack-E-{n:02}-rejected-support-drift','Recovery right forepaw landed behind baseline footprint, closure needed repair',f'runtime/attack/E/{n:02}.png') for n in [10,11,12]]:
    p=ROOT/'receipts'/(prefix+'.generation.json');r=json.loads(p.read_text(encoding='utf-8-sig'))
    r['prompt']=str(ROOT/'prompts'/(prefix+'.txt'));r['evidence']['receipt']=str(ROOT/'receipts'/(prefix+'.json'))
    r['disposition']={'status':'rejected_and_replaced','reason':reason,'supersededBy':adopted,'runtimeImageReplaced':True,'noBackupImageCreated':True,'sourceNativePathStillRecorded':True}
    p.write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8');rejections.append({'record':str(p.relative_to(ROOT)).replace('\\','/'),'reason':reason,'supersededBy':adopted})
for p in (ROOT/'runtime'/'attack').rglob('*.png.generation.json'):
    r=json.loads(p.read_text(encoding='utf-8-sig'));r['visualStatus']='single-frame and contact-sheet inspected; playback not certified by attack agent';p.write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8')
review={'action':'attack','reviewedAt':now,'adoptedFrames':24,'independentImageGenCalls':28,'rejectedFrames':rejections,'singleFrameReview':{'inspectedAll24ReturnedImages':True,'inspectedFinalExportContactSheets':['qa/attack-E-contact.jpg','qa/attack-W-contact.jpg'],'direction':'E true front/down-right; W independently generated true rear/up-left; no front/back flips observed','anatomy':'Same anatomical right forepaw performs the entire attack. Four quadruped limbs preserved with natural occlusion of far support legs. No weapon, no humanoid hands. One ringed curled tail with two jade beads and one cream tassel; cape remains bamboo-leaf garment.','phases':'Visible anticipation, RF lift/flex, forward extension and strike on07, downward arc, RF recovery, grounded return. E10..12 specifically regenerated against E01 baseline footprint.','crop':'All effective body pixels inside canvas; sparse low-alpha edge pixels retained. No crop-to-feet or per-frame realignment.','remainingNotes':'Fine fur, leaf contours and support silhouettes have independent-generation variation. Static review does not certify perfect motion registration.'},'playbackReview':{'completedByThisAgent':False,'reason':'CUA file URL preview rejected by browser URL security policy; no workaround attempted. Main agent must record any independently completed normal/0.25x playback review.'},'clientIntegration':'Not performed; out of scope','technicalReport':'qa/attack-technical.json','production':'Builtin image_gen only. Exact original E/W identities and approved style image attached on every call. Config target gpt-image-2.5-sunburst/max; submitted/actual model and quality null because tool did not expose them.'}
(ROOT/'qa'/'attack-review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2),encoding='utf-8')
print('Attack review and rejected source links updated.')
