from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
import numpy as np
from PIL import Image
OUT=Path(__file__).resolve().parent;TILE=OUT.parent
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 path=OUT/'review.json'
 if path.exists():raise FileExistsError('Do not overwrite existing early QA review')
 m=json.loads((OUT/'export.manifest.json').read_text(encoding='utf-8'));top=np.array(Image.open(m['topRow']['file']));north=np.array(Image.open(m['sourceNorth']['file']));assert sha(m['sourceNorth']['file'])==m['sourceNorth']['sha256'];assert sha(m['topRow']['file'])==m['topRow']['sha256']
 observations={
 'northjoin-c01':'Actual full1024x512 join viewed. Existing leaf cluster, tree/planter/pillar parts, ivory paving and diagonal beveled grooves continue across the real north join at board y256. No detached contour, missing material, newly added object or straight horizontal exposure stripe was observed. Natural leaf overlaps and stone highlights remain.',
 'northjoin-c02':'Actual full1024x512 join viewed. Quiet ivory paving connects through the true north boundary. Broader low-contrast painted stone patches appear within the lower area but do not start as a hard straight seam line. No structural interruption or clear exposure step was observed.',
 'northjoin-c03':'Actual full1024x512 join viewed. Ivory paving and the existing diagonal groove entering near the lower-right retain their form. Soft stone brush variation is spatially irregular, not a straight join band. No missing structure or clear straight color discontinuity was observed at the actual boundary.',
 'northjoin-c04':'Actual full1024x512 join viewed. The diagonal beveled groove on the left, purple-gray tree shadow and existing green foliage at the right retain continuous shape at the north boundary. No cut-off shadow contour, shifted line or abrupt horizontal band was observed.',
 'guide-y115-c01':'Actual1024x128 band viewed across target core y51:179, guide end at y115. Existing leaf contours and multiple paving bevels continue through the guide end. No new horizontal wall, cut leaf footprint, missing groove or clear tonal stripe was observed.',
 'guide-y115-c02':'Actual1024x128 band viewed across y115. Broad, low-contrast ivory stone brush shapes vary naturally; their diagonal/irregular boundaries do not coincide as a straight horizontal cut. No repairable contour gap or hard guide-end band was observed.',
 'guide-y115-c03':'Actual1024x128 band viewed across y115. Quiet paving and the slanted dark/ivory groove near the right continue without a visible notch at the guide-end row. Painted tonal variation is retained; no clear horizontal color step was observed.',
 'guide-y115-c04':'Actual1024x128 band viewed across y115. The gray-purple shadow contains broad soft brush facets and rounded shadow silhouette; the right leaf edge remains intact. No guide-end clipping or straight horizontal exposure stripe was observed.',
 'corner-nw':'Actual512x512 own upper-left corner viewed. Existing shrub cluster, contact shadow, partial left pillar and connected ivory groove junctions remain coherent. No local missing contour or rectangular guide boundary was seen. This does not validate the absent west neighbor or four-tile junction.',
 'corner-ne':'Actual512x512 own upper-right corner viewed. Existing foliage, gray-purple shadow and lower stone rail/column continue as normal object coverage. No local truncation or guide-end stripe was seen. This does not validate the absent east neighbor or four-tile junction.'}
 checks=[];now=datetime.now(timezone.utc).isoformat()
 for c in m['checks']:
  p=Path(c['file']);assert sha(p)==c['sha256'];a=np.array(Image.open(p));x0,y0,x1,y1=c['targetCoreBoxLTRB']
  expected=np.concatenate([north[3840:4096,x0:x1],top[0:256,x0:x1]],axis=0) if c['kind']=='external_north_join' else top[y0:y1,x0:x1]
  assert np.array_equal(a,expected),c['rangeId']
  checks.append({**c,'actuallyViewed':True,'viewedAtUtc':now,'viewMethod':'tools.view_image(detail=original); no downscaled visual evidence','pixelMappingVerified':True,'observation':observations[c['rangeId']],'missingStructure':False,'existingContourMisalignment':False,'clearStraightColorBand':False,'newDefectROIs':[],'result':'no_new_actionable_defect_observed'})
 sourceVerified=[]
 for src in m['sourceNative']:
  assert sha(src['file'])==src['sha256'];assert sha(src['generation']['file'])==src['generation']['sha256'];sourceVerified.append({'file':src['file'],'sha256':src['sha256'],'stillUnchanged':True})
 r={'schemaVersion':1,'reviewedAtUtc':now,'reviewer':'row03_relay','tile':'r09_c10','status':'early_north_review_passed_requested_scopes_no_repair_required','qualifiedComplete4KCandidate':False,'formalAccepted':False,'clientValidated':False,'wholeCityComplete':False,'sourceExport':{'file':str(OUT/'export.manifest.json'),'sha256':sha(OUT/'export.manifest.json')},'northSelected':m['sourceNorth'],'firstRowSources':sourceVerified,'topRow':m['topRow'],'topRowRawRGBSha256':m['topRowRawRGBSha256'],'coverage':{'actualNorthJoinSegments':4,'eachNorthJoinPixels':[1024,512],'fullActualNorthJoinLengthPixels':4096,'guideEndSegments':4,'guideEndCoreY':115,'eachGuideBandPixels':[1024,128],'fullGuideEndLengthPixels':4096,'ownUpperCorners':2,'eachCornerPixels':[512,512],'totalNativeRangesViewed':10,'allActualOriginalPixelViews':True,'allPixelMappingsVerified':True},'checks':checks,'newDefects':[],'repairPlan':None,'summary':'All4 actual north-join segments, all4 first-row guide-end segments and both upper own corners were actually viewed at native pixels. No missing structure, clearly shifted existing contour or hard straight tonal band requiring correction was observed. No upstream or native image was modified.','retainedNaturalVariations':['Low-contrast broad ivory stone brush shapes in columns2/3','Soft polygonal paint variation within the existing purple-gray tree shadow in column4','Small leaf overlap, bevel-width and ink-weight variations consistent with the existing art'],'inheritance':{'condition':m['inheritanceCondition'],'requiredFutureCoreTopRows':[0,1024],'requiredPixels':[4096,1024],'requiredTopRowRawRGBSha256':m['topRowRawRGBSha256'],'northSourceRequiredSha256':m['sourceNorth']['sha256'],'ifIdentityMatches':'Final assembly may inherit these10 early QA scopes without repeating the same views.','ifChanged':'Review changed supports plus surrounding junctions before inheriting affected scopes.'},'limitations':['Only first native row is assembled here; this is not a full4096x4096 tile candidate.','Other internal rows, vertical reference-band ends, west/east/south neighbors and four-tile corner joins are outside this early-north assignment.','No formal art acceptance, runtime/client validation or whole-city completion is claimed.'],'sourcesUnchangedVerified':True,'writesRestrictedTo':str(OUT)}
 path.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'report':str(path),'sha256':sha(path),'topRowRawRGBSha256':m['topRowRawRGBSha256'],'ranges':10,'newDefects':0,'nativeModified':False,'upstreamModified':False}))
if __name__=='__main__':main()
