from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib,datetime
B=Path(__file__).parent;T=B.parent;S=T/'r05_c10';read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()};save=lambda p,v:Path(p).write_text(json.dumps(v,indent=2),encoding='utf8');assert not (B/'local-source-checkpoint.json').exists();cp=read(T/'source-checkpoint.json');bottom=next(s for s in cp['candidateSet'] if s['tile']=='r05_c10');empty=next(s for s in cp['candidateSet'] if s['tile']=='r04_c10');assert ref(bottom['file'])['sha256']==bottom['sha256'];assert bottom['sha256']=='c6419dfbffdfa5fdad7e8bdc69a6f670d024966d2de1521abefcab19087a76ff';assert ref(empty['file'])['sha256']==empty['sha256'];assert not np.any(np.array(Image.open(empty['file']).convert('RGBA'))[:,:,3]);H=Image.new('RGBA',(4096,115));parts=[]
for col in [1,2,3,4]:
 D=S/f'r01_c{col:02}-v1';q=read(D/'request.json');mp=D/q.get('selectedFinalDirectory','final-v1')/'manifest.json';m=read(mp);J=Image.open(m['joined']['file']).convert('RGBA');assert ref(m['joined']['file'])['sha256']==m['joined']['sha256']
 for p in m['patches']:
  if p['name'] in ['new-core','left-return','right-return']:
   l,_,r,_=p['cropFromJoinedLTRB'];dl,_,dr,_=p['destinationTileLTRB'];H.paste(J.crop((l,0,r,115)),(dl,0));parts.append({'source':m['joined'],'sourceLTRB':[l,0,r,115],'destinationLTRB':[dl,0,dr,115],'manifest':ref(mp)})
assert np.all(np.array(H)[:,:,3]==255);H.save(B/'r05-top-external-halo-native.png');save(B/'r05-top-external-halo-native.png.generation.json',{'operation':'Exact actual native top115 external halo from r05 top row in sequential return ownership','parts':parts,'output':ref(B/'r05-top-external-halo-native.png'),'worldLTRB':[36864,16269,40960,16384],'nativeScale':1,'actualModel':None,'actualQuality':None,'noUpscale':True,'formalAccepted':False});save(B/'source-root-checkpoint-input.json',cp);save(B/'local-source-checkpoint.json',{'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tile':'r04_c10','fragment':{'file':empty['file'],'sha256':empty['sha256']},'nativeScale':1,'coveragePixels':0,'coupledBottom':{**bottom,'tile':'r05_c10'},'bottomNativeHalo':ref(B/'r05-top-external-halo-native.png'),'manifest':None,'previousManifest':None,'formalAccepted':False,'rootPublished':False});master=Path(r'D:/work/image/tianyong_festival_hd_20260910/tianyong_city_master_6144.png');Image.open(master).crop((3456,1152,3840,1536)).save(B/'canonical-native384-layout-only.png');Image.open(S/'r01_c03-v1/final-v1/joined.png').crop((300,500,900,1100)).save(B/'nearby-native-material-swatch.png');save(B/'nearby-native-material-swatch.png.generation.json',{'operation':'Exact600x600 native nearby material crop','source':ref(S/'r01_c03-v1/final-v1/joined.png'),'sourceLTRB':[300,500,900,1100],'output':ref(B/'nearby-native-material-swatch.png'),'nativeScale':1,'actualModel':None,'actualQuality':None})
for name in ['grid-prepare.py','grid-finish.py','grid-ingest.py','grid-assemble.py','prepare-prompt.py']:
 s=(S/name).read_text().replace('r05_c10','r04_c10').replace('r06_c10','r05_c10').replace('r06-top-external','r05-top-external').replace('native r06 external','native r05 external').replace('r06 coverage','r05 coverage').replace('[36864,16384]','[36864,12288]')
 (B/name).write_text(s)
print(json.dumps({'south':bottom,'empty':empty,'halo':ref(B/'r05-top-external-halo-native.png')}))
