from pathlib import Path
import json,hashlib,sys
D=Path(sys.argv[1]);r=json.loads((D/"request.json").read_text(encoding="utf-8"));p=json.loads((D/"preparation.json").read_text(encoding="utf-8"))
base="Use case: precise-object-edit / outpainting. Produce one opaque native-detail 1254 by 1254 square at exactly the original crop, camera and scale.\nImage1 is the approved bright clean rounded Daoist Q fantasy STYLE reference. Image2 is adjacent native MAP material/detail scale reference only. Image3 is the exact same-world canonical LAYOUT GUIDE; its pixels are not final detail. LAST image4 is the only EDIT TARGET. Fill only its transparent black missing region. Preserve the visible original bottom and side areas as exact native boundary constraints: every contour, junction, endpoint, leaf shape, hue, light, stone-grid coordinate and object scale stays fixed. Do not move or recreate those areas from the guide. Never copy image2's composition.\nContinue architecture, vegetation, floor, curbs and cast shadows shown by image3 in their true footprints. Known native boundaries override the blurred guide's approximate stone joints. No removed plants or architecture; no new invented structures, posts, figures or decoration. Broad smooth clean bevels, ivory warm stone, rounded lush leaves and polished jade only where the canonical shows them. Quiet detailed handpainted surfaces; no cracks, thin triangular fractures, chipped stone, scratches, grunge, noisy polygon lines or dangling short tile seams. No new readable lettering, UI or watermark. No resizing, zoom, rotate, registration or geometric warp. Highest host finish."
prompt=base+"\n"+(D/"patch-description.txt").read_text(encoding="utf-8")
old=r["payload"]["referenced_image_paths"];refs=[old[2],old[3],old[1],old[0]]
r["payload"]={"prompt":prompt,"referenced_image_paths":refs,"transparent_background":False}
(D/"request.json").write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding="utf-8");(D/"prompt.txt").write_text(prompt,encoding="utf-8")
p["references"]=[{"file":f,"sha256":hashlib.sha256(Path(f).read_bytes()).hexdigest()} for f in refs];(D/"preparation.json").write_text(json.dumps(p,ensure_ascii=False,indent=2),encoding="utf-8")
print(json.dumps(r["payload"]))

