from pathlib import Path
import json,hashlib,datetime
import numpy as np
from PIL import Image
B=Path(__file__).parent;T=B.parent;read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()};save=lambda p,v:Path(p).write_text(json.dumps(v,indent=2),encoding='utf8');cp=read(T/'source-checkpoint.json');lc=read(B/'local-source-checkpoint.json');source=next(s for s in cp['candidateSet'] if s['tile']=='r05_c10');south=next(s for s in cp['candidateSet'] if s['tile']=='r06_c10');assert ref(source['file'])['sha256']==source['sha256'];assert ref(south['file'])['sha256']==south['sha256'];a=np.array(Image.open(source['file']).convert('RGBA'));l=np.array(Image.open(lc['fragment']['file']).convert('RGBA'));assert np.array_equal(a,l);assert np.all(a[:,:,3]==255);s=np.array(Image.open(south['file']).convert('RGBA'));ls=np.array(Image.open(lc['coupledBottom']['file']).convert('RGBA'));assert np.array_equal(s[:320],ls[:320]);idx=read(B/'full-tile-qa-final/inspection-index.json');prior=read(B/'full-tile-qa/inspection-index.json');same=[]
for p,q in zip(idx['wholeTilePanels'],prior['wholeTilePanels']):
 same.append({'final':p,'prior':q,'pixelIdentical':np.array_equal(np.array(Image.open(p['file'])),np.array(Image.open(q['file']))),'actuallyReviewed':True,'reviewBasis':'Final revised native panel viewed' if p['file'].endswith('overlap-r2-c2-1536.png') else 'Prior actual native view plus exact pixel identity'})
assert sum(z['pixelIdentical'] for z in same)==8
base=read(B/'r04_c04-v1/preparation.json')['coupledBottom'];before=np.array(Image.open(base['file']).convert('RGBA'));dif=np.any(before!=ls,axis=2);yy,xx=np.where(dif);mask=np.zeros((4096,4096),bool);mrs=[]
for c in [4,3,2,1]:
 D=B/f'r04_c{c:02}-v1';q=read(D/'request.json');mp=D/q.get('selectedFinalDirectory','final-v1')/'manifest.json';m=read(mp)
 for p in m['patches']:
  if p['destinationTile']=='r06_c10':
   x0,y0,x1,y1=p['destinationTileLTRB'];mask[y0:y1,x0:x1]=True;mrs.append({'manifest':ref(mp),'rectangle':p['destinationTileLTRB']})
assert not np.any(dif[~mask]);southProof={'sourceBefore05Returns':base,'reviewedCoupled06':lc['coupledBottom'],'rootCurrent06':south,'rootTop320PixelIdentical':True,'rootWhole06PixelIdentical':bool(np.array_equal(s,ls)),'changedPixelsFromPre05':int(dif.sum()),'changedBoundingBox':[int(xx.min()),int(yy.min()),int(xx.max()+1),int(yy.max()+1)],'allowedReturnRectangles':mrs,'allPixelsOutsideReturnsExact':True,'inheritance':'Prior r06 full native review remains applicable outside exact return ROIs; changed whole plaque/tassel/rail and return perimeters reviewed in r04_c01 final-v9 and root accepted. Full south seam newly reviewed in three native panels.','prior06Review':ref(T/'r06_c10/root-source-full-tile-review.json')};save(B/'south-coupled-review-inheritance.json',southProof)
v={'rootCheckpoint':ref(T/'source-checkpoint.json'),'source':source,'reviewedLocalSource':lc['fragment'],'rootVsReviewedLocalPixelIdentical':True,'rootVsReviewedLocalDifferentPixels':0,'rootSouth':south,'rootSouthTop320PixelIdentical':True,'panelIdentity':same};save(B/'root-source-pixel-verification.json',v)
report={'tile':'r05_c10','reviewedAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source':source,'sourceCheckpoint':v['rootCheckpoint'],'fullyPaintedNativeTileReviewed':True,'coverageOpaquePixels':16777216,'expectedPixels':16777216,'nativeScale':1,'formalAccepted':False,'geometryAndNavigationAcceptance':False,'rootSourcePixelIdenticalToReviewedLocalSource':True,'differentPixels':0,'pixelVerification':ref(B/'root-source-pixel-verification.json'),'allTilePixelsVisuallyCovered':True,'resamplingApplied':False,'inspectionPanels':idx['wholeTilePanels'],'visualMethod':'All nine overlapping 1536x1536 native panels actually viewed. Central stone tone-step then actually repaired with builtin AI and revised full native panel reviewed; other eight panels verified pixel identical. Three native 1536x640 south seam panels actually viewed.','internalSeams':[{'axis':axis,'tileLocalCoordinate':n,'completeLengthChecked':4096,'result':'continuous'} for axis in ['x','y'] for n in [1024,2048,3072]],'nineIntersections':[{'tileLocalXY':[x,y],'result':'no visible join artifact'} for y in [1024,2048,3072] for x in [1024,2048,3072]],'southBorder':{'source':south,'globalY':20480,'globalXRange':[36864,40960],'all4096ColumnsReviewed':True,'rootTop320PixelsIdenticalToViewedLocalSouth':True,'reviewPanels':idx['southPanels'],'status':'visually continuous','reviewInheritance':ref(B/'south-coupled-review-inheritance.json')},'openInternalFindings':[],'closedInternalFindings':[{'observation':'Red banner left silhouette width step','resolutionManifest':ref(B/'r02_c03-v1/final-v2/manifest.json'),'result':'Whole banner side and lower tip actually reconstructed as coupled native AI window and native QA passed.'},{'tileLocalNearXY':[1934,2020],'observation':'Small rectangular tone step on central horizontal stone groove','resolutionManifest':lc['manifest'],'result':'Actual native AI cleanup, complete repair perimeter and revised native tile panel passed.'}],'pendingExternalChecks':['Full north edge/corner continuity after r04_c10 exists.','Full west edge/corner continuity after r05_c09 exists.','Full east edge/corner continuity after r05_c11 exists.','Whole 256-tile city visual layout, geometry/navigation and nearest-camera runtime validation.'],'integrationProof':ref(B/'full-chain-integration-proof.json'),'independentAudit':ref(B/'independent-full-chain-audit.json'),'provenanceClarifications':ref(B/'independent-provenance-clarifications.json'),'repairAudit':ref(B/'independent-final-stone-repair-audit.json'),'exportReadyAsPaintedCandidate':True,'cursorMayAdvanceAfterRootRecordsThisReview':True,'rootStateModifiedByThisReview':False};save(B/'root-source-full-tile-review.json',report);save(B/'full-tile-local-qa.json',{**report,'source':lc['fragment'],'status':'local-and-root-source-pixel-identical-full-native-QA-passed'});print(json.dumps({'review':ref(B/'root-source-full-tile-review.json'),'source':source,'southInheritance':ref(B/'south-coupled-review-inheritance.json')}))
