from pathlib import Path
import json, hashlib
from datetime import datetime, timezone

ROOT=Path(__file__).resolve().parents[4]
REC=ROOT/'qdao_original_roster_v14_hd/recovery-20260921'
identity=REC/'10-work/references/identity-inspection-1024.png'
style=ROOT/'designs/jubaozhai-ui/02-characters.png'
common='''Use case: identity-preserve. Produce ONE complete 10_crimson_spear_girl game walk sprite, native single-frame at least 1024x1024, actual transparent RGBA background. This is a targeted animation continuity repair, preserve detailed finished Daoist chibi painting. Image1 is the authoritative identity; keep brown double buns, long twin tails, red ribbons, gold/turquoise hair ornaments, red/white/gold ornate short costume and boots, long straight dark-shaft crimson/gold spear with tassels. Image2 is the MAIN confirmed style reference: clean bright rounded high-definition Daoist chibi hand-painted rendering; use its materials/finish, never its UI. Image3 is the SAME DIRECTION master for camera, whole-body size, head diameter, upper-body height and all equipment. Image4 is the faulty target frame whose walk phase should be retained while repairing its upper-body continuity. Do NOT shrink or enlarge the subject or head. Do NOT copy the master leg pose: this must be a newly drawn distinct preceding pre-contact phase with actual leg articulation. The top of head, neck, shoulders, waist and spear grip should lie at almost exactly the image3 heights measured relative to the ground/support boot, maximum a tiny natural 3px bob on a 1024 scale. Entire spear tip/butt, hair, ribbons and boots within square with margins. At least one boot contacts ground; no airborne jump, large black sole toward camera, crossed legs, extra limb, bent shaft, equipment redesign, shadows, colored matte, checkerboard, letters or UI. True transparent alpha with clean fine edges and no colored fringe. '''
specs={
 'N16-v2':('N16', 'N01-v1','N16-v1', '''Facing N straight away, exact rear view: no eyes or face. Anatomical left is screen left. The spear blade projects upper-left and butt lower-right. Keep the N01 master head/buns and neck HEIGHT, do not lower the head as in the faulty target. Walk phase16: screen-left anatomical LEFT leg is forward into the distance, left heel just 2px above coming heel contact, knee almost extended. Screen-right anatomical RIGHT trailing forefoot supports the weight, heel lifted modestly. This is the final anticipatory moment immediately before image3 contact01. Right supporting boot remains behind/toward viewer, but only a modest heel rise, not exposing a huge sole. Left hand remains higher on the shaft near blade, right hand lower near waist; no hand swap. Preserve image3 back costume embroidery and head shape; allow only subtle natural cloth/hair phase difference.'''),
 'S16-v2':('S16', 'S15-v1','S16-v1', '''Facing S straight toward viewer, exact front view. Anatomical LEFT leg is screen RIGHT. Spear blade upper-right, butt lower-left; character left hand grips higher nearer blade at chest, right hand lower near waist. Match image3 face size and eye line, chin, shoulders and waist HEIGHT; faulty image4 upper body sits too low and must be raised to match image3 while the ground height stays unchanged. Phase16: screen-right anatomical LEFT leg has swung forward toward viewer, knee nearly straight, heel descending to within 2px of its coming heel contact. Screen-left anatomical RIGHT trailing forefoot supports weight, heel slightly lifted. A gentle grounded short step, a distinct natural pose just after image3 phase15 and just before phase01. Preserve the same calm small closed smile, amber eyes, forehead jewel, costume panels, boots and weapon without redesign. Hair, ribbon and tassel shift subtly only.''')
}
for attempt,(slot,master,target,detail) in specs.items():
 d=REC/'10-generation'/attempt
 if d.exists(): raise RuntimeError('Refusing existing '+attempt)
 d.mkdir()
 refs=[identity,style,REC/'10-generation'/master/'raw.png',REC/'10-generation'/target/'raw.png']
 roles=['authoritative-character-identity','confirmed-main-style','same-direction-upper-body-continuity-master','faulty-target-pose-and-edit-reference']
 prompt=common+detail
 request={'status':'prepared_for_submission','character':'10_crimson_spear_girl','slot':slot,'startedAt':datetime.now(timezone.utc).isoformat(),'tool':'image_gen__imagegen','actual_request':{'prompt':prompt,'referenced_image_paths':[p.as_posix() for p in refs]},'submittedParameters':{'model':None,'quality':None},'configSnapshot':json.loads((ROOT/'config/image-generation.json').read_text(encoding='utf-8-sig')),'referenceRoles':roles,'reference_bindings_at_start':[{'path':p.as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'purpose':role} for p,role in zip(refs,roles)]}
 (d/'prompt.txt').write_text(prompt,encoding='utf-8',newline='')
 (d/'request.json').write_text(json.dumps(request,ensure_ascii=False,indent=2),encoding='utf-8')
 print(attempt)
