"""Prepare independent NE frame requests; never synthesizes image content."""
from pathlib import Path
import argparse, json, subprocess, sys
from root_prompts import PHASES
HERE=Path(__file__).resolve().parent
GEN=HERE.parent/'17-generation'
ROOT=HERE.parents[2]
BASE='Use case: stylized-concept. Draw ONE completely new genuine articulated walking frame of the exact 灵篆书生 calligrapher boy. Image 1 is the approved NE idle and defines exact rear-three-quarter camera, identity, scale and equipment. Image 2 is the original identity portrait. The last image is the approved primary polished Q-Daoist hand-painted style reference only. Keep huge round head, short compact body and limbs, brown tousled topknot, teal trailing ribbon, charcoal warm-black robe with ornate gold cloud trim, white inner robe, teal lining and sash, short black-gold boots. Anatomical RIGHT hand on near/image-right side holds the identical giant black/jade/gold brush with ivory bristles down. Anatomical LEFT hand on far/image-left holds the blank pale scroll with black-gold rollers and exactly two pale-blue ghost companions. Never swap hands. Head badge and belt medallion are on FRONT, hidden from rear. Fixed NORTHEAST direction: 45 degrees between due north away and due east image-right. We see the back of head and robe and his right side, only tiny right ear/cheek sliver, never a front eye. Both toes point upper-right. Fixed mild top-down orthographic camera, no camera zoom or turn. Match image1 hair-to-boot height, head size and boot size. Complete figure centered with hair at y7%, lowest support sole at y94%, all brush, scroll, ribbons and spirits inside safe margins. Native square single image at least1024x1024. '
END=' In this NE rear-three-quarter view, FORWARD means away toward upper-right and BACK means toward lower-left. The anatomical RIGHT leg is nearer/image-right and the LEFT leg is farther/image-left; never exchange them. Show two distinct feet below parted robe hem. This is restrained ordinary walking, not running, marching, kicking or jumping; at least one support sole/toe touches ground. Keep props steady with subtle small natural cloth and ribbon response. Transparent PNG genuine alpha, no floor, cast shadow, colored fringe, checkerboard, text, labels, grid or multiple poses. Draw new articulated anatomy; never copy, mirror, interpolate, warp or translate a previous pose.'
def main():
 p=argparse.ArgumentParser();p.add_argument('--frame',type=int,required=True);p.add_argument('--attempt',type=int,default=1);a=p.parse_args()
 n=a.frame;assert 1<=n<=16
 folder=GEN/f'walk-NE-{n:02d}-v{a.attempt}';folder.mkdir(exist_ok=False)
 visual=''
 if n in (9,10,11,12,13):
  visual=' Critical unambiguous SCREEN-SPACE arrangement: the TRAILING or airborne boot is on the RIGHT HALF OF THE IMAGE, below the brush hand at x62%, with its heel raised and dark sole facing viewer at y93%. The FORWARD PLANTED boot is on the LEFT HALF OF THE IMAGE below the scroll hand at x44%, smaller in depth at y87%, with gold heel but NO visible dark sole. Keep the legs separate and traceable. Exactly the image-RIGHT boot shows its dark underside; the image-LEFT boot does not. This reverses the leg phase of early frames while leaving all upper-body equipment unchanged.'
 if n in (6,7,8):
  visual=' Critical new leg configuration in SCREEN SPACE: image-LEFT leg swings FORWARD toward upper-right, away from the viewer; its boot has no broad underside visible and its toe is reaching diagonally upward/right, with ankle at x46% and sole near y88%. Image-RIGHT leg is now the rear SUPPORT, heel lifted and only toe planted near x60%, y94%; show a little right heel/underside. This must differ from the early frames where image-left boot was behind. Knees do not cross.'
 if n in (14,15,16):
  visual=' Critical new leg configuration in SCREEN SPACE: image-RIGHT leg swings FORWARD toward upper-right, away from the viewer; its boot has no broad underside visible and its toe is reaching diagonally upward/right, with ankle at x62% and sole near y88%. Image-LEFT leg is now the rear SUPPORT, heel lifted and only toe planted near x44%, y94%; show a little left heel/underside. This must differ from mid-cycle frames where image-right boot was behind. Knees do not cross.'
 prompt=BASE+f' WALK NE FRAME {n:02d}/16, cycle phase {n-1}/16. REQUIRED LEG ACTION: '+PHASES[n]+END+visual+'\n'
 if n==6 and a.attempt>1:
  prompt='Use case: identity-preserve. Draw ONE native square 1254x1254 genuine transparent standalone game walk frame. Reference1 is NE walk07, the pose AFTER the requested frame. Reference2 is original identity; Reference3 is the approved primary hand-painted style sample. Preserve the exact same boy, direction, camera, scale, head, costume, right-hand brush, left-hand scroll and TWO cyan spirits. Draw walk NE06: the moment just BEFORE reference1. Keep its leg ordering: SCREEN-LEFT boot farther away/up with gold heel and no broad outsole; SCREEN-RIGHT boot closer/down touching ground with toe, heel only slightly raised. Relative to reference1, move left thigh slightly back by bending the left knee so the left boot passes closer alongside the planted right ankle, still clear and separate. Right sole is mostly flat as heel only begins to rise. New organic anatomy and cloth folds, small restrained step, not jump or run. Do not swap legs or hands. Same NE rear three-quarter view with right ear sliver and no front eye. Keep all extremities inside canvas, top hair7%, lowest grounded boot94%. No shadow/floor, labels, grid, frame number, mirroring, duplicated pose, interpolation or artificial warp. A newly articulated independent frame with authentic alpha transparency.\n'
 (folder/'prompt.txt').write_text(prompt,encoding='utf8',newline='')
 refs=[GEN/'idle-NE-v1/raw.png',GEN/'references/identity-view-1024.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
 if n==6 and a.attempt>1:refs[0]=GEN/'walk-NE-07-v1/raw.png'
 cmd=[sys.executable,'-B',str(HERE/'prepare_request.py'),'--archive',str(folder),'--prompt',str(folder/'prompt.txt'),'--kind','walk','--direction','NE','--frame',str(n)]
 for ref in refs:cmd+=['--reference',str(ref)]
 subprocess.run(cmd,check=True,capture_output=True,text=True)
 print(json.dumps(json.loads((folder/'request.json').read_text(encoding='utf8')),ensure_ascii=True))
if __name__=='__main__':main()
