import pathlib,json,hashlib,datetime,sys
sys.stdout.reconfigure(encoding='utf-8')
root=pathlib.Path(__file__).resolve().parent
data=json.loads((root/'snapshot.json').read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
notes={
'00_reference_topright_boy':{'definitePoseFailures':[],'followups':[],'observedLimits':['dynamic grounding and loop continuity unverified']},
'01_ice_sword_girl':{'definitePoseFailures':[],'followups':[{'action':'run','direction':'NE','frames':[3,4,5],'issue':'large sword-arm/chest transition; verify normal-speed continuity'},{'action':'run','direction':'E','frames':[2,3,4],'issue':'large sword direction and shoulder transition; verify normal-speed continuity'},{'action':'run','direction':'SW','frames':[4,5],'issue':'large sword-arm/body yaw transition; verify continuity'}],'observedLimits':['identity portrait confirms left blue talisman; source TASK wording is incomplete','full-size S04/05/06 confirms continued support, raised other foot sole is not outward roll']},
'02_fire_talisman_boy':{'definitePoseFailures':[],'followups':[{'action':'run','direction':'E','frames':[3,4],'issue':'fan/bell front and rear extrema transition rapidly'},{'action':'cast','direction':'E','frames':[3,4],'issue':'bell hand passes from rear of body to front chest with large difference'}],'observedLimits':['full-size run E04/NE07/NW07 feet remain explainable in movement plane','no confirmed horizontal foot splay from viewed export pixels']},
'03_lotus_healer_girl':{'definitePoseFailures':[{'action':'run','direction':'N','frames':[2,3,4],'issue':'N03 isolated lantern dip to hip followed by N04 rise to chest; visible adjacent-pose discontinuity','recommendation':'stabilize lantern and elbow/wrist transition, prioritizing N03; preserve identity and correctly oriented feet'}],'followups':[{'action':'run','direction':'SE','frames':[10,11,12],'issue':'lantern moves from in front to lower waist to back of shoulder; check discontinuity'},{'action':'run','direction':'W','frames':[3,4],'issue':'bottle and lantern switch front/rear extrema abruptly'}],'observedLimits':['skirts obscure proximal hip/leg ownership in diagonal views','full-size NW07/NW12/S12 reveal heel/toe arrangement; cannot infer horizontal outward roll from sole visibility alone']},
'04_mountain_guardian_boy':{'definitePoseFailures':[{'action':'run','direction':'W','frames':[3,4,10,11],'issue':'torso front/back orientation and shield near/far appearance change suddenly, making a turn within same run direction','recommendation':'stabilize shoulder/torso plane and left shield attachment while preserving anatomical right staff'}],'followups':[{'action':'run','direction':'NW','frames':[3,4,5],'issue':'staff hand rises abruptly from waist to shoulder/high above shoulder'}],'observedLimits':['full-size NW07/NW15 can read as toe-off with raised heel; sole exposure alone is not outward twist evidence','21 SHA mismatches at source snapshot; actual export SHA was used for sheets']}}
report={'reviewedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'snapshot':'snapshot.json','criteria':'current user instruction: same hip-knee-ankle-toe movement plane; natural bending and toe-off preserved; support relative-position pairs are independent poses; 16x75ms run','visualScope':'35 actual current-export contact sheets plus selected full-size current PNGs; no live dynamic or client verification','characters':{}}
for cid,c in data['characters'].items():
 changed=[]
 for f in c['frames']:
  p=pathlib.Path(f['path']);current=sha(p) if p.exists() else None
  if current!=f['sha256']:changed.append({'path':f['path'],'action':f['action'],'direction':f['direction'],'frame':f['frame'],'reviewedSha256':f['sha256'],'currentSha256':current})
 report['characters'][cid]={**notes[cid],'viewedGroups':list(c['groupCounts']),'viewedGroupCount':len(c['groupCounts']),'viewedFrameCount':len(c['frames']),'sourceManifest':c['manifest'],'sourceManifestSha256AtSnapshot':c['manifestSha256'],'manifestChangedDuringReview':sha(c['manifest'])!=c['manifestSha256'],'pngChangedDuringReview':changed,'snapshotMissingCount':len(c['missing']),'snapshotManifestMismatchCount':len(c['mismatches']),'unviewedExistingGroups':[],'artStatus':'independent_static_screening_not_final_approval'}
report['totalViewedGroups']=sum(c['viewedGroupCount'] for c in report['characters'].values())
report['totalViewedFrames']=sum(c['viewedFrameCount'] for c in report['characters'].values())
(root/'audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({cid:{'groups':c['viewedGroupCount'],'frames':c['viewedFrameCount'],'pngChanged':len(c['pngChangedDuringReview']),'manifestChanged':c['manifestChangedDuringReview']} for cid,c in report['characters'].items()},ensure_ascii=False))
