from pathlib import Path
import json,hashlib,datetime
from PIL import Image
import numpy as np
D=Path(__file__).parent;F=D/'final-v1';ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()};read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));save=lambda p,o:Path(p).write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf8')
prep=read(D/'preparation.json');J=Image.open(F/'joined.png').convert('RGB');prior=prep['sourceTile']
a=read(F/'assembly.json');a['repairMaskBottomExtensionLTRB']=[0,1100,700,1254];save(F/'assembly.json',a)
save(F/'visual-review.json',{'reviewedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'image':ref(F/'joined.png'),'reviewMethod':'Whole native1254 square, complete left and bottom returns, and bottom-left junction inspected at original size.','inspectedImages':[ref(p) for p in (F/'qa').glob('*.png')],'localVisualAccepted':True,'formalAccepted':False,'wholeTileAccepted':False,'findings':['New native slabs match existing left and lower material, perspective and edge endpoints.','An inherited lower cross joint would dead-end inside the left slab. AI repair-v1 moved its bottom endpoint about50px and was rejected. AI repair-v2 connects it into a T-junction while preserving its actual lower endpoint.','Repair-v2 transparent wedge has zeroed RGB as well as alpha so the missing region is unambiguous to the host input channel.','The complete bottom-left return now has one continuous narrow joint, not a fade or a floating end.','No geometric registration, blur, resizing or tone adjustment was applied.','New core plus full230px left return and176px bottom return must be applied together. Existing pixels beyond left edge and lower return are preserved exactly.'],'actualModel':None,'actualQuality':None})
patches=[]
for name,crop,dest,src in [('new-core',[230,0,1254,1024],[1139,1933,2163,2957],None),('left-return',[0,0,230,1024],[909,1933,1139,2957],prior),('bottom-return',[0,1024,1254,1200],[909,2957,2163,3133],prior)]:
 p=F/(name+'.png');J.crop(crop).save(p);patches.append({'name':name,'asset':ref(p),'cropFromJoinedLTRB':crop,'destinationTile':'r07_c10','destinationTileLTRB':dest,'requiredPriorSource':src,'nativeScale':1,'mustApplyTogether':True})
m={'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'appearance':'tianyong_festival','tile':'r07_c10','tileGlobalOrigin':[36864,24576],'nativeScale':1,'windowTileLocalLTRB':[909,1933,2163,3187],'windowGlobalLTRB':[37773,26509,39027,27763],'joined':ref(F/'joined.png'),'visualReview':ref(F/'visual-review.json'),'assembly':ref(F/'assembly.json'),'localVisualAccepted':True,'formalAccepted':False,'patches':patches,'sourceCheckpoint':prep['savedCheckpoint'],'requiresPriorManifest':prep['requiresPriorManifest'],'note':'Root review and ROI validation before publication. Left and bottom source modifications resolve the previous paving-joint dead end and must travel together.'};save(F/'manifest.json',m)
save(F/'joined.png.generation.json',{'operation':'native AI outpaint and targeted AI joint completion, source-preserving composite','sources':[ref(D/'native.png'),ref(D/'repair-v2/native.png'),ref(D/'context.png')],'assembly':ref(F/'assembly.json'),'output':ref(F/'joined.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'noUpscale':True,'formalAccepted':False})
fragment=Image.open(prior['file']).convert('RGBA');fragment.paste(J.crop((0,0,1254,1200)).convert('RGBA'),(909,1933));fragment.save(F/'r07_c10-fragment.png');coverage=int(np.count_nonzero(np.array(fragment)[:,:,3]==255));assert coverage==6880256
save(F/'r07_c10-fragment.png.generation.json',{'operation':'1:1 native patch composition','sources':[prior,ref(F/'joined.png')],'manifest':ref(F/'manifest.json'),'output':ref(F/'r07_c10-fragment.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'coveragePixels':coverage,'noUpscale':True,'formalAccepted':False})
save(D.parent/'local-source-checkpoint.json',{'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tile':'r07_c10','fragment':ref(F/'r07_c10-fragment.png'),'nativeScale':1,'coveragePixels':coverage,'formalAccepted':False,'rootPublished':False,'manifest':ref(F/'manifest.json'),'previousManifest':prep['requiresPriorManifest'],'contextJoined':ref(F/'joined.png'),'bottomReturn':patches[2]})
print(json.dumps({'manifest':ref(F/'manifest.json'),'joined':ref(F/'joined.png'),'localCoveragePixels':coverage}))
