"""Native joint edits constrained to c16; c15 is immutable source context."""
from pathlib import Path
from PIL import Image
import sys,json,hashlib,shutil
from datetime import datetime,timezone
R=Path(__file__).resolve().parent;T=R/'r07_c16';D=T/'repairs/west-only-joint';W=R/'r07_c15/output/r07_c15.png';E=T/'repairs/integrated-south-v2/candidate.png';STYLE=R.parents[3]/'designs/gameplay-ui/04-guild.png'
WSHA=None;ESHA='3f5be4ea2f6cb9e54121761646fc0b0c218af12738fa7493c198a1f4b9944bc2';STARTS=[0,1024,1982,2960]
SW=R/'r08_c15/output/r08_c15.png';SO=R/'r08_c16/output/r08_c16.png'
SWSHA='70ce623a54fb8419b951b7372a88e95db2c8b5ae9e04845c2af2c1fd18312585';SOSHA='3e4a1a64a96d894531f6f1f7189287276b401e58f6805a9e6242c422e22b96de'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
load=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'))
def js(p,v):p.parent.mkdir(parents=True,exist_ok=True);tmp=Path(str(p)+'.writing');tmp.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');tmp.replace(p)
def prepare(i):
 global WSHA,W
 f=D/'final-source' if i==4 and '--final-source' in sys.argv else D
 binding=load(D/'source-bindings.json');assert binding['westStatus'] in ('stable-reviewed-source','review-candidate-pending-final-roi-validation');WSHA=binding['westSha256'];W=Path(binding['westFile'])
 assert sha(W)==WSHA and sha(E)==ESHA;D.mkdir(parents=True,exist_ok=True);f.mkdir(parents=True,exist_ok=True);start=STARTS[i-1]
 if i==4:
  full_ready=binding['westStatus']=='stable-reviewed-source' and binding['formalWestBound'] is True
  roi_ready=binding['westStatus']=='review-candidate-pending-final-roi-validation' and binding.get('s4WestROIReviewedAndFrozen') is True and binding.get('s4WestApprovedRectXYXY')==[3469,2960,4096,4096]
  assert full_ready or roi_ready,'Last joint requires stable whole source or explicitly reviewed frozen source ROI.'
  assert sha(SW)==SWSHA and sha(SO)==SOSHA
 pair=Image.new('RGB',(8192,max(4096,start+1254)));pair.paste(Image.open(W),(0,0));pair.paste(Image.open(E),(4096,0))
 if i==4:
  pair.paste(Image.open(SW).crop((0,0,4096,118)),(0,4096));pair.paste(Image.open(SO).crop((0,0,4096,118)),(4096,4096))
  for prior_i in [1,2,3]:
   prior=load(D/f's{prior_i}-input.png.generation.json')
   assert hashlib.sha256(pair.crop(prior['sourceRectInPairXYXY']).tobytes()).hexdigest()==prior['rawSourceRGBSha256'],'Earlier native joint source changed; cannot append s4 blindly.'
 box=[3469,start,4723,start+1254];baseline=pair.crop(box);raw=hashlib.sha256(baseline.tobytes()).hexdigest();guide=baseline.copy()
 sources=[{'file':str(W),'sha256':WSHA,'role':'immutable c15 left half, exact neighbor geometry and material'},{'file':str(E),'sha256':ESHA,'role':'frozen c16 right half that may be corrected'}]
 if i==4:sources.extend([{'file':str(SW),'sha256':SWSHA,'role':'immutable actual lower-left r08c15 context, bottom118 rows'},{'file':str(SO),'sha256':SOSHA,'role':'immutable actual lower-right r08c16 context, bottom118 rows'}])
 if i>1:
  prev=D/f's{i-1}.png';assert prev.exists();overlap=STARTS[i-2]+1254-start;guide.paste(Image.open(prev).crop((627,1254-overlap,1254,1254)),(627,0));sources.append({'file':str(prev),'sha256':sha(prev),'role':f'previous repaired c16-side upper {overlap}px overlap; c15 half remains exact current c15 pixels'})
 p=f/f's{i}-input.png';assert not p.exists();guide.save(p)
 js(Path(str(p)+'.generation.json'),{'file':str(p),'sha256':sha(p),'sourceRectInPairXYXY':box,'rawSourceRGBSha256':raw,'derivedFrom':sources,'immutableLeftColumns':[0,627],'immutableBottomRows':[1136,1254] if i==4 else None,'finalAllowedC16RectXYXY':[0,start,627,min(4096,start+1254)],'resized':False,'westSourceStatus':binding['westStatus'],'formalWestBound':binding['formalWestBound'],'finalIntegrationRequiresExactWest627RawROIIdentity':True,'operation':'exact 1254 native joint crop; previous native overlap on c16 half only; fourth crop has actual immutable lower118 context'})
 prompt='Use case: precise-object-edit. IMAGE 1 is an exact native joint crop of adjacent fishing-village map tiles. The vertical line at x=627 is an artificial image stitch. The LEFT HALF, x0 through626, is FINISHED IMMUTABLE ART. Copy it exactly; do not alter its geometry, colors, objects or shadows. Repair the RIGHT HALF ONLY so every shape that reaches the left half boundary continues into the right half at its EXACT existing endpoint, angle, thickness and material. The right half currently has misaligned timber rails/diagonal boat board contours and mismatched blue canopy/water fields. The left half is the authority; adapt the right half smoothly to meet it while retaining the unchanged rightmost150 pixels of composition. Reconnect the original shapes, do not add new parts or a divider. Any top overlap in the right half is previously repaired context; continue it naturally. Preserve the rounded wood posts, rope winding, blue-painted hull, brown plank divisions, lantern and narrow blue waterline where present. Keep the same camera, object scale, positions and overall layout. Water must remain calm with broad soft blue/cyan fields; continue the existing broad reflections from the immutable left, do not simplify them into a blank cut or add fine ripples, foam, white glare or netlike caustics. Preserve original lights/shadows and material character; do not globally recolor or relight. IMAGE 2 is primary confirmed bright clean rounded Q-style material rendering quality only; no UI. No new decoration, nails, grain, cracks, characters, text, border, crop, blur, upscaling or artificial sharpening. Return one opaque native1254x1254 corrected IMAGE 1 at highest available finish. Only the right half is editable; exact left-side contour endpoints take precedence over erroneous right-side guide geometry.'
 prompt='Precise local joint repair of IMAGE 1, an original1254 square crop. The vertical line at local x627 is an artificial tile boundary. LEFT x0..626 is immutable finished neighbor art: preserve every pixel, contour, material and shadow. Repair only RIGHT x627..1253 to continue the original timber rails, rounded wooden posts, existing wrapped gold ropes and broad cyan-water reflections from the exact visible left-side endpoints. Keep their existing angles, width and placement. Gently adapt the incorrect right-side endpoint over nearby distance; keep the rightmost150 pixels unchanged so the correction returns to the original composition. Reconnect the SAME existing objects; never invent a post, extra beam, rope, fitting or outline. Any upper-right overlap is previously repaired native context and must be continued naturally. Maintain quiet low-contrast water with broad soft fields. Preserve broad existing reflections that actually cross the boundary, without inventing fine ripples, gridlike caustics, foam, new white lines or noise. Keep original lighting and the same camera. IMAGE2 is the confirmed bright clean rounded Q-style material and finish reference only; no UI. No crop, resize, registration, blur, global recolor, sharpening, text, icons or decoration. Return one opaque native1254x1254 corrected target. Exact immutable LEFT geometry takes precedence over incorrect right-side guide geometry.'
 if i==4:prompt+=' IMPORTANT FOUR-TILE CORNER: the entire bottom118 rows, local y1136..1253, are ACTUAL finished lower tiles and are also immutable. Correct only the UPPER RIGHT rectangle x627..1253,y0..1135. The horizontal line y1136 and vertical line x627 must disappear through natural continuation of the SAME existing objects and colors. Preserve the finished bottom reference exactly. Match upper-right contours into both immutable left and immutable lower references, including rounded wood surfaces, any gold wrapping and cyan water. No new object, extra curve, joint, divider or invented rope. Keep each wooden beam straight along its existing axis; no S-curve or kink. Top276 right-side rows are previous corrected native context. Preserve the rightmost150 pixels and all immutable context.'
 (f/f's{i}.txt').write_text(prompt,encoding='utf-8');refs=[{'file':str(p),'sha256':sha(p),'role':'native edit target; left627 columns immutable, connect geometry and materials only on right627 columns; fourth crop bottom118 also immutable'},{'file':str(STYLE),'sha256':sha(STYLE),'role':'primary confirmed rounded Q-style rendering/material reference only'}];js(f/f's{i}.references.json',refs);print(json.dumps({'prompt':prompt,'references':[x['file'] for x in refs]}))
def record(i,src):
 f=D/'final-source' if i==4 and '--final-source' in sys.argv else D
 src=Path(src);out=f/f's{i}.png';assert not out.exists()
 with Image.open(src) as im:assert im.size==(1254,1254)
 shutil.copyfile(src,out);refs=load(f/f's{i}.references.json')
 js(Path(str(out)+'.generation.json'),{'file':str(out),'sha256':sha(out),'width':1254,'height':1254,'format':'PNG','generatedAt':datetime.now(timezone.utc).isoformat(),'tool':'image_gen.imagegen','route':'builtin','configSnapshot':load(R.parents[3]/'config/image-generation.json'),'submittedParameters':{'model':None,'quality':None,'transparent_background':False,'referenced_image_paths':[x['file'] for x in refs]},'actualModel':None,'actualQuality':None,'unverifiedReason':'Host managed built-in path exposes no selector or returned model/quality metadata.','evidence':{'toolResultSourcePath':str(src),'toolResultSha256':sha(src)},'prompt':str(f/f's{i}.txt'),'promptSha256':sha(f/f's{i}.txt'),'references':refs,'resizedAfterGeneration':False,'finalArtUpscaled':False,'finalAllowedC16RectXYXY':[0,STARTS[i-1],627,min(4096,STARTS[i-1]+1254)],'c15UnchangedRequired':True,'r08UnchangedRequired':True,'formalAccepted':False});print(json.dumps({'file':str(out),'sha256':sha(out)}))
if __name__=='__main__':
 if sys.argv[1]=='prepare':prepare(int(sys.argv[2]))
 elif sys.argv[1]=='record':record(int(sys.argv[2]),sys.argv[3])
