"""Prepare the next adjacent tile only; images are generated by the built-in tool."""
from pathlib import Path
from PIL import Image
import json,hashlib
R=Path(__file__).resolve().parent
P=R.parents[3];T=R/'r08_c12'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
for d in ['guides','prompts','native','output','qa']:(T/d).mkdir(parents=True,exist_ok=True)
source=P/'qdao_city_tiles_4k_20260916/builtin_q64_all_city_references/donghai_day/map-native-layout-reference.png'
west=R/'r08_c11/output/r08_c11.png';style=P/'designs/gameplay-ui/04-guild.png'
im=Image.open(source);box=[v*im.width/65536 for v in (44941,28557,49267,32883)]
path=T/'guides/local-layout.png';im.transform((1254,1254),Image.Transform.EXTENT,box,Image.Resampling.BICUBIC).save(path)
data={'tile':'r08_c12','globalRect':[45056,28672,4096,4096],'worldRect':{'x':256.25,'z':150,'width':18.75,'height':18.75},'layoutSource':str(source),'layoutSourceSha256':sha(source),'layoutSourceBox':box,'westNeighbor':str(west),'westNeighborSha256':sha(west),'westNeighborRole':'actual current pixel reference; west-side common-edge repair elsewhere in this neighbor does not alter its east-side context','sourceGuide':str(path),'guideSha256':sha(path),'status':'reference_prepared_native_generation_pending','referenceEnlargementOnly':True,'finalArtUpscaled':False,'formalAccepted':False,'nativeGrid':[4,4],'core':1024,'halo':115}
(T/'plan.json').write_text(json.dumps(data,indent=2),encoding='utf-8')
(Path(str(path)+'.generation.json')).write_text(json.dumps({'file':str(path),'sha256':sha(path),'derivedFrom':[{'file':str(source),'sha256':sha(source)}],'operation':'reference-only enlarged layout crop','sourceBox':box,'allowedInFinal':False},indent=2),encoding='utf-8')
print(json.dumps(data))
