from pathlib import Path
from datetime import datetime,timezone
from PIL import Image
import sys,json,shutil,hashlib
R=Path(__file__).resolve().parent;D=R/'r08_c16/repairs/west-only-joint';S=D/'s2.png';P=D/'s2-refine-input.png';STYLE=R.parents[3]/'designs/gameplay-ui/04-guild.png'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
load=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'))
def js(p,v):temp=Path(str(p)+'.writing');temp.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');temp.replace(p)
if sys.argv[1]=='prepare':
 assert sha(S)=='79e8470e291b764e7822402362b56a8e3323edd16e5e3e5fdb03fa5cc3048bd4';shutil.copyfile(S,P);shutil.copyfile(Path(str(S)+'.generation.json'),D/'s2-first-generation.json')
 prompt='Precisely correct ONE remaining geometric defect in IMAGE 1. This is the same fishing-boat rail crop. At the vertical image seam x627, the prominent golden DIAGONAL RAIL rising toward the right has a 36-pixel stair step: its right-hand continuation is too high. Keep ALL LEFT-HALF pixels x0..626 exactly unchanged. At x627, lower the RIGHT-HAND rail segment by about36 pixels so its upper contour meets the LEFT upper edge at approximately (627,515), its thin golden highlight edge meets (627,598), and its lower dark contour meets (627,664). Smoothly continue these three parallel contours to the existing far-right rail, making ONE straight continuous beam, with no vertical step at x627. Adjust only the adjacent right-half rail and immediately touching timber to connect correctly; the existing left edge is the absolute authority. Do not move the left half or hide the error by a shadow or a vertical strip. Preserve the same rail thickness, warm wood material, camera and all other structure. Keep the upper230px prior corrected context, and outermost150px of right edge unchanged. The wrong geometry on the right near x627 must be corrected, even if it differs from the current input there. No added detail, objects, plank divisions, recoloring, texture, blur, resizing or cropping. IMAGE 2 is confirmed Q-style material reference only, no UI. Return one opaque native1254x1254 corrected image1.'
 (D/'s2-refine.txt').write_text(prompt,encoding='utf-8');refs=[{'file':str(P),'sha256':sha(P),'role':'precise native edit target; only right-hand rail at center seam needs downward endpoint alignment'}, {'file':str(STYLE),'sha256':sha(STYLE),'role':'confirmed rounded clean Q-style material reference only'}];js(D/'s2-refine.references.json',refs);print(json.dumps({'prompt':prompt,'references':[x['file'] for x in refs]}))
elif sys.argv[1]=='record':
 src=Path(sys.argv[2]);assert Image.open(src).size==(1254,1254);temp=Path(str(S)+'.writing');shutil.copyfile(src,temp);temp.replace(S);refs=load(D/'s2-refine.references.json');old=load(D/'s2-first-generation.json');old.update(file=str(S),sha256=sha(S),generatedAt=datetime.now(timezone.utc).isoformat(),evidence={'toolResultSourcePath':str(src),'toolResultSha256':sha(src)},prompt=str(D/'s2-refine.txt'),promptSha256=sha(D/'s2-refine.txt'),references=refs,submittedParameters={'model':None,'quality':None,'transparent_background':False,'referenced_image_paths':[x['file'] for x in refs]},previousGenerationRecord={'file':str(D/'s2-first-generation.json'),'sha256':sha(D/'s2-first-generation.json')},specificFix='right-only central diagonal rail endpoint down about36px to match immutable left');js(Path(str(S)+'.generation.json'),old);print(json.dumps({'file':str(S),'sha256':sha(S)}))
