from pathlib import Path
import json
r=Path(r'D:/work/image/qdao_city_tiles_4k_20260916/builtin_q64_production/parallel_20261005/donghai_day')
s=(r/'production_r10_c15.py').read_text().replace('r10_c15','r11_c15').replace('r09_c15','r10_c15')
a=s.index("    prompt=",s.index('def prepare_structure'))
b=s.index("\n    save_prompt(",a)
s=s[:a]+"    prompt="+repr("Edit IMAGE1 only. This is the exact confirmed local layout crop of a fishing-village pier, a reference-only structural view. Preserve camera, scale, framing, all original silhouettes, object positions and counts. The lower half is a warm timber pier with wide diagonal planks, a thick front edge and several original cropped blue-gray-capped wooden mooring piles. At center stands the existing tall wooden lifting frame: tall rear upright at upper-right, a shorter left upright, curved sloping top member and one diagonal middle crossbar, with the same simple hanging pale ropes; keep the frame asymmetry and connections, do not make a gate or add a roof. Preserve the left slim orange-brown post with its long vertical red hanging decoration and pale-gold decorative marks, the small dark capped bollard behind it, the original sagging pale edge rope and small tie points. Preserve the single short blue-gray squared block at the frame foot. Upper background is quiet clear blue/cyan water; at the cropped top-right is the original blue-gray stone retaining wall and localized pale contact water marks. Keep this water broad and calm, no repeating waves, white net/caustic grid or noise. Preserve the existing wood-frame cast shadows across the deck. Do not add ropes, posts, plank divisions, lanterns, boats, text or objects. IMAGE2 is the PRIMARY confirmed style reference: rounded bright clean Q-style painted wood/stone with generous volume, crisp controlled outlines and soft clean directional shadows. Existing cropped objects must remain cropped at identical edges. Native opaque1254x1254; no UI, border, zoom, crop or viewpoint change. Redraw the structure cleanly while retaining its exact confirmed geometry. This is only a local structure reference, not final enlarged HD art.")+s[b:]
a=s.index("    prompt=",s.index('def prepare(row,column)'))
b=s.index("\n    save_prompt(",a)
s=s[:a]+"    prompt="+repr("Use case: precise-object-edit. Edit IMAGE1 only into a clean native-pixel fishing-village map fragment. Preserve the exact existing camera, framing, object count, positions, silhouette, material colors and directional light. Only paint portions actually visible: quiet cyan-blue water; original cropped gray retaining stone at far top if present; warm pier floor with its existing broad diagonal plank divisions; original wood lifting frame and sparse pale ropes; existing slim reddish post/red vertical decoration with its original pale-gold marks; original blue-gray-capped mooring piles and the small dark block at the frame foot. Never complete a cropped object. Add no posts, crossbars, planks, joints, knots, stairs, decorations, new writing, boats or figures. Keep the water intentionally broad, smooth and low contrast with only the original localized shore/contact marks if pictured, never white netting, wave grid, foam streaks or dense texture. Sharp border strips are exact verified neighboring native pixels: preserve their real geometry, far-edge color and shadow, and draw continuous structures across the soft/sharp transition; the strip boundary is not a physical line. IMAGE2 is the PRIMARY confirmed rounded bright clean Q-style hand-painted materials reference, clean substantial forms, controlled clear edges and soft existing cast shadows; no photoreal grain or dense microtexture. Return one opaque native1254x1254 image, no image enlargement, no changed framing, text/UI/frame/collage/blur/oversharpening. Highest available finish.")+s[b:]
s=s.replace("elif command=='record':p.record(sys.argv[2],sys.argv[3])","elif command=='record':\n        with Image.open(sys.argv[3]) as im:\n            im.load()\n            if im.size!=(1254,1254):raise ValueError('Native output must be1254x1254; never upscale')\n        refs=p.loadj(p.T/'prompts'/(sys.argv[2]+'.references.json'))\n        assert all(p.sha(v['file'])==v['sha256'] for v in refs)\n        p.record(sys.argv[2],sys.argv[3])")
(r/'production_r11_c15.py').write_text(s)

