"""Build an offline viewer using exported runtime PNGs only."""
from pathlib import Path
import json,hashlib
B=Path(__file__).resolve().parents[1]
M=json.loads((B/'manifest.json').read_text(encoding='utf-8'))
groups=[]
for s in M['sequences']:
 frames=[]
 for f in s['frames']:
  p=B/f['file']; assert p.is_file() and hashlib.sha256(p.read_bytes()).hexdigest()==f['sha256']
  frames.append({'src':'../'+f['file'],'frame':f['frame'],'duration':f['durationMs'],'sha256':f['sha256']})
 groups.append({'action':s['action'],'direction':s['direction'],'frames':frames,'ms':s['ms'],'cycle':s['cycleMs']})
D={'character':M['character'],'status':M['status'],'clientIntegrated':False,'sequences':groups}
HTML=r"""<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>灵篆书生 · 完整动作</title><style>
*{box-sizing:border-box}body{margin:0;background:#10211d;color:#eee9d7;font:15px/1.6 "Microsoft YaHei",sans-serif}main{max-width:1080px;margin:auto;padding:24px}h1{font-size:26px;margin:0}p{color:#b9cbbc}button,select{font:inherit;background:#264035;color:#fff4d9;border:1px solid #5f7865;border-radius:6px;padding:7px 12px}button{cursor:pointer}.bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:18px 0}.view{padding:20px;border:1px solid #546951;border-radius:12px;background:#1b3028}#stage{width:240px;height:240px;position:relative;margin:20px auto;background:#d9ddd6;overflow:hidden}#stage.large{width:480px;height:480px}#stage img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}#stage.dark{background:#243237}#stage.checker{background:repeating-conic-gradient(#d5d9d0 0 25%,#eef0e6 0 50%) 0/20px 20px}.meta{display:flex;justify-content:space-between;gap:12px}#film{display:grid;grid-template-columns:repeat(8,1fr);gap:8px;margin-top:20px}#film button{padding:3px;background:#31483c}#film img{display:block;width:100%;aspect-ratio:1}#film .active{border:2px solid #e7c76a}a{color:#b6e1c7}#seek{width:250px}small{color:#b9cbbc}@media(max-width:650px){main{padding:14px}#film{grid-template-columns:repeat(4,1fr)}#stage.large{width:320px;height:320px}}
</style><main><h1>17 灵篆书生 · 完整动作</h1><p>八方向跑步，以及东西方向受击、普攻和施法。每帧为1024×1024透明PNG，预览保持整张画布和统一锚点。</p>
<div class="bar"><label>动作 <select id="action"><option value="run">跑步</option><option value="hit">受击</option><option value="attack">普攻</option><option value="cast">施法</option></select></label><label>方向 <select id="direction"></select></label><button id="play">播放</button><button id="restart">从头播放</button><label>速度 <select id="speed"><option value="1">正常</option><option value="0.25">慢放 ×0.25</option></select></label><label><input id="large" type="checkbox">放大</label><label>背景 <select id="bg"><option value="">浅底</option><option value="dark">深底</option><option value="checker">棋盘</option></select></label></div>
<div class="view"><div class="meta"><strong id="title"></strong><span id="timing"></span></div><div id="stage"><img id="sprite" alt="角色动作"></div><div class="bar"><button id="prev">上一帧</button><input id="seek" aria-label="帧" type="range" min="1" value="1"><button id="next">下一帧</button><output id="number"></output></div><p id="phase"></p><small id="status"></small></div><div id="film"></div>
<p><a href="../manifest.json">196帧素材与来源清单</a> · <a href="../DELIVERY.md">交付说明</a> · <a href="run-current-1200ms.webp">八方向跑步动图</a></p><small>本页读取正式导出的runtime文件。客户端资源接入与游戏内位移未在本次素材制作中执行。</small></main><script id="data" type="application/json">__DATA__</script><script>
'use strict';const D=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id);const names={run:'跑步',hit:'受击',attack:'普攻',cast:'施法'};let seq,images=[],index=0,playing=false,started=0,baseMs=0,raf=0,version=0,rate=1;
const phases=['前侧落地 / 承重','身下支撑','后侧第一位置支撑','后侧第二位置支撑至换脚'];
function ready(){return !!seq&&images.length>0&&images.length===seq.frames.length;}
function controls(disabled){['play','restart','prev','next','seek'].forEach(id=>$(id).disabled=disabled);}
function elapsed(){return seq?(baseMs+(playing?Math.max(0,performance.now()-started)*rate:0))%seq.cycle:0;}
function paint(n){if(!ready()||!Number.isInteger(n)||n<0||n>=images.length)return;index=n;$('sprite').src=images[n].src;$('seek').value=n+1;$('number').textContent=String(n+1).padStart(2,'0')+' / '+images.length;[...$('film').children].forEach((b,j)=>b.classList.toggle('active',j===n));$('phase').textContent=seq.action==='run'?((n<8?'第一支撑脚':'另一支撑脚')+' · '+phases[Math.floor(n%8/2)]+' · 每个位置段两张独立姿态'):seq.action==='attack'&&n===5?'普攻接触帧':seq.action==='cast'&&n===9?'施法释放帧':'';}
function stop(){if(playing)baseMs=elapsed();playing=false;cancelAnimationFrame(raf);$('play').textContent='播放';}
function tick(){if(!playing||!ready())return;paint(Math.floor(elapsed()/seq.ms));raf=requestAnimationFrame(tick);}
function play(){if(!ready()||playing)return;started=performance.now();rate=Number($('speed').value);playing=true;$('play').textContent='暂停';paint(Math.floor(baseMs/seq.ms));raf=requestAnimationFrame(tick);}
function step(n){if(!ready()||!Number.isInteger(n))return;stop();const i=((n%images.length)+images.length)%images.length;baseMs=i*seq.ms;paint(i);}
async function load(){stop();const v=++version;seq=D.sequences.find(s=>s.action===$('action').value&&s.direction===$('direction').value);images=[];index=0;baseMs=0;controls(true);$('film').replaceChildren();$('sprite').removeAttribute('src');$('number').textContent='';$('phase').textContent='';$('status').textContent='加载中';if(!seq){$('title').textContent='';$('timing').textContent='';$('status').textContent='未找到动作方向';return}const loadingSeq=seq;$('title').textContent=names[seq.action]+' · '+seq.direction;$('timing').textContent=seq.ms+'ms / 帧 · '+seq.cycle+'ms / 圈';try{const ims=await Promise.all(loadingSeq.frames.map(async f=>{const im=new Image;im.src=f.src;await im.decode();return im}));if(v!==version)return;images=ims;$('seek').max=images.length;$('film').replaceChildren(...images.map((im,i)=>{const b=document.createElement('button');const t=im.cloneNode();t.alt='第'+(i+1)+'帧';b.append(t,document.createTextNode(String(i+1).padStart(2,'0')));b.onclick=()=>step(i);return b}));paint(0);$('status').textContent=images.length+'张素材已加载';controls(false)}catch(e){if(v===version)$('status').textContent='加载失败：'+e.message}}
function action(){const ds=D.sequences.filter(s=>s.action===$('action').value).map(s=>s.direction),old=$('direction').value;$('direction').replaceChildren(...ds.map(d=>new Option(d,d)));$('direction').value=ds.includes(old)?old:ds[0];load()}
$('action').onchange=action;$('direction').onchange=load;$('play').onclick=()=>playing?stop():play();$('restart').onclick=()=>{if(!ready())return;stop();baseMs=0;play()};$('prev').onclick=()=>step(index-1);$('next').onclick=()=>step(index+1);$('seek').oninput=()=>step(Number($('seek').value)-1);$('speed').onchange=()=>{const resume=playing;stop();rate=Number($('speed').value);if(resume)play()};function bg(){$('stage').className=($('large').checked?'large ':'')+$('bg').value}$('large').onchange=bg;$('bg').onchange=bg;document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('play').click()}if(e.key==='ArrowLeft')step(index-1);if(e.key==='ArrowRight')step(index+1)});action();
</script></html>"""
out=B/'preview';out.mkdir(exist_ok=True)
(out/'delivery-data.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(out/'delivery.html').write_text(HTML.replace('__DATA__',json.dumps(D,ensure_ascii=False).replace('</','<\\/')),encoding='utf-8')
print(json.dumps({'frames':sum(len(s['frames']) for s in groups),'groups':len(groups),'path':str(out/'delivery.html')}))
