from pathlib import Path
import sys,numpy as np
from PIL import Image
sys.dont_write_bytecode=True
T=Path(__file__).resolve().parent;sys.path.insert(0,str(T));import compose_patch as c
h=c.h;R=T/'repairs';O=R/'shared-output-v1';state=h.p.read(R/'shared-boundary-state.json');deltas=[]
for k in ['r10_c10','r11_c10']:
 base=Path(state[k]['file']) if k=='r10_c10' else T/'tiles/r11_c10-candidate.png';f=O/(k+'-candidate.png');aa=np.asarray(Image.open(base).convert('RGB'));bb=np.asarray(Image.open(f).convert('RGB'));assert aa.shape==bb.shape==(4096,4096,3);m=np.any(aa!=bb,2);mp=O/(k+'-change-mask.png');Image.fromarray(m.astype('uint8')*255).save(mp);replay=aa.copy();replay[m]=bb[m];assert np.array_equal(replay,bb);yy,xx=np.nonzero(m);bbox=[int(xx.min()),int(yy.min()),int(xx.max()+1),int(yy.max()+1)];tiley=36864 if k=='r10_c10' else 40960
 deltas.append({'tile':k,'globalRectXYWH':[36864,tiley,4096,4096],'baseline':str(base),'baselineSha256':h.p.sha(base),'candidate':str(f),'candidateSha256':h.p.sha(f),'changeMask':str(mp),'changeMaskSha256':h.p.sha(mp),'changedPixels':int(m.sum()),'bboxLTRB':bbox,'replayExact':True,'mergeRule':'Apply candidate pixels where mask255 only; preserve all other current neighbor pixels.'})
validation=[]
for src in sorted((T/'native').glob('p??.png'))+sorted(R.glob('*/native/*.png'))+[T/'references/structure.png']:
 rp=Path(str(src)+'.generation.json');rec=h.p.read(rp);assert h.p.sha(src)==rec['sha256'];assert Image.open(src).size==(1254,1254);assert h.p.sha(rec['toolResultPath'])==rec['sha256'];assert Path(rec['evidence']['toolOutputHintFile']).exists()
 for ref in rec['references']:assert h.p.sha(ref['file'])==ref['sha256'],ref
 assert any(Path(ref['file']).name=='04-guild.png' for ref in rec['references'])
 assert rec['actualModel'] is None and rec['actualQuality'] is None
 validation.append({'file':str(src),'sha256':rec['sha256'],'record':str(rp),'actualModel':None,'actualQuality':None,'referencesAndToolSourceHashVerified':True})
manifest={'schema':1,'tile':'r11_c10','createdAt':h.p.stamp(),'finalCandidate':str(O/'r11_c10-candidate.png'),'sha256':h.p.sha(O/'r11_c10-candidate.png'),'globalRectXYWH':[36864,40960,4096,4096],'deltas':deltas,'nativeDetailCount':16,'nativeRepairCount':8,'layoutStructureCount':1,'nativeRecordsVerified':validation,'layoutGuideNeverFinalPixels':True,'allSourcesNative1254':True,'provenance':{'ownership':str(R/'internal-quilt/record-v2.json'),'internalAI':str(R/'internal-ai/output-v1/record.json'),'northShared':str(O/'record.json')},'qa':{'status':'local visual QA complete; all listed native contexts actually inspected after final compose','sixInternalLines':[str(T/'qa'/f'shared-v1-{ax}{n}.png') for ax in ['x','y'] for n in [1024,2048,3072]],'nineJunctions':str(T/'qa/shared-v1-junctions.png'),'nineFull1254InternalContexts':[str(O/f'internal-full-{x}-{y}.png') for y in [1024,2048,3072] for x in [1024,2048,3072]],'fourFull1254NorthReturnContexts':[str(O/f'north-s{i}-review.png') for i in range(1,5)],'threeFull1254NorthCrossingContexts':[str(O/f'north-cross{i}-review.png') for i in range(1,4)],'fourInternalRepairReturnContexts':[str(R/'internal-ai/output-v1'/(n+'-review.png')) for n in ['stone-upper','stone-lower','leaf','post']]},'notYetApplicable':['east r11_c11 absent at assignment; future east and NE fourtile global integration owned by root','west and south new neighbor seams require future neighboring native tiles'],'conflictReview':['north proposal modifies r10_c10 bottom band including right edge; root should use exactmask and review eventual r10_c10/r10_c11/r11_c10/r11_c11 corner when r11_c11 exists'],'formalAccepted':False,'clientAccepted':False,'wholeCityComplete':False,'cleanup':'Root owns final cleanup after regional merge and current-reference validation. No source images deleted here.'}
h.p.write(R/'handoff-shared-v1.json',manifest);h.p.write(T/'progress.json',{'tile':'r11_c10','updatedAt':h.p.stamp(),'nativeDetailPatches':16,'expectedPatches':16,'nativeRepairPatches':8,'completePixelCandidateTiles':1,'stage':'local_native_qa_complete_handoff_ready','finalCandidate':manifest['finalCandidate'],'handoff':str(R/'handoff-shared-v1.json'),'formalAccepted':0,'clientAccepted':False,'wholeCityComplete':False});h.p.write(T/'current-work.json',{'tile':'r11_c10','stage':'local_native_qa_complete_handoff_ready','next':'root exactmask merge and eventual adjacent tile corner integration','handoff':str(R/'handoff-shared-v1.json')});print([(e['tile'],e['candidateSha256'],e['bboxLTRB'],e['changedPixels']) for e in deltas]);print('verified',len(validation))

