const fs=require('fs'),path=require('path'); const {chromium}=require('C:/Users/luyua/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='E:/work/image/designs/guild-ui-v2/qa';
(async()=>{ const browser=await chromium.launch({headless:true,channel:'msedge'}); const page=await browser.newPage(); const samples=[];
for(const [width,height,id] of [[1600,675,'overview'],[1600,675,'shop'],[320,844,'members'],[320,844,'overview'],[320,844,'donation'],[390,844,'overview']]){
 await page.setViewportSize({width,height}); await page.goto('http://127.0.0.1:4345/guild-ui-v2/',{waitUntil:'networkidle'}); await page.locator('[data-page="'+id+'"]').click(); await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(out,'visual-review-final-'+width+'x'+height+'-'+id+'.png'),fullPage:true});
 samples.push(await page.evaluate((id)=>({page:id,viewport:{width:innerWidth,height:innerHeight},horizontalOverflow:document.documentElement.scrollWidth-innerWidth,buttonSkins:[...document.querySelectorAll('.tabs button,.button')].filter(e=>e.getClientRects().length).map(e=>({text:e.innerText,backgroundImage:getComputedStyle(e).backgroundImage,borderImage:getComputedStyle(e).borderImageSource,slice:getComputedStyle(e).borderImageSlice,w:e.clientWidth,h:e.clientHeight,scrollWidth:e.scrollWidth,scrollHeight:e.scrollHeight})),searchWhiteSpace:document.querySelector('.search-label')?getComputedStyle(document.querySelector('.search-label')).whiteSpace:null,heading:document.querySelector('.page-heading').innerText,missingImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)}),id));
}
await browser.close(); const report=JSON.parse(fs.readFileSync(path.join(out,'visual-review.json'),'utf8'));report.finalCheck={checkedAt:new Date().toISOString(),scope:'Five requested focused samples plus 390px overview after root nine-slice and wrapping repairs',samples};report.visualReview={status:'reviewed',reviewedInitialScreenshots:24,notes:['No missing images, JavaScript errors, document horizontal overflow or fixed-container text clipping in the initial 24 samples.','Desktop short-height content uses an internal scrollbar where needed; mobile pages scroll naturally and keep footer actions reachable.','Root corrected button, tab and portrait skins from full-image stretching to declared nine-slice rendering, and repaired narrow search/metric labels.'],outstanding:[]};fs.writeFileSync(path.join(out,'visual-review.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({focusedSamples:samples.length,issues:samples.filter(s=>s.horizontalOverflow||s.missingImages.length)}));})();
