from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,numpy as np,sys
from PIL import Image
BASE=Path(__file__).resolve().parent;T=BASE.parent;ROOT=next(p for p in T.parents if (p/'config/image-generation.json').exists());col=int(sys.argv[1]);assert col in [2,3,4]
P=BASE/f'r03_c{col:02}-v1';P.mkdir(exist_ok=True)
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'file':str(p),'sha256':sha(p)}
read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));write=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
x=(col-1)*1024-115;origin=[36864,24576];window=[x,1933,x+1254,3187];world=[origin[i%2]+window[i] for i in range(4)]
cp=read(BASE/'local-source-checkpoint.json');source=cp['fragment'];assert sha(source['file'])==source['sha256'];current=np.array(Image.open(source['file']).convert('RGBA'))
leftp=Path(cp['contextJoined']['file']);assert f'r03_c{col-1:02}-v1' in str(leftp);left=np.array(Image.open(leftp).convert('RGBA'));bottomp=BASE/f'r04_c{col:02}-v1/final-v1/joined.png';bottom=np.array(Image.open(bottomp).convert('RGBA'))
C=np.zeros((1254,1254,4),dtype=np.uint8);C[1024:,:,:]=bottom[:230,:,:]
clip=min(1254,4096-x);seen=current[1933:3187,x:x+clip];mask=seen[:,:,3]==255;C[:,:clip][mask]=seen[mask];C[:,:230]=left[:,1024:]
assert np.array_equal(C[:,:230],current[1933:3187,x:x+230]);Image.fromarray(C).save(P/'context.png')
master=ROOT/'tianyong_festival_hd_20260910/tianyong_city_master_6144.png';assert sha(master)=='aea4c03a216138cd447187279fb62d9f5660da875140a155ca01f88dd1f11428'
Image.open(master).convert('RGB').resize((1254,1254),Image.Resampling.BICUBIC,box=tuple(v*3/32 for v in world)).save(P/'layout-reference-only.png')
refs=[P/'context.png',P/'layout-reference-only.png',ROOT/'designs/gameplay-ui/04-guild.png']
prompt='''Use case: precise-object-edit / outpainting. Continue one exact native-detail crop of the original game 五行奇谈. Return one opaque 1254 by 1254 square image, same crop, scale and camera as image 1.
Image 1 is the EDIT TARGET: authentic existing pixels occupy the entire LEFT230 columns and BOTTOM230 rows. Fill only the transparent upper-right1024 square, preserving all visible native geometry, exact endpoints, bevel widths, junctions, color and light. Continue the same ground into the missing area without changing scale. Transparency boundaries are not physical seams.
Image 2 is only the identical-world canonical LAYOUT reference. Newly render its broad stone shapes and any existing carved detail; never copy blurred enlarged pixels or interpret tiny ambiguous marks as added decoration. Actual left and lower geometry in image1 takes priority. Image 3 is the approved primary STYLE reference only: bright clean rounded full Daoist Q fantasy handpainting, warm ivory and slate stone, restrained warm golden shading; no UI, words, figures or frames.
Finish only the real plaza geometry present in the layout, with broad smooth architectural bands, simple paving planes and continuous carved relief. Keep all edge endpoints and tangents. No new decorative stripe or invented seam. Quiet clean smooth stone, no cracks, grunge, veins, speckles, photo textures, polygon noise or oversharpening. No buildings, figures, props, plants, text, borders or watermark. No rotation, zoom, camera shift, cropping or rescale. Highest finish available through the host.'''
(P/'prompt.txt').write_text(prompt,encoding='utf8');req={'preparedAtUtc':datetime.now(timezone.utc).isoformat(),'tile':'r07_c10','patch':f'r03_c{col:02}','tileGlobalOrigin':origin,'globalCropLTRB':world,'tileLocalCropLTRB':window,'knownPixels':int((C[:,:,3]==255).sum()),'missingPixels':int((C[:,:,3]==0).sum()),'payload':{'prompt':prompt,'referenced_image_paths':[str(z) for z in refs],'transparent_background':False},'configSnapshot':read(ROOT/'config/image-generation.json'),'submittedParameters':{'model':None,'quality':None,'size':None},'formalAccepted':False};write(P/'request.json',req);write(P/'source-checkpoint-input.json',cp)
write(P/'preparation.json',{'references':[ref(z) for z in refs],'savedCheckpoint':ref(P/'source-checkpoint-input.json'),'sourceTile':{**source,'tile':'r07_c10','tileLocalLTRB':[0,0,4096,4096],'nativeScale':1},'northPriorFragment':source,'nativeInputs':[source,ref(leftp),ref(bottomp)],'master':ref(master),'nativeScale':1,'guidePixelsAllowedInFinal':False,'requiresPriorManifest':cp['manifest'],'consistencyProof':{'leftOverlapExact':True,'allContextPixelsNative':True},'knownRegions':[{'contextLTRB':[0,1024,1254,1254],'source':ref(bottomp),'sourceLTRB':[0,0,1254,230],'note':'Overridden by current fragment ROI wherever known'},{'contextLTRB':[0,0,230,1254],'source':ref(leftp),'sourceLTRB':[1024,0,1254,1254]}]})
for name,ss,op in [('context.png',[source,ref(leftp),ref(bottomp)],'Exact source-native context composition'),('layout-reference-only.png',[ref(master)],'Enlarged geometry reference only; never final pixels')]:write(P/(name+'.generation.json'),{'output':ref(P/name),'sources':ss,'operation':op,'newModelCalls':0,'actualModel':None,'actualQuality':None,'formalAccepted':False,'nativeScale':1})
print(json.dumps({'request':ref(P/'request.json'),'missingPixels':req['missingPixels']}))
