from pathlib import Path
import json,hashlib,datetime,sys
from PIL import Image
import numpy as np
D=Path(sys.argv[1]);F=D/'final-v1';ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()};read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));save=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf8')
assert (D/'qa-accepted.txt').exists(),'Explicit image inspection note required before publishing';prep=read(D/'preparation.json');req=read(D/'request.json');J=Image.open(F/'joined.png').convert('RGB');prior=prep['sourceTile'];x,y,_,_=req['tileLocalCropLTRB'];xl=max(0,-x);yt=max(0,-y);xr=min(1254,4096-x);yb=min(1200,4096-y);side=req['knownSide'];newl=230 if side=='left' else xl;newr=1024 if side=='right' else xr;patches=[]
save(F/'visual-review.json',{'reviewedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'image':ref(F/'joined.png'),'reviewMethod':'Whole native1254 image and all known return strips inspected at original pixels.','inspectedImages':[ref(p) for p in (F/'qa').glob('*.png')],'localVisualAccepted':True,'formalAccepted':False,'wholeTileAccepted':False,'findings':[(D/'qa-accepted.txt').read_text(encoding='utf8'),'Native new pixels, known-overlap composite only; no registration, rescale or tone adjustment.','All explicit returns must travel with the new core; this does not accept the whole map or unbuilt neighbors.'],'actualModel':None,'actualQuality':None})
rects=[('new-core',[newl,yt,newr,1024],None)]
if side=='left':rects.append(('left-return',[max(54,xl),yt,230,1024],prior))
if side=='right':rects.append(('right-return',[1024,yt,min(1200,xr),1024],prior))
bl=max(54,xl) if side=='left' else xl;br=min(1200,xr) if side=='right' else xr;rects.append(('bottom-return',[bl,1024,br,yb],prior))
fragment=Image.open(prior['file']).convert('RGBA');before=np.array(fragment);changes=np.zeros((4096,4096),bool)
for name,crop,src in rects:
 l,t,r,b=crop;dest=[x+l,y+t,x+r,y+b];dl,dt,dr,db=dest;p=F/(name+'.png');J.crop(crop).save(p)
 if src is None:assert not np.any(before[dt:db,dl:dr,3])
 fragment.paste(J.crop(crop).convert('RGBA'),(dl,dt));changes[dt:db,dl:dr]=True;patches.append({'name':name,'asset':ref(p),'cropFromJoinedLTRB':crop,'destinationTile':'r07_c10','destinationTileLTRB':dest,'requiredPriorSource':src,'nativeScale':1,'mustApplyTogether':True})
m={'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'appearance':'tianyong_festival','tile':'r07_c10','tileGlobalOrigin':[36864,24576],'nativeScale':1,'windowTileLocalLTRB':req['tileLocalCropLTRB'],'windowGlobalLTRB':req['globalCropLTRB'],'joined':ref(F/'joined.png'),'visualReview':ref(F/'visual-review.json'),'assembly':ref(F/'assembly.json'),'localVisualAccepted':True,'formalAccepted':False,'patches':patches,'sourceCheckpoint':prep['savedCheckpoint'],'requiresPriorManifest':prep['requiresPriorManifest'],'note':'Root review and live ROI validation required before root publication. Outside listed rectangles remains exact.'};save(F/'manifest.json',m);save(F/'joined.png.generation.json',{'operation':'native AI outpaint and source-preserving overlap composite','sources':[ref(D/'native.png'),ref(D/'context.png')],'assembly':ref(F/'assembly.json'),'output':ref(F/'joined.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'noUpscale':True,'formalAccepted':False})
after=np.array(fragment);assert np.array_equal(after[~changes],before[~changes]);fragment.save(F/'r07_c10-fragment.png');coverage=int(np.count_nonzero(after[:,:,3]==255));expected=int(np.count_nonzero(before[:,:,3]==255))+(newr-newl)*(1024-yt);assert coverage==expected
save(F/'r07_c10-fragment.png.generation.json',{'operation':'1:1 native patch composition','sources':[prior,ref(F/'joined.png')],'manifest':ref(F/'manifest.json'),'output':ref(F/'r07_c10-fragment.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'coveragePixels':coverage,'noUpscale':True,'formalAccepted':False,'pixelsOutsideManifestExact':True})
save(D.parent/'local-source-checkpoint.json',{'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tile':'r07_c10','fragment':ref(F/'r07_c10-fragment.png'),'nativeScale':1,'coveragePixels':coverage,'formalAccepted':False,'rootPublished':False,'manifest':ref(F/'manifest.json'),'previousManifest':prep['requiresPriorManifest'],'contextJoined':ref(F/'joined.png'),'bottomReturn':patches[-1]});print(json.dumps({'manifest':ref(F/'manifest.json'),'joined':ref(F/'joined.png'),'localCoveragePixels':coverage}))
