from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,numpy as np,sys
from PIL import Image
B=Path(__file__).resolve().parent;T=B.parent;ROOT=next(p for p in T.parents if (p/'config/image-generation.json').exists());row,col=map(int,sys.argv[1:3]);assert row in [1,2] and col in range(1,5)
P=B/f'r{row:02}_c{col:02}-v1';P.mkdir(exist_ok=True);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();ref=lambda p:{'file':str(p),'sha256':sha(p)};read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));write=lambda p,v:Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
assert not (P/'native.png').exists(),'Native already exists; do not replace preparation'
x=(col-1)*1024-115;y=(row-1)*1024-115;origin=[36864,24576];window=[x,y,x+1254,y+1254];world=[origin[i%2]+window[i] for i in range(4)]
cp=read(B/'local-source-checkpoint.json');source=cp['fragment'];assert sha(source['file'])==source['sha256'];current=np.array(Image.open(source['file']).convert('RGBA'))
below=sorted((B/f'r{row+1:02}_c{col:02}-v1').glob('final-*/manifest.json'),key=lambda p:p.stat().st_mtime)[-1];bm=read(below);bottomp=Path(bm['joined']['file']);assert sha(bottomp)==bm['joined']['sha256'];bottom=np.array(Image.open(bottomp).convert('RGBA'))
side='right' if row==2 and col<4 else 'left' if row==1 and col>1 else None
C=np.zeros((1254,1254,4),dtype=np.uint8);C[1024:]=bottom[:230];nativeinputs=[source,ref(bottomp)];regions=[{'contextLTRB':[0,1024,1254,1254],'source':ref(bottomp),'sourceLTRB':[0,0,1254,230],'note':'Latest in-tile fragment pixels override older overlapping returns'}]
if side:
 sp=Path(cp['contextJoined']['file']);assert f'r{row:02}_c{col+(1 if side=="right" else -1):02}-v1' in str(sp);sa=np.array(Image.open(sp).convert('RGBA'));nativeinputs.append(ref(sp))
 if side=='right':C[:,1024:]=sa[:,:230];regions.append({'contextLTRB':[1024,0,1254,1254],'source':ref(sp),'sourceLTRB':[0,0,230,1254]})
 else:C[:,:230]=sa[:,1024:];regions.append({'contextLTRB':[0,0,230,1254],'source':ref(sp),'sourceLTRB':[1024,0,1254,1254]})
l,t,r,b=max(x,0),max(y,0),min(x+1254,4096),min(y+1254,4096);piece=current[t:b,l:r];known=piece[:,:,3]==255;C[t-y:b-y,l-x:r-x][known]=piece[known];Image.fromarray(C).save(P/'context.png')
master=ROOT/'tianyong_festival_hd_20260910/tianyong_city_master_6144.png';assert sha(master)=='aea4c03a216138cd447187279fb62d9f5660da875140a155ca01f88dd1f11428';Image.open(master).convert('RGB').resize((1254,1254),Image.Resampling.BICUBIC,box=tuple(v*3/32 for v in world)).save(P/'layout-reference-only.png')
refs=[P/'context.png',P/'layout-reference-only.png',ROOT/'designs/gameplay-ui/04-guild.png'];edge=(f' and the entire {side.upper()}230 columns' if side else '')
prompt=f'''Use case: precise-object-edit / outpainting. Continue one exact native-detail crop of the original game 五行奇谈. Return one opaque1254 by1254 square, same crop, scale and camera as image1.
Image1 is the EDIT TARGET: authentic existing native pixels occupy the bottom230 rows{edge}. Fill only the transparent black missing region, preserving every visible native contour, exact endpoint, bevel width, junction, color and light. Continue the same ground, never changing scale. Transparency boundaries are not physical seams.
Image2 is the identical-world canonical LAYOUT reference only. Newly render its broad stone shapes and actual partial carved motifs; never copy enlarged blurry pixels or treat ambiguous marks as added ornament. Real lower{(' and '+side) if side else ''} geometry in image1 is the edge connection constraint. If a joint enters from an existing edge, continue it to its natural crossing or structural endpoint; never dead-end a seam in a flat slab.
Image3 is approved STYLE only: bright clean rounded full Daoist Q fantasy handpainting, warm ivory and slate stone with restrained gold shading, no UI/words/frames. Render the actual plaza geometry shown by layout, broad smooth stone courses and simple paving planes. No invented decorative stripe or additional ledge. Clean stone, no cracks, grunge, marble veins, speckles, photo textures, polygon noise or oversharpening. No buildings, figures, props, plants, text, borders or watermark. No rotation, zoom, camera shift, crop or resize. Highest finish available through the host.'''
(P/'prompt.txt').write_text(prompt,encoding='utf8');req={'preparedAtUtc':datetime.now(timezone.utc).isoformat(),'tile':'r07_c10','patch':f'r{row:02}_c{col:02}','row':row,'col':col,'knownSide':side,'tileGlobalOrigin':origin,'globalCropLTRB':world,'tileLocalCropLTRB':window,'knownPixels':int((C[:,:,3]==255).sum()),'missingPixels':int((C[:,:,3]==0).sum()),'payload':{'prompt':prompt,'referenced_image_paths':[str(z) for z in refs],'transparent_background':False},'configSnapshot':read(ROOT/'config/image-generation.json'),'submittedParameters':{'model':None,'quality':None,'size':None},'formalAccepted':False};write(P/'request.json',req);write(P/'source-checkpoint-input.json',cp)
write(P/'preparation.json',{'references':[ref(z) for z in refs],'savedCheckpoint':ref(P/'source-checkpoint-input.json'),'sourceTile':{**source,'tile':'r07_c10','tileLocalLTRB':[0,0,4096,4096],'nativeScale':1},'northPriorFragment':source,'nativeInputs':nativeinputs,'master':ref(master),'nativeScale':1,'guidePixelsAllowedInFinal':False,'requiresPriorManifest':cp['manifest'],'consistencyProof':{'currentFragmentOverlayExact':True,'allContextPixelsNative':True},'knownRegions':regions})
for name,ss,op in [('context.png',nativeinputs,'Exact source-native context composition'),('layout-reference-only.png',[ref(master)],'Enlarged geometry reference only; never final pixels')]:write(P/(name+'.generation.json'),{'output':ref(P/name),'sources':ss,'operation':op,'newModelCalls':0,'actualModel':None,'actualQuality':None,'formalAccepted':False,'nativeScale':1})
print(json.dumps({'request':ref(P/'request.json'),'missingPixels':req['missingPixels']}))
