from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
base='''Use case: precise-object-edit. One single high-resolution transparent game running sprite, square full canvas at least 1024px.
Image 1 is the exact current thunder caster boy edit target and identity. Image 2 is the user-approved same-direction archer only for readable support-versus-swing mechanics, not for copying her proportions or costume. Image 3 is approved painted style.
Preserve the entire upper body, exact head size and canvas position, hair margins, camera, head angle, torso, cape, shoulder/elbow swing, hands and props from image 1. Anatomical RIGHT hand keeps golden pointed scepter, LEFT hand keeps rectangular gold taiji plaque. Do not zoom, resize, move whole character, change the arms, rotate camera or copy another pose.
The user needs a continuous real contact progression: one foot contacts, remains grounded while the body passes over it, pushes behind, then the other foot lands. This is a distinct single frame in that progression. Redraw actual hip/knee/ankle/boot geometry below the robe to achieve the described support location, not by shifting the whole image. Keep short chibi legs, subtle knee compression, knee-ankle-toe aligned with travel direction, no sideways splay. Only the support foot touches its invisible ground plane. Opposite swinging foot stays distinctly raised. Both legs remain readable. Coordinates are composition guides on a 1024 square, scaled proportionately for larger canvas.
'''
end='''
Retain clean detailed hand-painted ivory/navy/gold fabric, gold fittings, turquoise beads, white calf wraps and black/gold boots. Exactly two legs and feet. Real alpha transparency; no floor, shadow patch, dust, glow, effects, arrows or labels. No mirroring, duplicate-pose shortcut, limb stretching, extra boots, or whole-sprite translation. Return one complete sprite only.'''
spec={}
for i in [14,15,6,7]:
 right=i>=14; side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT'; other='LEFT' if right else 'RIGHT'; x=580 if right else 477;y=919 if i%2==0 else 926
 spec[('N',i)]=f'''NORTH straight rear view. EARLY CONTACT phase, {side} leg supports. Place this boot flat on the ground AHEAD of the pelvis along north travel (slightly higher in the picture): rear heel at about ({x},{y}), foot long axis straight up/away with zero lateral toe splay. The thigh reaches slightly forward under the robe and knee is softly bent as heel and forefoot take weight. This is a real planted boot, not floating; only the rounded heel counter and thin gold sole edge are visible from behind. The opposite {other} leg is folded up behind the body with its small outsole visible and distinctly above the grounded heel. {('First gentle touchdown, knee only softly flexed.' if i%2==0 else 'Next independent settling pose, knee flexes a little more and free calf advances slightly; do not duplicate previous pose.')}'''
for i in [1,8,9]:
 right=i==1;side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT';x=594 if right else 472;y=950 if i%2 else 946
 spec[('N',i)]=f'''NORTH straight rear view. FRONT-SIDE WEIGHT BEARING phase. Keep the {side} foot flat and loaded, heel about ({x},{y}), slightly in front of pelvis on its travel axis; knee visibly flexed so weight sits over this leg. Heel and forefoot both planted; heel counter visible and toes point straight NORTH away from viewer, not sideways. Opposite leg stays folded and airborne. Compared with first contact, body is passing toward this foot; this is a different knee and ankle articulation, not a duplicate. Preserve all existing upper-body pose.'''
for i in [3,11]:
 right=i==3;side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT';x=610 if right else 464
 spec[('N',i)]=f'''NORTH straight rear view. BODY PASSING OVER SUPPORT phase. The {side} boot is still firmly loaded near ({x},972) at its rear heel, now just behind the pelvis in northward travel. Repaint the current prematurely heel-lifted boot into a mostly flat loaded boot, heel and forefoot on the plane, thin sole edge and rear heel counter visible, no large camera-facing outsole on this support foot. Keep the knee naturally slightly bent, short wrapped calf. Opposite leg is airborne moving forward toward its next landing. Do not toe-off yet.'''
for i in [4,5,12,13]:
 right=i<8;side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT';other='LEFT, screen LEFT' if right else 'RIGHT, screen RIGHT';x=610 if right else 457;y=977 if i%2==0 else 982
 spec[('N',i)]=f'''NORTH straight rear view. LATE REAR SUPPORT / PUSH-OFF phase. The {side} leg is STILL the same support leg, extended BEHIND pelvis toward viewer, its FOREFOOT/toe tip in ground contact near ({x},{y}). Heel raises gradually toward camera, visible narrow dark outsole and gold sole rim, boot long axis still NORTH, no outward turn. Knee extends naturally to push the body forward; short wrapped calf, no long straight tube. The other {other} leg swings FORWARD with bent knee and boot lifted clearly above the ground, approaching next touchdown but not bearing weight. This is essential: do not let the other leg become support yet, and do not draw both feet airborne. {('Start the push with low heel lift and toe loaded.' if i%2==0 else 'Second distinct push frame with heel slightly higher, toe still on the same ground region and opposite knee advancing; no pose duplication.')}'''
for i in [14,15,6,7]:
 right=i>=14;side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT';other='LEFT' if right else 'RIGHT';hx,hy=(585,920) if right else (405,920);tx,ty=(510,886) if right else (330,885)
 spec[('NW',i)]=f'''NORTHWEST three-quarter REAR view. INITIAL CONTACT. The {side} leg reaches FORWARD along travel toward UPPER LEFT and plants its boot flat AHEAD of body: heel near ({hx},{hy}), toe toward ({tx},{ty}). Knee softly bends to take body weight. Both heel and forefoot grounded, thin sole edge, rounded near heel counter; never show a front-facing toe toward viewer. The other {other} leg folds up behind the body, its outsole visible well above the ground. Preserve rear NW camera and all existing arm movement. {('Gentle initial contact, knee softly flexed.' if i%2==0 else 'Second independent compression pose, support knee a little more flexed and swing calf advances slightly, not a duplicate.')}'''
for i in [2,3,10,11]:
 right=i<8;side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT';other='LEFT' if right else 'RIGHT';hx,hy=(700,974) if right else (555,976);tx,ty=(615,935) if right else (470,937)
 spec[('NW',i)]=f'''NORTHWEST three-quarter REAR view. BODY PASSING OVER SUPPORT. The {side} leg is the loaded support, its planted boot now BEHIND pelvis along NW travel, spatially down-right from its earlier contact: heel near ({hx},{hy}), toe toward ({tx},{ty}), both sole ends grounded. Keep NW boot yaw, heel on near/down-right side, toe upper-left, no large visible outsole on support. Knee naturally flexed but starting to extend as pelvis passes over planted foot. The other {other} knee is bent and airborne forward, boot entirely above its ground projection. {('First body-passing pose, heel remains loaded.' if i%2==0 else 'Next distinct progression pose with slightly extending support knee and forward-advancing free knee; still loaded heel, not an early jump.')} Preserve head and upper body from target exactly.'''
for i in [4,5,12,13]:
 right=i<8;side='RIGHT, screen RIGHT' if right else 'LEFT, screen LEFT';other='LEFT, screen LEFT' if right else 'RIGHT, screen RIGHT';tx,ty=(710,972) if right else (585,972)
 spec[('NW',i)]=f'''NORTHWEST three-quarter REAR view. REAR PUSH-OFF. The {side} leg is STILL support, extends BEHIND pelvis toward LOWER RIGHT. Its forefoot/toe tip is STILL on invisible ground near ({tx},{ty}); heel lifted behind and above the toe, partial dark outsole visible toward viewer. Boot still follows NW long axis, not outward; this leg pushes body forward. The other {other} knee swings FORWARD toward UPPER LEFT and is flexed; its boot floats clearly above its ground plane approaching a future landing, NOT supporting yet. Redraw both lower-leg chains accordingly while preserving all upper body and arms. Never show both feet floating. {('First push, lower heel lift, obvious toe pressure.' if i%2==0 else 'Second independent push, heel higher and airborne knee advances, toe remains in contact, not a duplicated pose.')}'''
for (d,i),desc in spec.items():
 stem=f'run_{d}_{i:02d}_position2_v1';(R/'prompts'/f'{stem}.txt').write_text(base+desc+end,encoding='utf-8')
 refs=[{'path':str(R/'runtime/run'/d/f'{i:02d}.png'),'purpose':'exact edit target, current identity, camera and arm phase'},{'path':str(R.parent/'09_bamboo_archer_girl/runtime/run'/d/('01.png' if d=='N' else '09.png')),'purpose':'user approved same direction grounding mechanics'},{'path':'D:/work/image/designs/jubaozhai-ui/02-characters.png','purpose':'approved painted style'}]
 (R/'records'/f'{stem}_references.json').write_text(json.dumps(refs,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(spec),'unique targeted candidates prepared')
