import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[3]
phases={
 '09':('08','Keep LEFT leg on VIEWER RIGHT as front weight-bearing leg. LEFT sole stays on ground and knee bends 10 degrees more. RIGHT leg on viewer-left stays behind with heel raised. Do not reverse legs. Right scepter forearm starts coming inward toward chest by only a few degrees; left plaque stays mostly behind. Slight hip compression.'),
 '11':('08','Left leg on viewer-right is now moving BACK to toe-off, rear toe pushing and heel lifting. RIGHT knee on viewer-left passes FORWARD under hips, bent, foot off ground. Plaque LEFT arm starts forward swing from behind, and RIGHT scepter arm passes toward rear beside body. Show the in-between crossing of thighs, not full long stride yet.'),
 '13':('12','Keep RIGHT leg on VIEWER LEFT in front and left leg behind. Lower the leading right knee very slightly and extend right shin 10 degrees as flight descends; right boot bottom y88%, left rear heel y82%, both remain airborne. Plaque left hand stays forward, right staff hand stays back but lowers from shoulder to beside upper ribs. Tiny motion from image1, no pose reversal.'),
 '14':('12','Keep RIGHT leg on VIEWER LEFT leading. Leading right shin extends down-forward and right heel approaches ground, boot bottom y90%, toes slightly up. Left knee trails behind, rear heel tucked y84%. Plaque arm left remains forward; scepter arm right bent behind ribs. Pelvis slightly lower from flight, no pose reversal.'),
 '15':('12','Keep RIGHT leg on VIEWER LEFT leading. Right heel almost meets ground at y91%, right knee slightly bent, left leg trails behind with heel raised. Lower right knee to modest contact stride like standing proportions, not a high-knee pose. Right scepter arm behind torso starts returning near side, left plaque arm forward begins return toward ribs. This is the frame just before right-foot contact00. No pose reversal.')}
for slot,(anchor,phase) in phases.items():
 stem=f'run_S_{slot}_v3'
 refs=[{'path':str(ROOT/f'work/run_S_{anchor}_v2.png'),'role':'EDIT TARGET, same continuous running half-cycle'}, {'path':str(REPO/'qdao_original_roster_v14_hd/recovery-20260921/06-final/runtime/idle/S.png'),'role':'fixed frontal camera and character scale'}, {'path':str(REPO/'q_daoist_character_pack_4096/06_thunder_caster_boy_transparent_4096.png'),'role':'identity only'}, {'path':str(REPO/'designs/jubaozhai-ui/02-characters.png'),'role':'approved paint finish'}]
 prompt=f'''Edit IMAGE1 into the neighboring run pose S{slot}. This is a small animation progression, not a new composition. {phase} Preserve image1 frontal camera, canvas scale, exact face/head size and all design. Keep ponytail tip around y13%, face bottom around y46%, belt center around y60%. TWO hands, TWO boots and two legs. Anatomical RIGHT hand always holds gold pointed taiji scepter on viewer-left; anatomical LEFT hand holds rigid rectangular gold taiji plaque on viewer-right, never change props. Keep white shin wraps, blackgold boots, navy lightning trousers, gold ivory robe navy lining, brown hair, gold ribbons/turquoise beads. Moderate cloth inertia only. Orthographic front view, no diagonal turn. Image2 only camera reference, image3 only identity details, image4 only painted finish. Maintain separated correct fingers, joint connections and feet. Genuine transparent native square>=1024, no shadow/floor/FX/text/grid. DO NOT zoom or resize the head.''' 
 (ROOT/'prompts'/f'{stem}.txt').write_text(prompt,encoding='utf-8');(ROOT/'records'/f'{stem}_references.json').write_text(json.dumps(refs,ensure_ascii=False,indent=2),encoding='utf-8')
print('Targeted neighbor edits saved.')
