// Local-only rendering and interaction checks. No downloads or image-generation APIs.
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage({viewport:{width:1600,height:675},deviceScaleFactor:1.6});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
  const base=process.env.PREVIEW_URL || 'http://127.0.0.1:4311/attribute-panels/';
  await page.goto(base+'?panel=hero',{waitUntil:'networkidle'});
  await page.screenshot({path:path.join(__dirname,'01-character_2560x1080.png')});
  await page.locator('[data-mode="pet"]').click();
  await page.screenshot({path:path.join(__dirname,'02-pet_2560x1080.png')});
  await page.locator('[data-pet="fuxiaohu"]').click();
  assert.equal(await page.locator('#remaining').textContent(),'8');
  await page.getByRole('button',{name:'增加力量',exact:true}).click();
  assert.equal(await page.locator('#remaining').textContent(),'7');
  await page.locator('[data-pet="lingyue"]').click();
  assert.equal(await page.locator('#remaining').textContent(),'6');
  await page.locator('[data-pet="fuxiaohu"]').click();
  assert.equal(await page.locator('#remaining').textContent(),'7');
  await page.locator('#reset').click();
  assert.equal(await page.locator('#remaining').textContent(),'8');
  await page.locator('#auto').click();
  assert.equal(await page.locator('#remaining').textContent(),'0');
  assert(await page.getByRole('button',{name:'增加力量',exact:true}).isDisabled());
  await page.locator('#confirm').click();
  assert(await page.locator('#confirm').isDisabled());
  assert(await page.getByRole('button',{name:'减少力量',exact:true}).isDisabled());
  await page.locator('#wash').click();
  await page.locator('#dialogAction').click();
  assert.equal(await page.locator('#remaining').textContent(),'8');
  await page.locator('#battle').click();
  assert((await page.locator('[data-pet="fuxiaohu"] .pet-status').innerText()).includes('参'));
  await page.locator('#help').click();
  assert(await page.locator('#infoDialog').isVisible());
  await page.keyboard.press('Escape');
  await page.locator('#closePanel').click();
  assert(await page.locator('#reopen').isVisible());
  await page.locator('[data-open="hero"]').click();
  assert(await page.locator('#panel').isVisible());
  const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src));
  assert.deepEqual(broken,[]);
  const overflow=await page.evaluate(()=>Array.from(document.querySelectorAll('.panel-body > *')).map(e=>({name:e.className,client:e.clientHeight,scroll:e.scrollHeight})).filter(x=>x.scroll>x.client+3));
  await page.goto(base+'?panel=hero&state=clean',{waitUntil:'networkidle'});
  assert.equal(await page.locator('#remaining').textContent(),'20');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(__dirname,'mobile-character.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.getByRole('button',{name:'增加力量',exact:true}).click();
  assert.equal(await page.locator('#remaining').textContent(),'19');
  await page.locator('[data-mode="pet"]').click();
  await page.screenshot({path:path.join(__dirname,'mobile-pet.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.setViewportSize({width:844,height:390});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert((await page.getByRole('button',{name:'增加力量',exact:true}).boundingBox()).width>=44);
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(__dirname,'validation.json'),JSON.stringify({status:'passed',exports:{'01-character_2560x1080.png':[2560,1080],'02-pet_2560x1080.png':[2560,1080]},checks:['assets load','independent pet drafts','remaining points','reset draft','auto distribute','zero-points disables plus','confirm commit','saved points cannot be decremented','refund preview points','pet battle state','help dialog','close and reopen','clean state','mobile 390px layout and touch'],browserErrors:errors,desktopColumnOverflow:overflow,scope:'Browser prototype only; no game client or server integration.'},null,2));
  console.log(JSON.stringify({status:'passed',browserErrors:errors,desktopColumnOverflow:overflow}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
