const {chromium}=require('C:/Users/luyua/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:2560,height:1080}}),checks=[],errors=[];
 const report='E:/work/image/designs/social-ui-v1/qa/channels-validation.json',shot='E:/work/image/designs/social-ui-v1/screenshots/';
 const check=(name,pass,detail)=>{checks.push({name,passed:!!pass,...(detail===undefined?{}:{detail})});if(!pass)throw Error(name+' '+JSON.stringify(detail));};
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 const url='http://localhost:4351/social-ui-v1/index.html?view=world';
 try{
 await page.clock.install();await page.goto(url);await page.evaluate(()=>{localStorage.removeItem('wuxing-social-channels-v1');});await page.reload();await page.waitForSelector('.ch-message');
 check('Four working channel tabs',await page.locator('[data-channel]').count()===4);
 check('Native message text and Q avatars',await page.locator('.ch-message').count()===6&&await page.locator('.ch-avatar img').count()===6);
 check('Own message aligned distinctly',await page.locator('.ch-self').count()===1);
 check('World input fixed in frame',await page.locator('.ch-composer').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('#view-root').getBoundingClientRect().bottom+1));
 const input=page.locator('#ch-compose');
 check('Blank send disabled',await page.locator('.ch-send').isDisabled());await input.fill('    ');check('Whitespace send disabled',await page.locator('.ch-send').isDisabled());
 await input.fill('青云问候');await input.press('Enter');check('Enter sends local message',await page.locator('.ch-delivery').last().textContent()==='✓ 本地发送成功'&&await input.inputValue()==='');
 await input.fill('第一行');await input.press('Shift+Enter');await input.type('第二行');check('Shift Enter preserves newline',(await input.inputValue()).includes('\n'));
 let count=await page.locator('.ch-message').count();await input.dispatchEvent('compositionstart');await input.press('Enter');check('IME composition does not send',await page.locator('.ch-message').count()===count);await input.dispatchEvent('compositionend');
 await input.fill('甲'.repeat(140));check('120 character limit',Array.from(await input.inputValue()).length===120&&await page.locator('.ch-counter').textContent()==='120/120');
 await input.fill('世界草稿');await page.locator('[data-channel=guild]').click();await input.fill('同门草稿');await page.locator('[data-channel=world]').click();check('Independent world draft retained',await input.inputValue()==='世界草稿');await page.locator('[data-channel=guild]').click();check('Independent guild draft retained',await input.inputValue()==='同门草稿');
 await page.locator('[data-channel=team]').click();check('Team empty state',await page.locator('.ch-empty h3').textContent()==='静候道友，结伴同行');await input.fill('队伍初见');await input.press('Enter');check('Team channel accepts own local message',await page.locator('.ch-message').count()===1);
 await page.locator('[data-channel=current]').click();check('Current channel has its own history',await page.locator('.ch-message').count()===2);
 await page.locator('[data-channel=world]').click();await input.fill('');await page.locator('[data-emoji-toggle]').click();await page.locator('[data-emote="[作揖]"]').click();check('Emote inserted in draft',await input.inputValue()==='[作揖]');check('Emote picker closes',await page.locator('#ch-emoji-picker').isHidden());await page.locator('[data-emoji-toggle]').click();await page.keyboard.press('Escape');check('Escape dismisses focused emote picker',await page.locator('#ch-emoji-picker').isHidden());
 await page.locator('[data-share-toggle]').click();await page.locator('[data-share-item=talisman]').click();check('Share item card sends locally',await page.locator('.ch-self [data-card=talisman]').count()===1);
 await page.locator('.ch-self [data-card=talisman]').click();check('Item detail modal',await page.locator('.ch-dialog').isVisible()&&(await page.locator('#ch-dialog-title').textContent())==='太清护身符');await page.keyboard.press('Escape');check('Escape dismisses modal',await page.locator('.ch-dialog').count()===0);
 await page.locator('.ch-message [data-profile=han]').first().click();check('Profile dialog shows Q character',await page.locator('.ch-profile-hero .ch-avatar img').count()===1&&(await page.locator('.ch-dialog').textContent()).includes('竹间客'));await page.locator('.ch-dialog-done').click();
 await page.locator('[data-card=bamboo]').first().click();check('Coordinate detail explicit local boundary',(await page.locator('.ch-dialog').textContent()).includes('尚未连接游戏寻路'));await page.locator('.ch-dialog-close').click();
 await page.evaluate(()=>{const l=document.querySelector('.ch-message-log');l.scrollTop=l.scrollHeight;});await page.locator('.ch-message-log').dispatchEvent('scroll');await page.evaluate(()=>window.ChannelsUI.simulateIncoming('world'));
 check('Incoming at bottom stays at bottom',await page.locator('.ch-message-log').evaluate(e=>e.scrollHeight-e.clientHeight-e.scrollTop<3));
 await page.locator('.ch-message-log').evaluate(e=>e.scrollTop=0);await page.locator('.ch-message-log').dispatchEvent('scroll');await page.evaluate(()=>window.ChannelsUI.simulateIncoming('world'));
 check('Incoming preserves reading position',await page.locator('.ch-message-log').evaluate(e=>e.scrollTop===0));check('New message count visible',(await page.locator('.ch-new-button').textContent()).includes('1条新消息'));await page.locator('.ch-new-button').click();check('Jump to latest clears badge',await page.locator('.ch-new-button').isHidden());
 await page.locator('[data-channel=guild]').click();await page.evaluate(()=>window.ChannelsUI.simulateIncoming('world'));check('Inactive channel unread badge',await page.locator('[data-channel=world] .ch-unread').isVisible());await page.locator('[data-channel=world]').click();check('Entering channel clears unread badge',await page.locator('[data-channel=world] .ch-unread').isHidden());
 await input.fill('<img src=x onerror=alert(1)>');await input.press('Enter');check('User content rendered safely as text',await page.locator('.ch-self .ch-bubble').last().textContent()==='<img src=x onerror=alert(1)>'&&await page.locator('.ch-self .ch-bubble').last().locator('img').count()===0);
 await input.fill('刷新保留');await page.reload();check('Local message and draft persist',await page.locator('#ch-compose').inputValue()==='刷新保留'&&(await page.locator('.ch-self .ch-bubble').last().textContent()).includes('<img'));
 await page.locator('.demo-controls summary').click();const nBefore=await page.locator('.ch-message').count();await page.locator('#simulate-message').click();check('Shell simulated incoming button works',await page.locator('.ch-message').count()===nBefore+1);await page.locator('#reset-demo').click();check('Shell reset restores clean channel state',await page.locator('.ch-message').count()===6&&await page.locator('#ch-compose').inputValue()==='');await page.locator('.demo-controls summary').click();await page.locator('button[data-view=rumor]').click();check('Rumor has explicit read only notice',(await page.locator('.ch-rumor-notice').textContent()).includes('本频道为系统传闻，无法发言'));check('Rumor never has message composer',await page.locator('.ch-composer,textarea,.ch-send').count()===0);
 check('All rumor categories present',await page.locator('[data-rumor-filter]').count()===4);check('Initial rumors populated',await page.locator('.ch-rumor-card').count()===5);
 await page.locator('[data-rumor-filter=beast]').click();check('Beast filter includes pending and ended',await page.locator('.ch-rumor-card').count()===2&&await page.locator('.ch-ended').count()===1);
 await page.locator('[data-rumor-filter=treasure]').click();check('Treasure filter works',await page.locator('.ch-rumor-card').count()===2);
 await page.locator('[data-rumor-filter=victory]').click();check('Victory filter works',await page.locator('.ch-rumor-card').count()===1);
 await page.locator('.ch-rumor-search input').fill('不存在的奇遇');check('Filter empty state',await page.locator('.ch-empty').count()===1&&await page.locator('.ch-rumor-card').count()===0);await page.locator('[data-clear-filter]').click();check('Clear filter restores all',await page.locator('.ch-rumor-card').count()===5&&await page.locator('.ch-rumor-search input').inputValue()==='');
 await page.locator('[data-rumor-detail=r1]').first().click();check('Rumor coordinate detail local only',(await page.locator('.ch-dialog').textContent()).includes('尚未连接游戏寻路'));await page.locator('.ch-dialog-done').click();
 await page.locator('[data-rumor-detail=r1]').first().click();const before=await page.locator('[data-timer=r1]').first().textContent();await page.clock.fastForward(181000);const after=await page.locator('[data-timer=r1]').first().textContent();check('Open rumor detail timer updates',(await page.locator('.ch-dialog-state').textContent()).includes('现身时刻已到'));await page.locator('.ch-dialog-done').click();check('Countdown expires with coherent body',before.includes('即将现身')&&after.includes('现身时刻已到')&&!(await page.locator('[data-rumor=r1]>div.ch-rumor-main>p').textContent()).includes('3分钟后'));
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.ch-rumor-list').evaluate(e=>e.scrollTop=e.scrollHeight);await page.locator('[data-latest]').click();await page.clock.fastForward(1000);check('Back to newest rumor works',await page.locator('.ch-rumor-list').evaluate(e=>e.scrollTop<3));
 // Fresh clean page for visual evidence and per-viewport bounds.
 await page.close();const fresh=await browser.newPage({viewport:{width:2560,height:1080}});fresh.on('pageerror',e=>errors.push(e.message));await fresh.goto(url);await fresh.evaluate(()=>window.ChannelsUI.reset());await fresh.reload();
 for(const [w,h,label] of [[2560,1080,'2560'],[1920,1080,'1920'],[390,844,'390']]){await fresh.setViewportSize({width:w,height:h});for(const mode of ['world','rumor']){await fresh.locator(`button[data-view=${mode}]`).click();await fresh.screenshot({path:shot+`channel-${mode}-${label}.png`,fullPage:w<900});check(`${mode} ${w} has no page horizontal overflow`,await fresh.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));check(`${mode} ${w} inner panel remains bounded`,await fresh.locator('.ch-view').evaluate(e=>e.scrollHeight<=e.clientHeight+2));if(mode==='world'){check(`Composer ${w} fits channel bottom`,await fresh.locator('.ch-composer').evaluate(e=>e.getBoundingClientRect().bottom<=document.querySelector('.ch-view').getBoundingClientRect().bottom+2));}else check(`Rumor ${w} remains read only`,await fresh.locator('textarea').count()===0);}}
 check('No runtime or missing-resource errors',errors.length===0,errors);
 fs.writeFileSync(report,JSON.stringify({status:'passed',scope:'Local browser prototype; no network chat or game client integration',checks,errors,screenshots:['channel-world-2560.png','channel-world-1920.png','channel-world-390.png','channel-rumor-2560.png','channel-rumor-1920.png','channel-rumor-390.png']},null,2));console.log(JSON.stringify({status:'passed',count:checks.length,report}));
 }catch(e){fs.writeFileSync(report,JSON.stringify({status:'failed',error:e.message,checks,errors},null,2));console.error(e);process.exitCode=1;}finally{await browser.close();}
})();
