"use strict";
(() => {
  const STORE = "wuxing-qitan-social-groups-v1";
  // Drafts belong to the module so unmounting a channel cannot discard input.
  let drafts = {};
  const ME = "me";
  const people = {
    me:{name:"青云小道",avatar:"hero-headband.png",online:true,school:"五行道门"},
    lu:{name:"清风剑客",avatar:"24_lu_dongbin.png",online:true,school:"云游剑修"},
    lion:{name:"狮鼓小卫",avatar:"25_lion_drum_guard.png",online:false,school:"护山灵卫"},
    ink:{name:"墨羽",avatar:"27_ink_kite_ranger.png",online:true,school:"符墨行者"},
    he:{name:"清荷",avatar:"29_he_xiangu.png",online:true,school:"灵莲医者"},
    han:{name:"青笛",avatar:"30_han_xiangzi.png",online:false,school:"竹音仙客"}
  };
  const initial = () => ({selectedId:"cloud",groups:[
    {id:"cloud",name:"云游同道",owner:ME,notice:"道友同行，山海有约。今晚戌时在青玉道观相聚，一起游历仙山、赏灯祈福。",members:[ME,"lu","he","han"],pinned:true,notify:true,unread:0,messages:[{from:"he",text:"桂花开了，今晚一起去仙山赏灯吧。",time:"19:26"},{from:"lu",text:"好呀！我先去道观等大家，带上清茶与点心。",time:"19:27"},{from:ME,text:"戌时见，路过荷池的道友可以一同出发。",time:"19:28"},{from:"he",text:"收到，花灯也准备好啦！",time:"19:29"}]},
    {id:"elements",name:"五行论道",owner:"ink",notice:"论道不争高下，交流只问所得。欢迎分享五行修行心得，彼此尊重，和气相待。",members:[ME,"ink","lion","he"],pinned:false,notify:true,unread:8,messages:[{from:"ink",text:"今日的论道小题：山林游历时，大家最喜欢用哪一类法器？",time:"18:15"},{from:"lion",text:"我带鼓，给同行道友助助威。",time:"18:18"},{from:"he",text:"一枝莲，一壶药。治愈伙伴也很有成就感。",time:"18:20"}]},
    {id:"lantern",name:"花灯小队",owner:"he",notice:"提灯赏月，结伴而行。道友可在群中分享花灯见闻，记得等一等走慢的伙伴。",members:[ME,"he","lion","han"],pinned:false,notify:false,unread:2,messages:[{from:"han",text:"我在石桥边发现了兔儿灯，做得十分精巧。",time:"17:42"},{from:"he",text:"先别走远，等大家一起去看看。",time:"17:43"}]}
  ]});
  const escape = value => String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  function load(){try{const value=JSON.parse(localStorage.getItem(STORE));if(value?.version===1&&Array.isArray(value.groups)&&value.groups.every(group=>Array.isArray(group.members)&&Array.isArray(group.messages)&&group.members.every(id=>people[id])))return {selectedId:value.selectedId,groups:value.groups};}catch{}return initial();}
  function save(state){try{localStorage.setItem(STORE,JSON.stringify({version:1,...state}));}catch{}}
  window.GroupsUI = {
    reset(){drafts={};try{localStorage.removeItem(STORE);}catch{}},
    mount(root,helpers){
      let state=load();let query="";let showMobileChat=false;const dialogs=new Set();
      const asset=helpers.asset;const toast=helpers.toast;
      function current(){return state.groups.find(group=>group.id===state.selectedId)||state.groups[0];}
      function avatar(id){const person=people[id];return `<span class="avatar"><img src="${asset(person.avatar)}" alt="${escape(person.name)}的Q版头像"></span>`;}
      function memberMarkup(group){return group.members.map(id=>{const p=people[id];return `<div class="group-member">${avatar(id)}<div class="group-member-copy"><div class="group-member-name">${p.name}${id===group.owner?'<span class="owner-badge">群主</span>':""}</div><div class="group-member-state${p.online?"":" offline"}">${p.online?"在线":"离线"}${id===ME?" · 我":""}</div></div></div>`;}).join("");}
      function infoMarkup(group){return `<aside class="group-info" aria-label="群组信息"><div class="group-info-heading"><h2>群组信息</h2><button type="button" class="text-button" data-action="info">查看详情 ›</button></div><div class="group-name-row"><img src="${asset('round_badge_taiji.png')}" alt=""><div><h3>${escape(group.name)}</h3><p>自定义群组 · 同道相聚</p></div></div><div class="group-announcement"><div class="group-announcement-heading"><h3>群公告</h3>${group.owner===ME?'<button type="button" class="text-button" data-action="edit">编辑</button>':""}</div><p>${escape(group.notice)||"尚未发布群公告。"}</p></div><div class="members-heading"><h3>群组成员</h3><span>${group.members.length} / 50</span></div><div class="group-members">${memberMarkup(group)}</div><div class="group-settings"><label class="group-toggle"><input type="checkbox" data-setting="pinned" ${group.pinned?"checked":""}>置顶群组</label><label class="group-toggle"><input type="checkbox" data-setting="notify" ${group.notify?"checked":""}>消息提醒</label></div><div class="group-info-actions"><button type="button" class="button" data-action="exit">退出群组</button><button type="button" class="button primary" data-action="invite">邀请好友</button></div></aside>`;}
      function listMarkup(){const groups=[...state.groups].sort((a,b)=>Number(b.pinned)-Number(a.pinned)).filter(group=>group.name.includes(query));return groups.length?groups.map(group=>{const last=group.messages[group.messages.length-1];return `<button type="button" class="group-card" data-group-id="${group.id}" aria-pressed="${current()?.id===group.id}" aria-label="${escape(group.name)}${group.unread?'，'+group.unread+'条未读':''}${group.pinned?'，已置顶':''}"><span class="group-badge"><img src="${asset('round_badge_taiji.png')}" alt="">${group.unread?`<span class="group-unread">${group.unread>99?'99+':group.unread}</span>`:""}</span><span class="group-card-title">${escape(group.name)}</span><span class="group-card-preview">${last?escape(people[last.from]?.name+"："+last.text):"群聊已建立，向道友打个招呼吧"}</span><span class="group-card-meta"><span>${group.members.length} 位道友</span><span class="${group.pinned?'pinned':''}">${group.pinned?'◆ 已置顶':group.notify?'消息提醒开启':'提醒已关闭'}</span></span></button>`;}).join(""):`<p class="group-search-empty">${query?'没有找到这个群组':'尚未加入群组'}<br>${query?'试试其他群名':'结识同道，从创建群组开始'}</p>`;}
      function messagesMarkup(group){return `<p class="group-date">今日 · 仙山相聚</p>${group.messages.map(message=>{const person=people[message.from];return `<div class="group-message${message.from===ME?' is-self':''}">${avatar(message.from)}<div class="group-message-content"><div class="group-message-head"><span>${person.name}</span>${message.from===group.owner?'<span class="owner-badge">群主</span>':""}<time>${escape(message.time)}</time></div><div class="group-message-bubble">${escape(message.text)}</div></div></div>`;}).join("")}${group.messages.length?'':'<p class="group-notice">群聊已建立。向同行道友问声好吧。</p>'}`;}
      function render(scrollToBottom=true){
        const group=current();if(group)state.selectedId=group.id;
        root.innerHTML=`<div class="groups-layout${showMobileChat?' is-chat':''}"><aside class="group-sidebar" aria-label="群组列表"><div class="group-list-heading"><h2>自定义群组</h2><span class="group-list-total">${state.groups.length}</span></div><input class="group-search" type="search" aria-label="搜索群组" placeholder="搜索群组" value="${escape(query)}"><div class="group-list">${listMarkup()}</div><div class="group-sidebar-footer"><button type="button" class="button primary" data-action="create">＋ 创建群组</button></div></aside>${group?`<section class="group-chat" aria-label="群聊"><button type="button" class="group-mobile-back" data-action="back">‹ 返回群组</button><header class="group-chat-heading"><div><h2>${escape(group.name)}</h2><p>${group.members.filter(id=>people[id].online).length} 位道友在线 · ${group.members.length} 位成员</p></div><button type="button" class="text-button mobile-info-button" data-action="info">群信息 ›</button></header><div class="group-chat-log" role="log" aria-label="群组消息记录">${messagesMarkup(group)}</div><form class="group-composer"><div class="group-compose-box"><textarea id="group-message-input" maxlength="200" aria-label="群聊消息" placeholder="与同行道友说点什么…">${escape(drafts[group.id]||"")}</textarea><button type="submit" class="button primary" id="group-send" ${drafts[group.id]?.trim()?"":"disabled"}>发送</button></div><div class="group-compose-hints"><button type="button" class="text-button" data-action="emote">表情</button><span class="keyboard-hint">Enter 发送 · Shift + Enter 换行</span><span id="group-input-count">${(drafts[group.id]||"").length} / 200</span></div></form></section>${infoMarkup(group)}`:`<div class="empty-state"><img src="${asset('round_badge_taiji.png')}" alt=""><h2>仙缘待相逢</h2><p>创建一个群组，邀道友共话山海。</p></div>`}</div>`;
        const log=root.querySelector('.group-chat-log');if(log&&scrollToBottom)log.scrollTop=log.scrollHeight;save(state);
      }
      function refreshSidebar(){const list=root.querySelector('.group-list');if(list)list.innerHTML=listMarkup();}
      function dialog(title,body,setup){
        const el=document.createElement('dialog');el.className='dialog group-dialog';el.innerHTML=`<button type="button" class="close-button" aria-label="关闭弹窗" data-close></button><h2>${title}</h2>${body}`;document.body.append(el);dialogs.add(el);
        el.addEventListener('click',event=>{if(event.target.closest('[data-close]'))el.close();if(event.target===el){const r=el.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)el.close();}});
        el.addEventListener('close',()=>{dialogs.delete(el);el.remove();});setup?.(el);el.showModal();return el;
      }
      function closeDialogs(){for(const el of [...dialogs])el.close();}
      function openInfo(){const group=current();if(!group)return;const el=dialog('群组信息',infoMarkup(group));el.addEventListener('click',actions);el.addEventListener('change',settings);}
      function editGroup(){const group=current();if(!group||group.owner!==ME)return toast('只有群主可以编辑群组信息');closeDialogs();dialog('编辑群组信息',`<form id="group-edit-form"><label>群组名称<input name="groupName" type="text" maxlength="12" value="${escape(group.name)}" required></label><label>群公告<textarea name="notice" maxlength="160">${escape(group.notice)}</textarea></label><p class="group-char-count">群名 2–12 个字 · 公告最多 160 字</p><div class="dialog-actions"><button class="button" type="button" data-close>取消</button><button class="button primary" type="submit">保存修改</button></div></form>`,el=>{el.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);const name=form.get('groupName').trim();if(name.length<2)return toast('群名至少需要 2 个字');if(state.groups.some(item=>item.id!==group.id&&item.name===name))return toast('已有同名群组，请换一个名字');group.name=name;group.notice=form.get('notice').trim();el.close();render(false);toast('群组信息已更新');if(innerWidth<=900)openInfo();});});}
      function friendRows(ids){return ids.map(id=>`<label class="invite-row"><input type="checkbox" value="${id}" name="friend"><span>${avatar(id)}</span><span><span class="invite-name">${people[id].name}</span><small>${people[id].school} · ${people[id].online?'在线':'离线'}</small></span></label>`).join('');}
      function invite(){const group=current();if(!group)return;const available=Object.keys(people).filter(id=>!group.members.includes(id));closeDialogs();dialog('邀请好友',`<p>邀请道友加入「${escape(group.name)}」</p><p class="dialog-hint">已在群内的道友不会重复显示，最多 50 位成员。</p><form id="group-invite-form"><div class="group-member-list-dialog">${available.length?friendRows(available):'<p class="group-search-empty">好友都已在群里啦。</p>'}</div><div class="dialog-actions"><button class="button" type="button" data-close>取消</button><button class="button primary" type="submit" id="confirm-invite" disabled>邀请加入</button></div></form>`,el=>{const form=el.querySelector('form');form.addEventListener('change',()=>{const count=form.querySelectorAll('input:checked').length;const button=el.querySelector('#confirm-invite');button.disabled=!count;button.textContent=count?`邀请加入（${count}）`:'邀请加入';});form.addEventListener('submit',event=>{event.preventDefault();const chosen=[...new FormData(form).getAll('friend')].filter(id=>people[id]&&!group.members.includes(id));if(!chosen.length)return;if(group.members.length+chosen.length>50)return toast('群组最多容纳 50 位道友');group.members.push(...chosen);el.close();render(false);toast(`已邀请 ${chosen.length} 位道友加入群组`);});});}
      function create(){closeDialogs();dialog('创建群组',`<form id="group-create-form"><label>群组名称<input name="groupName" type="text" maxlength="12" placeholder="为同道起一个名字" required></label><p class="group-create-hint">群名 2–12 个字，至少邀请一位好友。</p><h3>邀请好友</h3><div class="group-member-list-dialog">${friendRows(Object.keys(people).filter(id=>id!==ME))}</div><div class="dialog-actions"><button class="button" type="button" data-close>取消</button><button class="button primary" type="submit" id="confirm-create" disabled>创建群组</button></div></form>`,el=>{const form=el.querySelector('form');const update=()=>{el.querySelector('#confirm-create').disabled=form.elements.groupName.value.trim().length<2||!form.querySelector('input[type=checkbox]:checked');};form.addEventListener('input',update);form.addEventListener('change',update);form.addEventListener('submit',event=>{event.preventDefault();const name=form.elements.groupName.value.trim();const members=[ME,...new FormData(form).getAll('friend')];if(name.length<2||members.length<2)return;if(state.groups.some(group=>group.name===name))return toast('已有同名群组，请换一个名字');const group={id:'group-'+Date.now(),name,owner:ME,notice:'欢迎道友相聚，愿一路同行，仙缘长在。',members,pinned:false,notify:true,unread:0,messages:[]};state.groups.push(group);state.selectedId=group.id;showMobileChat=innerWidth<=900;el.close();render();toast(`已创建「${name}」`);});});}
      function exitGroup(){const group=current();if(!group)return;closeDialogs();dialog('退出群组',`<p>确定退出「${escape(group.name)}」吗？</p><p class="group-exit-note">退出后，此群组将从你的列表移除，历史聊天将不再显示。</p><div class="dialog-actions"><button class="button" type="button" data-close>再想想</button><button class="button primary" type="button" id="confirm-exit">确认退出</button></div>`,el=>{el.querySelector('#confirm-exit').addEventListener('click',()=>{state.groups=state.groups.filter(item=>item.id!==group.id);state.selectedId=state.groups[0]?.id||null;showMobileChat=false;el.close();render();toast('已退出群组');});});}
      function emote(){dialog('选个心情','<div class="emote-options"><button type="button" class="button" data-emote="【微笑】">微笑</button><button type="button" class="button" data-emote="【抱拳】">抱拳</button><button type="button" class="button" data-emote="【开心】">开心</button></div><p class="dialog-hint">表情作为文字加入输入框，点击发送后才进入群聊。</p>',el=>{el.addEventListener('click',event=>{const button=event.target.closest('[data-emote]');if(!button)return;const group=current();drafts[group.id]=((drafts[group.id]||'')+button.dataset.emote).slice(0,200);el.close();render(false);root.querySelector('#group-message-input').focus();});});}
      function send(){const group=current();if(!group)return;const text=(drafts[group.id]||'').trim();if(!text)return;group.messages.push({from:ME,text:text.slice(0,200),time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})});drafts[group.id]='';render();root.querySelector('#group-message-input').focus();}
      function actions(event){const row=event.target.closest('[data-group-id]');if(row){state.selectedId=row.dataset.groupId;current().unread=0;showMobileChat=innerWidth<=900;render();return;}const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(action==='create')create();if(action==='info')openInfo();if(action==='edit')editGroup();if(action==='invite')invite();if(action==='exit')exitGroup();if(action==='emote')emote();if(action==='back'){showMobileChat=false;render(false);}}
      function settings(event){const input=event.target.closest('[data-setting]');if(!input)return;const group=current();group[input.dataset.setting]=input.checked;save(state);const selected=group.id;render(false);for(const el of dialogs){el.querySelectorAll('[data-setting]').forEach(toggle=>{toggle.checked=Boolean(current()[toggle.dataset.setting]);});}toast(input.dataset.setting==='pinned'?(input.checked?'群组已置顶':'已取消置顶'):(input.checked?'已开启消息提醒':'已关闭消息提醒'));}
      function input(event){if(event.target.matches('.group-search')){query=event.target.value;refreshSidebar();}if(event.target.id==='group-message-input'){const group=current();drafts[group.id]=event.target.value;root.querySelector('#group-send').disabled=!event.target.value.trim();root.querySelector('#group-input-count').textContent=event.target.value.length+' / 200';}}
      function submit(event){if(event.target.matches('.group-composer')){event.preventDefault();send();}}
      function keydown(event){if(event.target.id==='group-message-input'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();send();}}
      root.addEventListener('click',actions);root.addEventListener('change',settings);root.addEventListener('input',input);root.addEventListener('submit',submit);root.addEventListener('keydown',keydown);
      if(current()&&innerWidth>900)current().unread=0;render();
      return ()=>{save(state);closeDialogs();root.removeEventListener('click',actions);root.removeEventListener('change',settings);root.removeEventListener('input',input);root.removeEventListener('submit',submit);root.removeEventListener('keydown',keydown);};
    }
  };
})();
