from pathlib import Path
import json,hashlib
D=Path(r"D:/work/image/qdao_city_tiles_4k_20260916/builtin_q64_production/parallel_20261005/tianyong_festival/r05_c10/r04_c04-v1");r=json.loads((D/"request.json").read_text(encoding="utf-8"));p=json.loads((D/"preparation.json").read_text(encoding="utf-8"))
prompt="Use case: precise-object-edit / outpainting. Render one opaque 1254 by 1254 image at the exact original pixel scale.\nInput image1 is approved STYLE (Daoist Q fantasy guild UI), image2 is adjacent native MAP material/scale reference only, image3 is the exact canonical world-crop LAYOUT guide, and LAST image4 is the only EDIT TARGET. Continue image4 upward into its transparent black missing area. Preserve the known bottom strip in its exact coordinates, with its exact stone-joint positions and leaf shapes. It is a hard boundary constraint; do not shift, reframe or repaint it. Do not copy the composition of image2.\nNew content must follow image3: broad pale stone paving; at the very top-left only the cropped lower edge of an ivory rectangular planter base; a vertical ivory boundary rail at far right; rounded lush green foliage at the lower-right, growing naturally upward from the real existing leaves. Retain those footprints, no extra pillars, roofs or red objects in this crop. Known native stone grid positions override blurred guide grid positions. Extend clean continuous broad stone edges upward from the real bottom. No dangling short joints, cracks, triangular fragments, scratches or grunge. Broad smooth rounded bevels, warm ivory stone, consistent upper-left light and soft natural plant shadows.\nLocked bright clean rounded full Daoist Q polished handpainting, precise native detail. No text, characters, figures, UI, watermark. No resampling, zoom, rotation or geometric warp. Fill the missing region, and return the same-crop complete opaque square."
old=r["payload"]["referenced_image_paths"];refs=[old[2],old[3],old[1],old[0]]
r["payload"]={"prompt":prompt,"referenced_image_paths":refs,"transparent_background":False}
(D/"request.json").write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding="utf-8")
(D/"prompt.txt").write_text(prompt,encoding="utf-8")
p["references"]=[{"file":f,"sha256":hashlib.sha256(Path(f).read_bytes()).hexdigest()} for f in refs]
(D/"preparation.json").write_text(json.dumps(p,ensure_ascii=False,indent=2),encoding="utf-8")
print(json.dumps(r["payload"]))

