import json,hashlib
from pathlib import Path
from PIL import Image
root=Path(r"D:/work/image/designs/creature-combat-20261005/pets/02-jiangling")
frames=[]
for n in range(1,17):
 p=root/"runtime/cast/E"/f"{n:02d}.png"
 im=Image.open(p)
 rec=json.loads(p.with_suffix(".png.generation.json").read_text(encoding="utf-8"))
 a=im.getchannel("A")
 row={"frame":n,"file":str(p.relative_to(root)).replace("\\","/"),"width":im.width,"height":im.height,"mode":im.mode,"sha256":hashlib.sha256(p.read_bytes()).hexdigest(),"alphaExtrema":a.getextrema(),"alphaBounds":a.getbbox(),"substantiveAlphaBounds16":a.point(lambda x:255 if x>=16 else 0).getbbox(),"opaqueBounds128":a.point(lambda x:255 if x>=128 else 0).getbbox(),"shaMatchesRecord":rec["sha256"]==hashlib.sha256(p.read_bytes()).hexdigest(),"promptExists":(root/rec["prompt"]).exists(),"receiptExists":(root/rec["evidence"]["receipt"]).exists(),"allReferenceFilesExist":all(Path(x["path"]).exists() for x in rec["references"]),"durationMs":rec["durationMs"],"actualModel":rec["actualModel"],"actualQuality":rec["actualQuality"]}
 frames.append(row)
report={"action":"cast","direction":"E","frameCount":len(frames),"expectedFrameCount":16,"technicalPassed":all(x["width"]==1024 and x["height"]==1024 and x["mode"]=="RGBA" and x["alphaExtrema"]==(0,255) and x["shaMatchesRecord"] and x["promptExists"] and x["receiptExists"] and x["allReferenceFilesExist"] for x in frames),"distinctSHA256":len(set(x["sha256"] for x in frames)),"all16IndependentlyGenerated":True,"modelDisclosure":"Actual model and quality not disclosed by host, null in every record; config target remains gpt-image-2.5-sunburst/max.","export":"All 16 native 1254-square RGBA generated results uniformly resized full-canvas to 1024, Lanczos; no crop, translation, mirror, interpolation, or per-frame foot alignment.","singleFrameVisualReview":{"reviewedAllFrames":True,"method":"Each generated output and each final exported PNG was displayed and directly inspected with view_image.","observations":["E front-three-quarter consistently faces lower-right; face and chest are visible throughout.","Same anatomical right hand holds the folding fan throughout; left hand stays empty.","Two arms/hands, two legs/feet; no wings or tail. Short black bob and ivory/crimson folded-petal clothing retained.","Three fan bells visible throughout; 07-11 show local bell glow without masking face or torso.","Clear rise/charge, cross-body release and recovery; 12 fan appears narrower in angled/partly closed recovery, 13-16 naturally opens and returns.","10 first candidate glow met right canvas border; one AI repair moved fan/glow inward. Final subject/effects contained.","Natural freehand redraw differences in cloth folds, foot placement and proportions remain; no deterministic pixel alignment was used."],"repairedFrames":[10]},"continuousPlayback":{"status":"pending-parent-unified-preview-review","note":"Parent already creates unified previews; this subtask does not claim continuous playback review."},"clientValidation":"not performed; no client files read or changed","failures":[{"frame":6,"receipt":"receipts/cast-E-06-attempt1-failed.json","resolution":"successful retry"},{"frame":13,"receipt":"receipts/cast-E-13-attempt1-failed.json","resolution":"successful retry"}],"rejectedDrafts":[{"frame":10,"record":"records/cast-E-10-attempt1-rejected.json","workspaceImageRetained":False,"hostImageRetained":"outside permitted write scope, unchanged"}],"frames":frames}
(root/"qa/cast-E-validation.json").write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding="utf-8")
print(json.dumps({k:report[k] for k in ["frameCount","technicalPassed","distinctSHA256"]}))
for x in frames:print(x["frame"],x["substantiveAlphaBounds16"],x["opaqueBounds128"])

