from pathlib import Path
import json, sys
from datetime import datetime, timezone

base = Path(__file__).resolve().parent.parent
gen = base / '08-generation'
phases = {
6: 'LEFT leg early forward swing. Far RIGHT leg planted just behind pelvis. Near LEFT knee and ankle move a little ahead of support ankle, foot low and level. The advancing LEFT thigh must emerge from screen-right near hip and cross naturally in FRONT of the receding RIGHT trouser leg. Short gentle step.',
7: 'LEFT leg mid forward swing. Far RIGHT support boot recedes toward screen-right/up. Near LEFT leg advances toward screen-left/down in front of the far trouser leg; knee slightly flexed, boot still a little above ground. Anatomical connection from near screen-right hip to the advancing boot must be clear. No kicking.',
8: 'LEFT leg terminal forward swing just before heel contact. Near LEFT leg almost extended diagonally screen-left/down, heel very close above ground, toe slightly raised. Far RIGHT leg behind and supporting, heel starts to rise. Near LEFT trouser leg overlaps the far RIGHT leg at the thighs. Do NOT recreate frame01 leg ownership.',
9: 'OPPOSITE CONTACT: near anatomical LEFT leg leads at screen-left/down, heel makes ground contact, toe slightly raised; far anatomical RIGHT leg trails at screen-right/up on toe. This is the opposite anatomical leg configuration to contact01, not the same legs spread again. Near LEFT thigh from screen-right hip diagonally advances IN FRONT OF and occludes far RIGHT thigh, which goes backward behind. Keep shoulders and camera unchanged.',
10: 'LEFT loading response. Near LEFT boot is ahead screen-left/down and now almost flat, LEFT knee mildly flexes under weight; far RIGHT heel lifts as RIGHT toes leave behind screen-right/up. Near LEFT thigh overlaps in FRONT of far RIGHT. Gentle weight transfer after LEFT contact.',
11: 'LEFT mid support and RIGHT toe-off. Near LEFT planted leg carries weight, boot modestly ahead of hips. Far RIGHT leg behind flexes at knee; heel rises and toes just leave ground. RIGHT boot begins its low recovery from behind. True overlap: LEFT in front of RIGHT.',
12: 'RIGHT early recovery. Near LEFT support boot flat under body, far RIGHT knee flexed and boot swings forward from behind toward support ankle, still behind LEFT and low to ground. Stride narrowing. Near LEFT leg in front, far RIGHT leg partly occluded.',
13: 'RIGHT passing. Near LEFT leg vertical firmly planted under pelvis. Far RIGHT boot passes directly behind/beside LEFT ankle, low above ground; far knee mildly flexed. Almost aligned ankles with far RIGHT trouser edge occluded by near LEFT. No high knee.',
14: 'RIGHT early forward swing. Near LEFT support leg recedes a little toward screen-right/up. Far RIGHT boot begins emerging toward screen-left/down from BEHIND near LEFT leg. RIGHT knee slightly flexed, boot low level. Anatomical far RIGHT thigh from screen-left hip leads behind near LEFT; overlap now transitions naturally.',
15: 'RIGHT mid forward swing approaching contact01. Far RIGHT leg advances screen-left/down with knee nearly extending, heel remains a little above ground and toe gently raised. Near LEFT planted leg trails screen-right/up, heel starts rising. Match contact01 far RIGHT-leading hip connection, but shorter pre-contact stride.',
16: 'RIGHT terminal swing immediately before contact01. Far RIGHT leg nearly extended screen-left/down, heel only just above the ground, toe gently raised, a slightly shorter stride than contact01. Near LEFT leg trails screen-right/up, toe grounded and heel lifted. Match frame01 far RIGHT-leading hip connection and body proportions; frame16 to01 must be smooth, no duplicate contact pose.'
}
phases.update({
6: 'Early LEFT swing: anatomical LEFT leg is the screen-RIGHT leg attached under the potion-side hip. Lift this screen-RIGHT boot just off the ground with slightly bent knee and advance it a LITTLE, while screen-LEFT anatomical RIGHT boot remains planted under its own hip. Do not put the screen-left leg forward again. Almost aligned boot depths; short low stride.',
7: 'Mid LEFT swing: anatomical LEFT leg remains attached to screen-RIGHT potion-side hip. Its screen-RIGHT boot advances toward the viewer and a little left, lower in the picture than before, knee mildly bent. Screen-LEFT anatomical RIGHT leg supports while its foot recedes higher. Keep each leg visibly linked to its own hip. No cross-legged pose.',
8: 'Terminal LEFT swing: screen-RIGHT anatomical LEFT boot now clearly leads at lower-right, closer to the bottom edge, with heel slightly above ground and toe gently up. Screen-LEFT anatomical RIGHT boot trails farther away at upper-left on toe. Left knee nearly extends. The near LEFT trouser leg and shin are fully in front of the far RIGHT leg; this must visibly reverse contact01.',
9: 'OPPOSITE LEFT CONTACT: screen-RIGHT anatomical LEFT boot is the LEADING boot closest to bottom edge, ahead of the body toward viewer; the screen-LEFT anatomical RIGHT boot is the TRAILING boot higher in the image, farther away. LEFT heel touches and toe gently raised; far RIGHT rear heel lifts. LEFT thigh starts at potion-side screen-right hip and leads in front; RIGHT thigh starts screen-left and trails behind. This MUST be the opposite to input4 contact01 whose screen-left boot leads. Do not put the screen-left boot closest to bottom again. No crossing legs.',
10: 'LEFT loading: screen-RIGHT anatomical LEFT boot leads closest to bottom and becomes flat, near knee softly bends; screen-LEFT anatomical RIGHT trailing boot is higher and farther away and begins toe-off. Maintain clear near LEFT in front / far RIGHT behind ordering. Do not return screen-left boot to the front.',
11: 'LEFT mid-support: screen-RIGHT anatomical LEFT boot flat supports body, still a little lower/closer than screen-LEFT anatomical RIGHT boot, whose knee flexes and heel lifts behind for recovery. Keep RIGHT leg behind LEFT and its boot higher.',
12: 'RIGHT recovery: screen-RIGHT anatomical LEFT leg straightens in planted support; screen-LEFT anatomical RIGHT knee flexes, boot low airborne behind the left support ankle, almost coming alongside but still a little higher in image. Narrow stride, both hip-to-knee chains visible.',
13: 'RIGHT passing: screen-RIGHT anatomical LEFT leg is vertical planted support. Screen-LEFT anatomical RIGHT boot passes behind support ankle, small low lift and slightly flexed knee, two ankles nearly aligned in depth. RIGHT trouser leg slightly occluded by near LEFT at thighs. No high knee or broad straddle.'
})
frame = int(sys.argv[1]); version = sys.argv[2] if len(sys.argv)>2 else 'v1'
attempt = f'walk-SW-{frame:02d}-{version}'
dest = gen / attempt
dest.mkdir(exist_ok=True)
if (dest / 'request.json').exists(): raise RuntimeError('Never overwrite an attempt')
previous = f'walk-SW-{frame-1:02d}-' + ('v3' if frame==7 else 'v2' if frame==8 else 'v1')
refs = [gen/'idle-SW-v1/raw.png', gen/'references/identity-1024.png', gen/'references/style-1280.jpg', gen/'walk-SW-01-v1/raw.png', gen/previous/'raw.png']
prompt = ('Use case: stylized-concept. Generate ONE newly drawn full-body animation frame of 08 alchemy prodigy boy, native square at least 1024x1024 with real transparent alpha. Input1 locks SW camera and design; input2 original identity; input3 primary painted style/material only (never reproduce its UI); input4 existing contact01 and exact proportions; input5 preceding frame continuity. '+
'Match the same huge amber-eyed round child head, chestnut topknot jade/gold clasp and two gold ribbons, short stout child proportions, orange-gold brocade robe teal panels, ivory puffy trousers, jade-gold boots ivory toe caps. Near anatomical LEFT hand holds green potion at screen-right; far anatomical RIGHT hand holds bronze-jade yin-yang censer at screen-left. Back basket has twin ivory scrolls, herbs, bead pouch and tassel. Never swap hands or mirror character. Fixed slight top-down SOUTHWEST 3/4 front view: face/chest/boots face diagonally down-left. LEFT hip is near at screen-right, RIGHT hip is far at screen-left. Preserve head/body size, camera and all equipment exactly. '+
'Redraw articulated legs, trousers and responsive cloth for this distinct genuine walking phase; no copied/translated/warped pose, no sprite sheet. IMPORTANT: input4 is only a proportion guide, do NOT copy its leg pose. A different foot must lead during the second half of the cycle. Phase %02d of 16: '%frame + phases[frame]+ ' Normal gentle walking, not marching/running/jumping. Both boot uppers visible, no broad soles toward viewer, no split or extra limbs. Quiet carried arms; subtle secondary robe/ribbon movement only. Whole body fits safe margins ~84 percent canvas height, supporting sole baseline y92 percent. Bright clean polished Daoist chibi hand-painted volumes consistent with references. No floor, shadow, glow, text, border, grid or opaque background.\n')
if frame != 9:
    target = gen/('walk-SW-09-v1/raw.png' if 6 <= frame <= 13 else 'walk-SW-01-v1/raw.png')
    previous = {6:'walk-SW-05-v1',7:'walk-SW-06-v4',8:'walk-SW-07-v2'}.get(frame, f'walk-SW-{frame-1:02d}-v1')
    refs = [target, gen/'references/identity-1024.png', gen/'references/style-1280.jpg', gen/'idle-SW-v1/raw.png', gen/previous/'raw.png']
    prompt = ('Use case: identity-preserve. EDIT reference1 into ONE newly drawn full-body walking frame of the SAME alchemy boy, true native transparent square 1254x1254 or >=1024. Reference1 locks camera, proportions, identity, materials and leg anatomy; image2 identity; image3 primary painted style only, never its UI; image4 fixed SW idle camera and same equipment; image5 adjacent phase continuity. Keep head, face, chest, camera, hands and gear matching, redraw BOTH articulated legs and responsive lower robe for this exact different phase. Frame %02d/16: '%frame+phases[frame]+' Preserve anatomical LEFT hand potion on image right and RIGHT hand censer on image left, fixed southwest down-left 3/4 view, short stout chibi limbs and giant round head. Both hips stay fixed: LEFT hip on screen right, RIGHT hip on screen left. Back basket twin ivory scrolls herbs pouch, topknot gold ribbons, orange-gold teal brocade, ivory trousers and jade-gold ivory-toe boots unchanged. No mirror, copying, translating or warping old pose. Complete new authentic drawn pose; no floor, shadow, text, grid, opaque background, split limbs or extra limbs. Normal small gentle step, not running or kicking. Full figure fits with safe margins and consistent source scale; supporting soles near y92 percent.\n')
    if frame == 6:
        prompt += 'Reduce the wide RIGHT-SIDE-foot-leading stride of reference1 to an EARLY SWING: image-right LEFT boot almost beside image-left RIGHT support boot, and still slightly HIGHER (farther from bottom) by ~25 pixels. Image-left support boot FLAT, never show its sole. Image-right knee only slightly flexed, foot just clearing ground.\n'
    if frame == 7:
        prompt += 'Reduce reference1 stride halfway: image-right LEFT boot leads only ~40 pixels lower than image-left support boot, low in forward swing. Do not copy reference1 full stride. Both toes turn a little toward image-left.\n'
    if frame == 14:
        prompt += 'IMPORTANT reduce the wide stride in image1 almost completely: the screen-left far RIGHT boot has only JUST passed the screen-right near LEFT support ankle, both boots nearly same depth, screen-left boot at most 15 pixels lower. Low level airborne foot with top visible, not raised toe or big sole. Screen-right LEFT boot is vertical FLAT support under hip.\n'
    if frame == 15:
        prompt += 'Stride about halfway from passing to contact01: screen-left far RIGHT boot ahead only moderately (about 45 pixels lower than screen-right near LEFT support). Screen-left heel a few pixels above ground, top of boot visible and toe only slightly up. Do not copy the full wide contact01 step.\n'
    if frame == 16:
        prompt += 'Stride just short of contact01. Screen-left far RIGHT boot heel approaches ground, screen-right near LEFT boot trails supporting on toe. Keep boots facing down-left, pose close enough to contact01 for a clean cyclic join but independently drawn preceding phase.\n'
    if frame == 8:
        prompt += 'Slightly shorter stride than reference1 contact09, image-right LEFT boot leads ~75 pixels lower than image-left trailing support boot; heel a few pixels above ground just before contact. Both toes turn southwest slightly image-left.\n'
if frame == 8 and version != 'v1':
    prompt = '''Edit image1 (existing SW contact09) into the immediately preceding gentle walk frame08. Other references are original identity, primary painted style, SW idle camera, and frame07 continuity. Keep EVERYTHING matching: head/face, head-body ratio, shoulders, hands, green potion on screen-right, censer on screen-left, backpack twin scrolls herbs pouch, topknot ribbons, robe and camera. Change just the legs and modest cloth response.
Image-right near LEFT boot remains the lower leading boot, image-left far RIGHT boot remains higher trailing boot. SHORTEN image1's step only slightly. The leading image-right boot is just about to touch heel, at a height only a few pixels before contact, toe pointing FORWARD/SLIGHTLY IMAGE-LEFT exactly like image1, NOT turned out toward image-right. Keep leg short and stout, the boot directly under its own screen-right knee; NO side kick. The trailing image-left boot is planted on toe and provides support. Both boot UPPERS are visible. The foreground boot sole is not exposed broadly. This is a quiet small walking pre-contact, no airborne jump, no exaggerated lift. Do not spread or cross legs. New independently drawn full frame, no copying/warping/translation. Native transparent 1254 square or at least1024, one whole character with all safe margins. No floor, shadows, text, grid, opaque backdrop or extra limbs.\n'''
if frame == 9:
    refs = refs[:3]
    prompt = '''Edit the FIRST reference character into one full-body transparent walking animation keyframe. Keep exactly the first reference's boy identity, head, facial expression, SOUTHWEST down-left three-quarter facing, hand objects, costume, backpack, lighting, material, body size and camera. Reference 2 confirms identity; reference 3 is the main hand-painted material/style standard, do not draw its UI.
CHANGE ONLY THE TWO LEGS AND RESPONSIVE LOWER ROBE into this OPPOSITE STEP: the boot on the RIGHT SIDE OF THE PICTURE (the boy's anatomical LEFT foot, under the green potion hand) takes a FULL STEP FORWARD TOWARD THE VIEWER, and is the lowest and nearest boot. Extend this screen-RIGHT leg down, heel touching ground near y=1180 on a 1254 square. The boot on the LEFT SIDE OF THE PICTURE (anatomical RIGHT foot under the censer) is distinctly BEHIND, shorter in projection, visibly HIGHER at y=1080, rear heel raised and toe planted. This left-side foot must NOT lead. The foreground LEFT trouser leg originates at the screen-right hip and is in front; the background RIGHT thigh at screen-left recedes behind it. Maintain two distinct leg chains, NO leg crossing. Same short chubby child limbs, no lengthening. Both toes still face southwest down-left.
Render ONE complete independently drawn native 1254x1254 or at least 1024 square RGBA with real transparent background. Entire character inside margins. This is an ordinary gentle walking contact pose, not running/kicking/marching. No floor, ground shadow, extra arms/legs, text, grid or sheet. Preserve bronze-jade yin-yang censer in RIGHT hand screen-left, green potion in LEFT hand screen-right, orange-gold teal brocade, ivory trousers, green-gold ivory-toe boots, twin scrolls/herbs/pouch/back basket. Give clear new foreground RIGHT-SIDE BOOT LEADING and background LEFT-SIDE BOOT TRAILING silhouette.\n'''
request = {'tool':'image_gen__imagegen','parameters':{'prompt':prompt,'referenced_image_paths':[p.as_posix() for p in refs]},'slot':f'walk/SW/{frame:02d}','attempt':version,'startedAt':datetime.now(timezone.utc).isoformat(),'configSnapshot':json.loads((base.parents[1]/'config/image-generation.json').read_text(encoding='utf-8-sig')),'submittedParameters':{'model':None,'quality':None}}
(dest/'prompt.txt').write_text(prompt,encoding='utf-8')
(dest/'request.json').write_text(json.dumps(request,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(request,ensure_ascii=False))
