from pathlib import Path
import json,hashlib,datetime
from PIL import Image
import numpy as np
D=Path(__file__).parent;F=D/'final-v1';ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()};read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));save=lambda p,o:Path(p).write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf8')
prep=read(D/'preparation.json');req=read(D/'request.json');J=Image.open(F/'joined.png').convert('RGB');prior=prep['sourceTile'];x=req['tileLocalCropLTRB'][0];width=min(1254,4096-x)
save(F/'visual-review.json',{'reviewedAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'image':ref(F/'joined.png'),'reviewMethod':'Full1254 native image and complete bottom/left return strips inspected at original pixels.','inspectedImages':[ref(p) for p in (F/'qa').glob('*.png')],'localVisualAccepted':True,'formalAccepted':False,'wholeTileAccepted':False,'findings':['Continued ivory diagonal paving and partial carving from canonical reference, with exact existing native edge context as join constraints.','Main diagonal contours continue across the left and lower returns without a cut at the transparency boundary.','No registration, scale change, tone adjustment or blur applied; the new missing region is exactly AI-native pixels.','Core, left return and bottom return must be installed together. Wholecity canonical geometry and neighboring unbuilt tiles remain outside this local acceptance.'],'actualModel':None,'actualQuality':None})
patches=[]
for name,crop,dest,src in [('new-core',[230,0,width,1024],[x+230,1933,x+width,2957],None),('left-return',[54,0,230,1024],[x+54,1933,x+230,2957],prior),('bottom-return',[54,1024,width,1200],[x+54,2957,x+width,3133],prior)]:
 p=F/(name+'.png');J.crop(crop).save(p);patches.append({'name':name,'asset':ref(p),'cropFromJoinedLTRB':crop,'destinationTile':'r07_c10','destinationTileLTRB':dest,'requiredPriorSource':src,'nativeScale':1,'mustApplyTogether':True})
m={'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'appearance':'tianyong_festival','tile':'r07_c10','tileGlobalOrigin':[36864,24576],'nativeScale':1,'windowTileLocalLTRB':req['tileLocalCropLTRB'],'windowGlobalLTRB':req['globalCropLTRB'],'joined':ref(F/'joined.png'),'visualReview':ref(F/'visual-review.json'),'assembly':ref(F/'assembly.json'),'localVisualAccepted':True,'formalAccepted':False,'patches':patches,'sourceCheckpoint':prep['savedCheckpoint'],'requiresPriorManifest':prep['requiresPriorManifest'],'note':'Root review and ROI validation before publication. Preserve all current pixels outside listed rectangles.'};save(F/'manifest.json',m)
save(F/'joined.png.generation.json',{'operation':'native AI outpaint and source-preserving composite','sources':[ref(D/'native.png'),ref(D/'context.png')],'assembly':ref(F/'assembly.json'),'output':ref(F/'joined.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'noUpscale':True,'formalAccepted':False})
fragment=Image.open(prior['file']).convert('RGBA');before=np.array(fragment);assert not np.any(before[1933:2957,x+230:x+width,3]);fragment.paste(J.crop((54,0,width,1200)).convert('RGBA'),(x+54,1933));fragment.save(F/'r07_c10-fragment.png');coverage=int(np.count_nonzero(np.array(fragment)[:,:,3]==255));assert coverage==int(np.count_nonzero(before[:,:,3]==255))+(width-230)*1024
save(F/'r07_c10-fragment.png.generation.json',{'operation':'1:1 native patch composition','sources':[prior,ref(F/'joined.png')],'manifest':ref(F/'manifest.json'),'output':ref(F/'r07_c10-fragment.png'),'actualModel':None,'actualQuality':None,'nativeScale':1,'coveragePixels':coverage,'noUpscale':True,'formalAccepted':False})
save(D.parent/'local-source-checkpoint.json',{'createdAtUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'tile':'r07_c10','fragment':ref(F/'r07_c10-fragment.png'),'nativeScale':1,'coveragePixels':coverage,'formalAccepted':False,'rootPublished':False,'manifest':ref(F/'manifest.json'),'previousManifest':prep['requiresPriorManifest'],'contextJoined':ref(F/'joined.png'),'bottomReturn':patches[2]});print(json.dumps({'manifest':ref(F/'manifest.json'),'joined':ref(F/'joined.png'),'localCoveragePixels':coverage}))
