from prepare_structure import *
ident='night-canopy-focused';src=R/'structure-north-healed.png';focus=[X-115,Y-640,2508,2508]
im=Image.open(src).convert('RGB');k=1254/S;box=[(focus[0]-FRAME[0])*k,(focus[1]-FRAME[1])*k,(focus[0]+focus[2]-FRAME[0])*k,(focus[1]+focus[3]-FRAME[1])*k]
# Native top640 extends beyond the old planning halo; fill it exclusively from real N wherever available.
target=im.transform((2508,2508),Image.Transform.EXTENT,box,Image.Resampling.BICUBIC)
target.paste(Image.open(N).convert('RGB').crop((0,3456,2393,4096)),(115,0))
out=R/'canopy-focus-target.png';image_save(target.resize((1254,1254),Image.Resampling.LANCZOS),out,[src,N],dict(kind='focused planning repair with true native N640; no production pixels',globalFrameXYWH=focus,structureExtentLTRB=box,nativeCropLTRB=[0,3456,2393,4096],nativePasteXY=[115,0],compositePixels=[2508,2508],outputPixels=[1254,1254],coreBoundaryY=320,upperLeftOutsideNative='planning extrapolation; not true NW source'))
prompt='''Use case: structural inpainting. Repair the seam at EXACTLY y320 in Image1. Image1 is the only1254-square edit target and is a focused view of one blue market canopy, timber frame and paving. Its upper320 rows from x58 rightward are actual NORTH-neighbor paint; keep those real contours/stripes in place. Below y320 the planning continuation is wrong by about40 image pixels: the pale fabric stripe jumps sideways and the canopy hem/left edge slightly shifts. Repaint ONLY the continuation below y320 so each real upper stripe edge and blue hem crosses y320 with precisely the same intersection X, width and tangent. The correct upper paint controls the continuation. Move the wrong lower fabric stripe/hem as necessary. Do not keep any horizontal shelf or fabric splice at y320. Do not move the upper native stripes to meet the wrong lower ones. This is one smooth continuous canopy fabric, not stacked roofs or two panels.
Image2 is the completed north context for understanding only, NOT the target crop. Image3 is approved painting style only. Preserve the exact Image1 camera, field of view, square framing and all existing objects. Keep every post in its existing footprint. Maintain the blue-violet evening, clean amber wood, blue fabric and ivory stripe; no change of lighting, object count or scale. Resolve nearby wood attachments consistently. Preserve the target's lower region from y750 down, including cargo/ground, and keep its open walkway. No blur, extra post, extra strip, new roof, grout branch, lantern, text, UI, border, sky, horizon or moon. The important outcome is exact continuous geometry at y320, not merely painting over the seam with a color gradient. Return a full opaque1254x1254 image at identical crop.'''
refs=[out,R/'north-context-preview.png',STYLE];pp=F/(ident+'.prompt.txt');pp.write_text(prompt,encoding='utf8');call=dict(prompt=prompt,referenced_image_paths=[str(p) for p in refs],transparent_background=False)
write(F/(ident+'.call.json'),call);write(F/(ident+'.request.json'),dict(startedAt=now(),configSnapshot=read(REPO/'config/image-generation.json'),prompt=str(pp),promptSha256=sha(pp),references=[ref(p,role=r) for p,r in zip(refs,['exact focused target with actual native N640 above seam','native N context only','approved style only'])],submittedParameters=dict(model=None,quality=None,**call),planningFrameGlobalXYWH=focus,productionPixels=False,nativeDetailCount=0,allowedApplication='Planning only. Select generated lower seam/canopy pixels into existing full structure at exact global coordinates.'))
print(out)
