from prepare_structure import *
req=read(F/'night-structure.request.json');base=read(str(R/'structure.png')+'.generation.json')
base.update(visualReview=dict(at=now(),actuallyViewed=True,verdict='rejected_for_planning_frame',observation='Output follows the separately attached smaller4326 day structure composition instead of exact4736 Image1 expanded frame. No native or guides consumed it.'),requestedPlanningFrameGlobalXYWH=FRAME,actualFrameVerified=False,productionUseForbidden=True)
write(str(R/'structure.png')+'.generation.json',base)
prompt='''Use case: exact-frame image edit. Edit ONLY Image1 into a clean Mid-Autumn evening version, preserving Image1 pixel placement and its ENTIRE square field of view. Image1 is the ONLY target composition. Image2 and Image3 are NORTH NEIGHBOR CONTEXT ONLY, never target compositions. Image4 is STYLE ONLY. Return1254x1254 opaque square.
The crop is fixed:4736 global pixels including320 of surrounding context on each side. The4096 core tile is inset84.73 pixels on all sides of Image1. Keep this inset field of view. Do NOT crop off Image1's outer bands or enlarge its center to fill the square. Render the blurry outer bands in place as the natural continuation of the same map, not a frame or border. Keep every landmark where it appears in Image1: nearest wooden stall post remains near x310,y300..500; cargo cluster remains near x100..660,y450..900; quay right corner remains near x1120,y455; cropped boat rim enters right near y740. No zoom, rotation, scene recentering or shift.
Image1's TOP native-night strip, x84.73..1169.27 and y0..84.73, is authoritative real art. Its contour positions, canopy stripes and colors must remain at those locations and continue downward into the target. At y84.73 the temporary collage line is NOT architecture: eliminate it by coherently continuing the native shapes with their exact widths and slopes. Image2 is the actual full north4096 neighbor, lying ABOVE this crop's core. Image3 is that neighbor's exact bottom1254 native rows. Use these to understand the clipped canopy, wall and single wood rail. Do not paste or repeat either entire context image into Image1. The blue canopy corner at the top center, pale blue quay wall at top right, and true wooden rail/fender must continue as the SAME objects; native endpoints override the day drawing where they disagree. No kink, step, disconnected rail or extra post.
Keep the remaining Image1 layout: existing blue striped canopy and wooden stall at upper-left, grouped cargo and parcels center-left, open stone pavement, diagonal pale quay and rounded caps, existing water fenders, harbor water right/lower-right, existing cropped small boat corner at right. No new object, extra canopy, crate, lantern, decoration, post or masonry branch. Do not complete clipped objects. NO SKY, horizon, moon, stars, landscape, UI, lettering, people, guides, watermark or border.
Image4 supplies the approved rounded Daoist chibi hand-painted finish only: smooth dimensional stone and honey timber, controlled clean brushwork and readable shapes. Match Image2's bright blue-violet evening paving, pale blue wall, cobalt water, blue fabric and golden amber wood/highlights. No dark murk, photorealistic grain, fine noise, blur or sharpening. Preserve EXACT Image1 geometry/crop first; this is a planning image, not native final art.'''
refs=[R/'night-edit-target.png',R/'north-context-preview.png',R/'north-native1254.png',STYLE]
pp=F/'night-frame-corrected.prompt.txt';pp.write_text(prompt,encoding='utf8');call=dict(prompt=prompt,referenced_image_paths=[str(p) for p in refs],transparent_background=False)
write(F/'night-frame-corrected.call.json',call);write(F/'night-frame-corrected.request.json',dict(startedAt=now(),configSnapshot=req['configSnapshot'],prompt=str(pp),promptSha256=sha(pp),references=[ref(p,role=r) for p,r in zip(refs,['ONLY exact-frame edit target with actual N anchor','N full context only','exact N native crop only','approved style only'])],submittedParameters=dict(model=None,quality=None,**call),planningFrameGlobalXYWH=FRAME,productionPixels=False,nativeDetailCount=0,supersedesRejectedOutput=ref(R/'structure.png'),reason='Remove separately attached differently framed day image to prevent automatic crop substitution.'))
print(F/'night-frame-corrected.call.json')
