from prepare_structure import *
ident='night-north-healed';target=R/'structure-frame-corrected.png'
req0=read(F/'night-frame-corrected.request.json')
prompt='''Use case: inpainting, structural repair. Repair the obvious COLLAGE MISMATCH in the UPPER QUARTER of Image1. It currently has a horizontal pasted strip at y85: the canopy's white stripe jumps sideways, wooden parts disconnect, and the upper right wall/pier posts do not continue naturally. REMOVE that artificial horizontal seam by freshly repainting the structure below it, not by keeping the pasted block. This repair MUST visibly change the incorrect geometry around y85. Recoloring alone is insufficient.
Image1 is the ONLY1254x1254 target. Keep this exact4736-global-pixel square framing [48832,40640,4736,4736], no zoom or crop. Its true north-native anchor is x85..1169,y0..85. Preserve those correct native contour entry points at y85. Rebuild the following lower area to meet them naturally, with freedom to adjust incorrect canopy stripe positions, canopy front edge, upper stall frame, existing wall connection and existing pier post feet. Resolve the large mismatches within roughly y85..350 so the surfaces flow into the already-correct lower scene. Do not retain any straight horizontal shelf, pasted band or rectangular color change at y85. The blue/white fabric must be ONE curved canopy with uninterrupted white stripes and continuous hem, not overlapping panels. The north wall must flow into the existing quay edge; its existing wooden rail/post must attach coherently without extra duplicate supports. Keep the native topmost endpoints fixed, allowing wrong lower endpoints to move as needed.
Image2 is the exact bottom1254 rows of the native NORTH neighbor, and Image3 is its full context, both lying ABOVE the target core. Use them to understand that this is the southern continuation of the same blue canopy, quay wall and existing single rail. Never copy their whole scene into the target. Image4 is approved rounded Daoist Q handpainting style only.
Retain Image1's lower cargo cluster, diagonal quay lower wall, rounded caps, water fenders and cropped boat corner at exactly their current positions, especially everything below y400. Preserve clear blue-violet evening paving, amber-lit warm wood, blue fabric, cobalt harbor water and crisp organized rounded brushwork. Keep the smooth paving grid and open walking space. No new objects, crates, roofs, posts, ornaments, lanterns or grout branches. NO SKY, horizon, moon disc, stars, text, people, UI or border. Draw the corrected continuous geometry with AI; do not conceal the mismatch in blur or darkness. Return full opaque1254 square with identical full framing.'''
refs=[target,R/'north-native1254.png',R/'north-context-preview.png',STYLE]
pp=F/(ident+'.prompt.txt');pp.write_text(prompt,encoding='utf-8');call=dict(prompt=prompt,referenced_image_paths=[str(p) for p in refs],transparent_background=False)
write(F/(ident+'.call.json'),call);write(F/(ident+'.request.json'),dict(startedAt=now(),configSnapshot=req0['configSnapshot'],prompt=str(pp),promptSha256=sha(pp),references=[ref(p,role=r) for p,r in zip(refs,['exact-frame edit target with obvious collage defect','native north bottom context','native north full context','approved style'])],submittedParameters=dict(model=None,quality=None,**call),planningFrameGlobalXYWH=FRAME,productionPixels=False,nativeDetailCount=0,repairPurpose='Resolve pasted native anchor geometry, not a final native seam acceptance.'))
write(E/'frame-corrected-review.json',dict(at=now(),file=str(target),sha256=sha(target),actuallyViewed=True,framePreserved=True,verdict='requires_top_anchor_geometry_repair',observation='Expected expanded frame restored, but native canopy stripe and upper right masonry/post still have an explicit straight pasted boundary at y85.'))
print(F/(ident+'.call.json'))
