from pathlib import Path
import importlib.util,json
HERE=Path(__file__).resolve().parent;TOOLS=HERE.parent;ROOT=TOOLS.parents[2]
spec=importlib.util.spec_from_file_location('archive',TOOLS/'archive_generation.py');arc=importlib.util.module_from_spec(spec);spec.loader.exec_module(arc)
prompt='''Use case: precise-object-edit, identity-preserve, background-extraction.
ONE complete native high-resolution transparent SOUTH walking sprite for 06_thunder_caster_boy, S15.
Input 1 is the EDIT TARGET, the clean high-resolution S15. Correct only its overall drawn physical size: its head/face, hands, talisman and full body currently look about five percent smaller than neighboring S14. AI redraw it at the SAME physical character scale as input 3, while keeping its own exact S15 pose. This is native detailed artwork reconstruction, not numerical enlargement or per-body-part resizing.
Input 2 is the AUTHORITATIVE old S15 walking PHASE reference. Preserve this exact phase: SCREEN LEFT leg is swinging forward and lowering, the boot toe is raised and the broad dark sole faces the viewer; SCREEN RIGHT leg supports with a front-facing gold toe band and very little sole exposed. The two boot bottoms are nearly level, unlike input 3 where the swinging leg is raised higher. Keep input 1/2 exact ankle and boot angles, knee bend, relative foot heights, leg separation, pelvis, robe motion, hand positions and forward head direction. Do not replace S15 with the S14 phase. Do not add, merge or disconnect legs.
Input 3 is clean S14 native image for physical SCALE and finish ONLY: match its head, round face, eyes, hands, rectangular talisman and short chibi body dimensions. Ignore its raised-leg phase. Character size is consistent, while S15 retains its own joint pose.
Input 4 is identity/costume ONLY, never its camera, idle pose or obsolete edge contamination. Input 5 is approved PRIMARY STYLE reference: luminous clean rounded hand-painted Daoist chibi finish, delicate clean contours and warm gold material; ignore its UI/background/text/other characters.
Identity lock: cheerful short boy, large brown eyes, happy open mouth, tousled brown hair/ponytail, gold ribbons and turquoise beads, forehead yin-yang medallion; ivory/gold Daoist coat, navy cuff/trousers, gold lightning decoration, yin-yang waist belt, turquoise beads and short tassels, white wraps and black/gold boots. Anatomical RIGHT hand holds pointed lightning staff at SCREEN LEFT. Anatomical LEFT hand holds rectangular gold talisman at SCREEN RIGHT. Preserve all costume/equipment and large-head short-limb proportions. No slimmer/older/taller anatomy, no hand swaps or invented gesture.
Composition: exactly front-facing SOUTH, same mild elevated game camera as input 1. Square native transparent PNG at least 1024 each side, preferably 1254 or larger if supported. Draw the full character approximately 90 percent of native canvas height, hair near5 percent and lowest supporting boot near95 percent, matching input 3 scale. Slightly increase the entire drawn character together, without changing relative head-to-body ratios or boot pose. Keep centered and all hair, ribbons, staff, talisman and boots inside margins. Final exporter is locked to common whole-cell .88 and integer foot anchor y942, no bbox scaling. Desired final silhouette roughly810px high under that fixed export, so solve the size in this generated artwork.
Genuinely transparent alpha, empty outside character and between separate limbs/props. Natural local material-colored antialiasing with no pink, red, magenta, purple or green contaminated fringe copied from old references. Preserve thin gold ornaments/hair. No halo, erosion, glow, particles, shadow, floor, backdrop, fake checkerboard, text or watermark. Return only one complete transparent S15 sprite at highest host-managed visual finish.'''
refs=[TOOLS.parent/'06-generation/S15-edge-final-v1/raw.png',ROOT/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/walk/S/15.png',TOOLS.parent/'06-generation/S14-edge-final-v1/raw.png',ROOT/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
print(json.dumps(arc.prepare('S15-edge-final-v2',prompt,[str(p) for p in refs]),ensure_ascii=False))
