from pathlib import Path
import importlib.util,json
HERE=Path(__file__).resolve().parent;TOOLS=HERE.parent;ROOT=TOOLS.parents[2]
spec=importlib.util.spec_from_file_location('archive',TOOLS/'archive_generation.py');arc=importlib.util.module_from_spec(spec);spec.loader.exec_module(arc)
prompt='''Use case: precise-object-edit, identity-preserve.
Produce ONE complete transparent native S15 walking sprite for 06_thunder_caster_boy.
Input 1 is the CLEAN BODY AND SCALE LOCK, neighboring S14. Preserve its exact canvas framing, top of hair, grounded SCREEN RIGHT boot baseline, head size, face size, face/eye shape, staff size, talisman size, hand size, shoulder/chest width and torso length. These are already correct. Keep its native physical dimensions and all upper-body/costume detail. Do not zoom out, add extra margins, compress the torso, shorten the supporting leg or shrink the character.
Change only the WALKING PHASE from S14 to S15 as specified by input 2 (authoritative original old S15) and input 3 (clean S15 phase). The SCREEN LEFT leg is swinging forward and lowering: lower this knee and boot so the bottom of its dark viewer-facing sole is almost level with the SCREEN RIGHT supporting boot. Keep the SCREEN LEFT toe raised and broad dark sole visible, exactly input2. The SCREEN RIGHT leg remains supporting, its shin connected, its black/gold boot front-facing with minimal sole visible, near the same input1 ground baseline. Maintain input1's torso-to-ground distance and fully connected anatomy; do not shorten the whole figure to lower the swinging leg. Reconstruct pants/robe folds around the changed legs. Preserve original S15 pelvis, separated legs, foot angles and staff/plaque hand positions from inputs2/3. S15 must not remain a high-knee S14 pose.
Input 2 is old S15 POSE ONLY; never copy its low resolution or magenta fringe. Input 3 is the clean S15 POSE/detail reference, but it is too small physically. Use its phase and current identity at input1 physical size, not its compact scale. Input 4 is identity/costume only, ignore its angled camera/idle pose/contaminated edges. Input 5 is approved PRIMARY STYLE reference, use its luminous clean rounded hand-painted Daoist chibi finish and warm gold material; ignore UI/background/text/other characters.
Frontal SOUTH mild elevated game camera, same as input1. Short round chibi boy with big brown eyes, happy open mouth, brown hair/ponytail, gold ribbon/turquoise beads, forehead yin-yang medallion, ivory/gold coat, navy pants/cuffs, gold lightning, waist yin-yang medallion, bead tassels, white leg wraps, black/gold boots. Anatomical RIGHT hand has pointed lightning staff SCREEN LEFT; anatomical LEFT hand has rectangular gold talisman SCREEN RIGHT. No redesigned props, swaps, missing details, extra limbs or fingers.
Match input1's square canvas and figure occupancy exactly. All hair, ribbon, staff, talisman and boots contained. Native transparent PNG ideally1254x1254, at least1024. Highest host-managed clean detail. Genuine alpha outside figure and in gaps. Preserve natural local material-colored antialiasing, no red/magenta/pink/purple/green edge contamination, no glow/halo/shadow/floor/checkerboard/backdrop/text/watermark. Return only one complete transparent S15 sprite.'''
refs=[TOOLS.parent/'06-generation/S14-edge-final-v1/raw.png',ROOT/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/walk/S/15.png',TOOLS.parent/'06-generation/S15-edge-final-v1/raw.png',ROOT/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
print(json.dumps(arc.prepare('S15-edge-final-v4',prompt,[str(p) for p in refs]),ensure_ascii=False))
