from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib
P=Path(__file__).resolve().parent;E=P.parent.parent;C=E/'current'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
bound=[('r08_c09.png','1b527d515088aebb6e1d640db28b0ba8421ac335594b1b5883b029aab404c304'),('r08_c10.png','0e17b643def2ab8c1ece8054e8a8284b177c9885b5c453bf77f43b3fceae166c')]
for file,h in bound:assert sha(C/file)==h
w=Image.open(C/'r08_c09.png').convert('RGB');a=Image.open(C/'r08_c10.png').convert('RGB')
D=P/'south-wide';D.mkdir(exist_ok=True);box=(0,1700,1254,2954);ctx=a.crop(box);ctx.save(D/'context.png')
base=Image.open(P/'south/context.png').convert('RGB');native=Image.open(P/'south/native.png').convert('RGB');old=Image.open(P/'south/joined.png').convert('RGB')
l,t,r,d=375,340,930,650;y,x=np.mgrid[t:d,l:r];z=np.clip(np.minimum.reduce([(x-l)/28,(r-1-x)/10,(y-t)/40,(d-1-y)/40]),0,1);z=z*z*(3-2*z);mask=np.zeros((1254,1254),np.uint8);mask[t:d,l:r]=np.round(z*255).astype(np.uint8)
new=Image.composite(native,base,Image.fromarray(mask));diff=np.any(np.array(new)!=np.array(old),axis=2);ca=np.array(ctx);assert np.array_equal(ca[diff],np.array(old)[diff]);ca[diff]=np.array(new)[diff];joined=Image.fromarray(ca);joined.save(D/'joined.png');Image.fromarray(diff.astype(np.uint8)*255).save(D/'changed-mask.png');assert not diff[:,930:].any()
record={'file':str(D/'joined.png'),'sha256':sha(D/'joined.png'),'operation':'Incremental mechanical extension of existing native south repair alpha support to x930. Only difference versus prior south joined transferred onto current bound crop; no new AI call.','tileLocalWindowLTRB':box,'context':{'file':str(D/'context.png'),'sha256':sha(D/'context.png'),'boundSource':{'file':str(C/'r08_c10.png'),'sha256':sha(C/'r08_c10.png')}},'derivedFrom':[{'file':str(P/'south/native.png'),'sha256':sha(P/'south/native.png'),'generationRecord':str(P/'south/native.png.generation.json')},{'file':str(P/'south/joined.png'),'sha256':sha(P/'south/joined.png'),'generationRecord':str(P/'south/joined.png.generation.json')}],'changedMask':{'file':str(D/'changed-mask.png'),'sha256':sha(D/'changed-mask.png')},'changedPixels':int(diff.sum()),'proof':{'boundCurrentMatchedOnChangedPixels':True,'xAtAndBeyond930Exact':True,'nativePixelScale':1,'resampling':False},'formalAccepted':False,'status':'pending_actual_visual_review'}
joined.crop((790,310,980,670)).save(D/'qa.png');record['qa']={'file':str(D/'qa.png'),'sha256':sha(D/'qa.png'),'cropLTRB':[790,310,980,670],'nativeScale':1,'actuallyViewed':False}
(D/'manifest.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8');(D/'joined.png.generation.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8')
D=P/'west-final';D.mkdir(exist_ok=True);ctx=Image.new('RGB',(1254,1254));ctx.paste(w.crop((3696,850,4096,2104)),(0,0));ctx.paste(a.crop((0,850,854,2104)),(400,0));ctx.save(D/'context.png')
style='D:/work/image/designs/gameplay-ui/04-guild.png'
prompt='Use case: precise-object-edit. Image1 is a precise1254-square map crop; Image2 approved style only. Repair only two hard triangular tone cuts in the left part of this exact image: the upper diagonal cream/gold slab near local x330..405,y65..210, and the brown diagonal bevel near local x240..365,y390..570. These are false cut-and-paste material boundaries; blend their stone/gold surface shading into continuous coherent material while keeping all existing contour lines, white highlights, widths, shadows, slab positions and grey stone texture exactly fixed. Remove the polygonal overlay/color cuts, no new grout or notches. Keep everything else pixel-aligned and unchanged, especially x>=650, the whole bottom half, all image edges, layout/camera/light. Clean bright rounded polished Chinese chibi fantasy stonework matching input. No objects, no text, no UI, no resizing, no reframing. Return the same full1254-square image.'
refs=[{'file':str(D/'context.png'),'sha256':sha(D/'context.png'),'role':'exact composite current c09/c10 crop; edit target'},{'file':style,'sha256':sha(style),'role':'approved style only'}]
sources=[{'file':str(C/f),'sha256':h} for f,h in bound]
req={'payload':{'prompt':prompt,'referenced_image_paths':[r['file'] for r in refs],'transparent_background':False},'configSnapshot':json.loads(Path('D:/work/image/config/image-generation.json').read_text(encoding='utf-8-sig')),'references':refs,'sourceParts':sources,'tileLocalWindowLTRB':[-400,850,854,2104],'allowedMaximumC10X':250}
(D/'request.json').write_text(json.dumps(req,indent=2)+'\n',encoding='utf-8');(D/'context.png.generation.json').write_text(json.dumps({'file':str(D/'context.png'),'sha256':sha(D/'context.png'),'operation':'Exact 1:1 native crop and concat, c09 negative x relative to c10','tileLocalWindowLTRB':req['tileLocalWindowLTRB'],'derivedFrom':sources},indent=2)+'\n',encoding='utf-8')
print(json.dumps({'southWide':record['file'],'southWideSha256':record['sha256'],'southWideChanged':record['changedPixels'],'westContext':str(D/'context.png')}))
