from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib
D=Path(__file__).parent;P=D/'repair-v3';P.mkdir(exist_ok=True);read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
r=np.array(Image.open(D/'repair-v2/native.png').convert('RGBA'));n=np.array(Image.open(D/'native.png').convert('RGBA'));c=np.array(Image.open(D/'context.png').convert('RGBA'));a=np.array(Image.open(D/'repair-v2/target.png').convert('RGBA'))
a[:260]=r[:260];a[380:439,:1139]=c[1080:1139,:1139];a[260:380]=0;a[80:260,495:650]=0;a[:80]=n[700:780]
Image.fromarray(a).save(P/'target.png')
q=read(D/'repair-v2/request.json');q['payload']={'prompt':'''Precise small-gap repair. Return an opaque1254 square at EXACT original coordinates. Image1 has transparent black areas to fill; ALL visible pixels must remain at their current exact positions. The main gap y260..380 joins the upper gold/green cylindrical body to its authoritative lower red oval pendant and stone base. Its lower red oval tip at y445 and all gray stone contours below are immutable. Rebuild only the missing short middle portion with smooth clean connected surfaces; do not move or shorten the pendant and do not invent another ornament. There is a second narrow gap x495..650/y80..260 under the small hanging orange tassel at x560: continue it simply to a rounded red/orange tassel end near y150, then ivory background beneath. NO added gold bead and NO added oval red pendant there. Image2 is only approved Daoist Q rendering style. Image3 is the same lower native map for material only; do not shift its composition into the gap. No change of camera, zoom, crop, native scale, no cracks or lettering.''','referenced_image_paths':[str(P/'target.png'),q['payload']['referenced_image_paths'][2],q['payload']['referenced_image_paths'][3]],'transparent_background':False}
q['operation']='Focused narrow native bridge repair';(P/'request.json').write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf8');(P/'preparation.json').write_text(json.dumps({'references':[ref(z) for z in q['payload']['referenced_image_paths']],'shiftFromMainNative':[0,700],'sources':[ref(D/'native.png'),ref(D/'context.png'),ref(D/'repair-v2/native.png')],'nativeScale':1,'guidePixelsAllowedInFinal':False}),encoding='utf8')
