from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib
D=Path(__file__).parent;P=D/'repair-v2';P.mkdir(exist_ok=True);B=D.parent;T=B.parent
read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
q=read(D/'request.json');cp=read(D/'source-checkpoint-input.json');s=cp['coupledBottom'];src=np.array(Image.open(s['file']).convert('RGBA'));n=np.array(Image.open(D/'native.png').convert('RGBA'));c=np.array(Image.open(D/'context.png').convert('RGBA'))
a=np.zeros((1254,1254,4),dtype='uint8');a[:80]=n[700:780];a[400:439,:1139]=c[1100:1139,:1139];a[439:,:1139]=src[:815,2957:4096]
Image.fromarray(a).save(P/'target.png')
world=[39821,24137,41075,25391];master=Path(read(D/'preparation.json')['master']['file']);Image.open(master).convert('RGB').resize((1254,1254),Image.Resampling.BICUBIC,box=tuple(v*3/32 for v in world)).save(P/'layout-reference-only.png')
q['globalCropLTRB']=world;q['operation']='Focused native repair shifted700pixels south to include ample authoritative source';q['payload']={'prompt':'''Precise masked native repair. ONE opaque1254-square image, same world crop and scale as image1. Image1 contains a REAL EXISTING connected game object. Opaque areas are exact anchors. The upper80 rows show the green roof fringe and top of its cylindrical green/gold body. The LOWER majority y400..1254 is the immutable authoritative object: red oval pendant, cylindrical green/gold base, gray oval rim, cream square plinth, cloud relief and paving. Paint ONLY the transparent horizontal gap between y80 and y400 plus transparent far-right115 tail. Join the existing upper structure to the correct lower body, naturally extending the red hanging pendant upward into its attachment. Do NOT move the red pendant tip, oval gray rim, stone cloud plinth or any lower anchor; do NOT add another cloud plinth in the gap. Existing lower object position and scale are exact. Existing red pendant has its tip around y445, gray oval rim around y470..560; retain these positions. Use image2 identical-world original layout for what belongs in the gap, image3 approved bright rounded Daoist Q style, image4 is the same existing lower map object for material only. Preserve all opaque shapes, no zoom, shift, rotation, resize, new objects, cracks or text. Do not redraw a whole new object, only bridge its missing upper body.''','referenced_image_paths':[str(P/'target.png'),str(P/'layout-reference-only.png'),q['payload']['referenced_image_paths'][2],q['payload']['referenced_image_paths'][3]],'transparent_background':False}
(P/'request.json').write_text(json.dumps(q,ensure_ascii=False,indent=2),encoding='utf8');(P/'preparation.json').write_text(json.dumps({'references':[ref(z) for z in q['payload']['referenced_image_paths']],'shiftFromMainNative':[0,700],'sources':[ref(D/'native.png'),ref(D/'context.png'),s],'master':ref(master),'guidePixelsAllowedInFinal':False,'nativeScale':1,'mask':[0,80,1254,400]}),encoding='utf8')
