from pathlib import Path
from PIL import Image
import json,hashlib,numpy as np
D=Path(__file__).parent;T=D.parents[1];P=D/'repair-left-boundary-v1';P.mkdir(exist_ok=True);read=lambda p:json.loads(Path(p).read_text(encoding='utf-8-sig'));ref=lambda p:{'file':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
root=read(T/'source-checkpoint.json');cs=read(root['candidateSetRecord']['file']);s=next(z for z in cs['candidates'] if z['tile']=='r07_c10');assert ref(s['file'])['sha256']==s['sha256'];src=np.array(Image.open(s['file']).convert('RGBA'));j=np.array(Image.open(D/'final-v4/joined.png').convert('RGBA'))
a=np.zeros((1254,1254,4),dtype='uint8');a[:439,500:]=j[700:1139,:754];a[439:,:500]=src[:815,2457:2957];a[439:,500:]=j[1139:1954,:754]
a[420:970,420:585]=0
Image.fromarray(a).save(P/'target.png')
master=Path(read(D/'preparation.json')['master']['file']);world=[39321,24137,40575,25391];Image.open(master).convert('RGB').resize((1254,1254),Image.Resampling.BICUBIC,box=tuple(v*3/32 for v in world)).save(P/'layout-reference-only.png')
base=read(D/'request.json');req={**base,'globalCropLTRB':world,'operation':'Native AI bridge across left boundary of coupled pedestal repair'};req['payload']={'prompt':'''Precise native restoration of a narrow vertical joining gap. Return ONE1254-square opaque image in the SAME coordinates as image1. Image1 is the actual partial game map with a thin vertical transparent strip x420..585/y420..970, crossing the dark edge of an oval gray rim, a white-gold stone ledge and an inset carved cloud panel. Both visible sides are the fixed authoritative geometry anchors. Newly paint the short missing horizontal continuations between them with smooth continuous contours, bevels and cloud relief. Left and right edges of the strip have slightly different contour heights; make one gentle natural curve between them. Never duplicate rims or paint a second shadow. Keep all opaque stone and object positions untouched. The large transparent upper-left area is also missing map; continue the cylindrical body there according to exact same-world layout image2, but do not change the central join coordinates. Image3 is approved bright clean rounded Daoist Q handpainted style. Image4 is the nearby native map material reference only. No move, scale, camera shift, new objects, grunge, cracks or text.''','referenced_image_paths':[str(P/'target.png'),str(P/'layout-reference-only.png'),base['payload']['referenced_image_paths'][2],base['payload']['referenced_image_paths'][3]],'transparent_background':False}
(P/'request.json').write_text(json.dumps(req,ensure_ascii=False,indent=2),encoding='utf8');(P/'preparation.json').write_text(json.dumps({'references':[ref(z) for z in req['payload']['referenced_image_paths']],'sources':[s,ref(D/'final-v4/joined.png')],'rootCheckpoint':ref(T/'source-checkpoint.json'),'latestBottom':s,'windowGlobalLTRB':world,'nativeScale':1,'guidePixelsAllowedInFinal':False,'maskLTRB':[420,420,585,970],'maskRelativeToMainX':[-80,85],'actualModel':None,'actualQuality':None}),encoding='utf8')
