from pathlib import Path
import json, hashlib, importlib.util, datetime, xml.etree.ElementTree as ET
from PIL import Image, ImageOps
root=Path('E:/work/image/qdao_chibi_roster_v13'); ev=root/'runtime-validation'; run=ev/'contract-run3'; snap=ev/'input-snapshot-run3.json'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
s=json.loads(snap.read_text()); saved=Path(s['project']); formal=Path(s['source']); prior={x['path']:x['sha256'] for x in s['files']}
spec=importlib.util.spec_from_file_location('v13publish',root/'tools/publish.py'); pub=importlib.util.module_from_spec(spec);spec.loader.exec_module(pub)
def current(base):
 return {p.relative_to(base).as_posix():sha(p) for folder in ('Assets','Packages','ProjectSettings') for p in (base/folder).rglob('*') if p.is_file()}
def diffs(now):
 return [{'path':k,'snapshotSha256':prior.get(k),'currentSha256':now.get(k),'relevant':bool(pub.relevant_input(k))} for k in sorted(set(prior)|set(now)) if prior.get(k)!=now.get(k)]
private_diffs=diffs(current(saved)); formal_diffs=diffs(current(formal)); tests=[]
for mode in ('editmode','playmode'):
 f=run/(mode+'.xml');x=ET.parse(f).getroot();tests.append({'platform':mode, 'file':str(f),'sha256':sha(f),**{k:x.attrib.get(k) for k in ('result','total','passed','failed','skipped','start-time','end-time','duration')}})
obsfile=run/'city-captures/runtime-observed-appearances.json';obs=json.loads(obsfile.read_text());lu=next(x for x in obs['appearances'] if x['actualCharacterId']=='24_lu_dongbin')
summary={'status':'code-and-v12-baseline-passed-v13-artwork-incomplete','createdUtc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'generatedNewLuFrames':0,'expectedNewLuFrames':64,'formalV13Activated':(formal/pub.RESOURCE/'appearance.json').exists(),'scope':'New V13 code with real approved V12 assets and synthetic in-memory test fixtures. Offline Tianyong sandbox only; not final V13 artwork/runtime acceptance and not online login validation.','inputSnapshot':{'path':str(snap),'sha256':sha(snap),'fileCount':s['count']},'tests':tests,'runtimeObservation':{'path':str(obsfile),'sha256':sha(obsfile),'snapshotHashMatches':obs['inputSnapshotSha256']==sha(snap),'actualVersions':[{k:x[k] for k in ('actualCharacterId','actualArtworkVersion','actualFrameCount','spriteMatchesDedicatedIdle')} for x in obs['appearances']],'lu':{k:lu[k] for k in ('actualAnimationFramesPerSecond','actualFramesPerUnit','actualCycleDurationMs','actualCycleWorldDistance','controllerMoveSpeed','actualFramesPerDirection','actualFramesMatchResources','movementObserved','actualTravelDistance','actualPathDistance','movementSeconds','observedWalkPoseCount','sampledPosesPerDirection','stoppedIdle')},'deviceMaxTextureSize':obs['deviceMaxTextureSize']},'postRunPrivateInputDifferences':private_diffs,'currentFormalInputDifferences':formal_diffs,'currentFormalRelevantInputsMatch':not any(x['relevant'] for x in formal_diffs),'earlierRuns':[{'run':'contract-run1','EditMode':'297 total, 296 passed, 1 failed: test fixture generated invalid g/h hex SHA values; fixture corrected to valid d/e/f.'},{'run':'contract-run2','EditMode':'Compile failed: Unity 6000.6 obsolete GetInstanceID; changed test observation to GetEntityId. No XML produced.'}],'artworkValidationPending':['64 genuinely generated even frames','S/E 16-frame visual inspection before other six directions','All 145 exports and fixed-head/body QC','Stage real V13 assets, fresh complete input snapshot, repeat both test platforms','Real V13 runtime observation and comparison with this V12 baseline','Formal publication and post-publication verification'],'screenshots':[{'path':str(p),'sha256':sha(p)} for p in sorted((run/'city-captures').glob('*.png'))]}
(ev/'summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding='utf8')
for name in ('approved-roster-runtime','tianyong-24_lu_dongbin'):
 im=Image.open(run/'city-captures'/f'{name}.png').convert('RGB');im.thumbnail((1440,960));im.save(run/'city-captures'/f'{name}-review.jpg',quality=88)
print(json.dumps({'tests':tests,'privateDifferenceCount':len(private_diffs),'privateDifferences':private_diffs,'formalDifferenceCount':len(formal_diffs),'formalRelevantDifferences':[x for x in formal_diffs if x['relevant']],'lu':summary['runtimeObservation']['lu'],'summary':str(ev/'summary.json')},ensure_ascii=False,indent=2))
