"""Persist human/model visual review observations after inspecting current pixels."""
import json,datetime
from pathlib import Path
P=Path(__file__).resolve().parent
index=json.loads((P/'combat-qa/inspected-source-index.json').read_text())
notes={
 'hit/E':[
  '受击起始双靴稳定；右掌托炉、左手握瓶，两袖口各连一手。',
  '后仰开始，膝踝跟随躯干倾斜；两鞋尖保持向E，托炉腕未折断。',
  '前脚抬鞋尖、后脚支撑；原尺寸检查排除反踝；抱炉与握瓶分别连接袖口。',
  '前腿伸出承接后仰，两踝鞋轴仍随腿；双手道具未换手。',
  '重心回收，前脚放平；膝位与靴口一致，腕部与道具接触完整。',
  '恢复站立，两脚均沿E方向透视；握瓶与托炉保持同一解剖归属。'],
 'hit/W':[
  '双脚W向支撑，右掌托炉、近侧左手握瓶；肩袖关系可读。',
  '受击缩膝并抬前脚，靴随小腿旋转，未额外向外拧；炉贴胸。',
  '前脚仍在抬起阶段，鞋尖W向，后脚稳定；收回托炉手未反折。',
  '双脚重新承重，膝踝不分叉；药瓶依然左手握持。',
  '恢复段向前伸炉，肘腕顺直、炉底贴掌；双靴落稳。',
  '恢复站立，肩肘保持合理屈度；左右手道具与前帧一致。'],
 'attack/E':[
  '预备托炉，瓶在胸前，双脚自然前后站位。',
  '右臂收炉蓄势、左手握瓶；原尺寸确认两手两臂，无重复肢体。',
  '继续蓄势，肩肘腕位置延续02；两脚未突然换朝向。',
  '右臂推出、前脚抬鞋尖开始跨步；屈膝及踝轴自然。',
  '前脚承重，后脚抬跟前掌蹬地；托炉掌与右袖衔接。',
  '保持推出后随动，后跟抬起属于蹬地；左手药瓶未消失或换手。',
  '推出后回收开始，肩肘不过伸；双鞋轴保持E向透视。',
  '右肘回收、后腿跟进，靴口包住小腿；两手道具完整。',
  '屈膝回稳，右掌接炉底；前后脚支撑关系清楚。',
  '起身回收，鞋掌无外撇突转；瓶仍由左手握持。',
  '炉降至腰胸间，右肘自然弯曲；双脚平稳。',
  '回到准备姿态，右掌托炉、左手贴胸握瓶；膝踝鞋连续。'],
 'attack/W':[
  '站立预备，右炉左瓶解剖归属正确，双靴W向。',
  '前腿抬起蓄势，鞋尖向W且与踝相连；炉随右肘后收。',
  '前脚鞋尖抬起跨步，原尺寸检查为正常足背屈；两手未换持。',
  '跨步推出炉，前脚承重、后脚开始抬跟；肩肘腕连贯。',
  '前脚稳定，后脚前掌触地蹬出；后脚可见鞋尖属透视而非反踝。',
  '低弓步推出峰值；原尺寸确认后腿—踝—鞋轴自然相接，掌托炉底完整。',
  '推进后随动，后跟仍抬起；炉为右掌托持、左瓶贴近身体。',
  '右肘回收，后脚回稳，脚掌方向未突然换向。',
  '站姿回收阶段，两脚重落稳定；手腕与炉底接触连贯。',
  '右臂收回、左瓶靠胸；左右膝与各自靴口衔接。',
  '准备复位，前臂没有额外关节或重叠手；靴轴保持W向。',
  '恢复准备姿态，双脚稳立、道具归属与01一致。'],
 'cast/E':[
  '起始托炉与握瓶均明确，两腿直立自然。',
  '向前送炉，肩肘腕顺势展开，双脚仍稳立。',
  '下蹲蓄力，原尺寸确认只有两脚；近鞋圆头与远鞋侧面为视角差，非额外鞋。',
  '蓄力后小幅起身，双腿屈膝，靴轴与膝踝连接正常。',
  '托炉右臂开始上抬，左瓶在胸前；脚掌继续承重。',
  '右臂举炉，原尺寸检查腕部自然仰掌；左手/瓶局部被右袖遮挡，未丢失。',
  '举炉最高点，原尺寸检查肩—肘—腕衔接；左瓶露出瓶颈及握持部位。',
  '右臂开始向前送出，膝盖弯曲承力；脚趾朝E。',
  '前送并下蹲到释放段，前后膝踝一致，无外翻鞋底。',
  '释放随动，托炉手从袖口正常伸出；左瓶继续在胸前。',
  '起身收臂，双脚仍支撑，鞋方向延续10。',
  '收回炉到胸高，肘部自然弯曲；握瓶手可见。',
  '回收低点，炉底掌接触完整、没有第三手；双靴稳立。',
  '恢复准备，袖口—腕—掌相接；瓶的解剖左手归属不变。',
  '收势小幅调整，膝与靴口自然；两手道具完整。',
  '最终准备姿态，右炉左瓶不换，双靴保持原E向透视。'],
 'cast/W':[
  '准备站立，远侧右掌托炉、近侧左手握瓶。',
  '开始俯身蓄力，肩肘自然收合，双膝屈曲方向一致。',
  '双腿下蹲、鞋掌平稳；右托炉腕没有反折。',
  '下蹲最低附近，膝踝与靴口相接，两脚没有重叠增生。',
  '起身准备举炉，两手道具归属延续。',
  '右臂上抬初段，肘腕自然、炉底保持托掌接触。',
  '继续上抬，双腿平稳承重，左瓶仍在胸前。',
  '举炉接近头高，右袖口沿前臂落下，腕掌连续。',
  '举炉高位，原尺寸确认右掌仰托炉底，肩肘自然上举；左手握瓶。',
  '举炉峰值，原尺寸确认没有额外手臂或反腕；双脚承重，鞋尖朝W。',
  '高位回落，原尺寸确认腕掌结构延续10、左瓶仍握牢。',
  '炉回到头胸高度，右肘收回；两靴平稳。',
  '炉降到胸前，肩肘自然放松，两手道具无交换。',
  '准备复位，托炉掌与袖口连接清楚，双膝踝无扭转。',
  '收势小幅调整，左右手握持持续；靴方向稳定。',
  '最终准备姿态，右炉左瓶及自然两脚站位保持。']
}
reviewed=[]
for row in index:
    group='/'.join(row['slot'].split('/')[:2]); n=int(row['slot'].split('/')[2])
    row.update({'decision':'retain','staticReviewed':True,'feetLegs':'pass_current_pose','shoulderElbowWrist':'pass_visible_structure','gripOwnership':'anatomical_right_cauldron_left_green_bottle','observation':notes[group][n-1]})
    reviewed.append(row)
report={
 'schemaVersion':1,'reviewedAt':datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=-4))).isoformat(),
 'scope':'08炼丹童子已有combat六组68帧；不新增方向、不改变时长、不复制帧',
 'status':'offline_static_review_complete_no_confirmed_limb_repair',
 'selectedReplacements':0,'retainedFrames':68,'failedGroups':[],'problemFrames':[],
 'method':['实际查看当前六组preview联系表，逐帧观察原有姿态及前后联系。','从当前runtime实时生成10张手部/腿脚分区放大板并逐槽查看，固定画布裁切仅作审阅，未编辑任何runtime。','另查看11张1024原图：cast/E03、06、07；cast/W09、10、11；attack/E02、03；attack/W03、06；hit/E03。'],
 'referenceEvidence':{
  'actuallyViewed':['C:/Users/luyua/AppData/Local/Temp/codex-clipboard-7cc4bf22-e4cf-4c35-8ac6-a37fd85f4037.png','D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/reference-motion-review-20261004/character-detail.jpg','D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/reference-motion-review-20261004/video-contact.jpg'],
  'use':'只提取运动平面、关节与鞋轴衔接、连续性和接地。角色身份及项目画风保持。',
  'limitation':'视频角色小且有名字/特效遮挡，抽样不能证明其每帧鞋掌角度；此次combat审阅为当前实图逐帧离线审阅，不声称连续游戏运行测量。'},
 'findings':[
  '本次未发现足以判定需重绘的膝踝脱节、反折手腕、重复肢体、道具换手或悬空握持。保留已经正确的68张。',
  'cast/E03在小联系表中容易误看成额外鞋尖；1024原图和放大腿脚板均确认只有两只靴，未为了缩略误判重画。',
  'attack/W04-07及attack/E05-08后跟抬起是自然蹬地；hit/E03、attack/W03前脚鞋尖抬起是有效屈踝；不把正常战斗屈膝、抬跟套成跑步错误。',
  'cast/E06-07的瓶和左手部分被右袖遮挡，原尺寸仍可见瓶颈/握持；不把正常遮挡判成缺手。',
  '所有槽SHA互不相同。本次没有发起AI编辑，因此没有新增生图或生成版本需要记载。'],
 'limitations':['较小的绘画轮廓/衣摆/道具体积差异仍存在；本审阅只判定可见肢体和握持是否有确定错误。','未进行客户端世界位移、滑步、事件帧或实机战斗测试；staticReviewed不等于dynamicAccepted。'],
 'browserPreviewChecked':False,'dynamicAccepted':False,'clientValidated':False,
 'slots':reviewed,
 'qaImages':'provenance/limbs-20261004/combat-qa/*.jpg，可在根任务确认审阅完成后按用户素材保留策略清理；保留本报告、脚本和source-index文字。'
}
(P/'combat-selection.json').write_text('{}\n',encoding='utf-8')
(P/'combat-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'reviewed':len(reviewed),'replacements':0,'uniqueSHA':len({r['sha256'] for r in reviewed})}))
