from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
H=Path(__file__).resolve().parent;R=H.parents[1];O=H/'candidate/06_thunder_caster_boy';G=R/'06-generation'
def read(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):Path(p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
selected={1:'NE01-walk-v1',2:'NE02-final-v2',3:'NE03-final-v2',4:'NE04-final-v2',5:'NE05-final-v2',6:'NE06-final-v3',7:'NE07-final-v4',8:'NE08-final-v3',9:'NE09-final-v4',10:'NE10-final-v3',11:'NE11-final-v3',12:'NE12-final-v3',13:'NE13-walk-v1',14:'NE06-final-v2',15:'NE07-final-v2',16:'NE16-final-v3'}
phases=['right-contact','right-loading','left-toe-off','left-passing','left-high-swing','left-extending','left-lowering','left-precontact','left-contact','left-loading','right-toe-off','right-passing','right-high-swing','right-extending','right-lowering','right-precontact']
files=[]
for n,b in selected.items():
 d=G/b;path=O/f'walk/NE/{n:02d}.png';source=read(d/'raw.png.generation.json');receipt=read(d/'generation-receipt.json')
 files.append({'frame':n,'phase':phases[n-1],'final_file':str(path),'final_sha256':sha(path),'size':[1024,1024],'selected_source_batch':b,'selection_note':'Source requested frame06 but returned right-leg extension; independently selected as frame14.' if n==14 else 'Source requested frame07 but returned right-leg precontact; independently selected as frame15.' if n==15 else 'Visual pose selected for requested frame.','derivedFrom':{'historical_path':str(d/'raw.png'),'sha256':source['sha256'],'native_size':[source['width'],source['height']],'generation_record':source,'exact_prompt':(d/'prompt.txt').read_text(encoding='utf-8-sig'),'receipt':receipt,'tool_result':read(d/'tool-result.json')},'operation':{'profile':'native-alpha','whole_cell_common_scale':0.88,'resample':'LANCZOS','foot_anchor':[512,942],'per_subject_bbox_scaling':False,'chroma_key':False,'despill':False,'synthesized_frame':False},'actualModel':None,'actualQuality':None,'unverifiedReason':'Host-managed built-in tool did not disclose model or quality. Config targets are not actual return evidence.'})
rejects=[]
for b,reason in [('NE05-walk-v1','Right high swing, incorrect for desired left high swing05;13 retains separate matching right high swing.'),('NE09-walk-v1','Right-leading instead of left-leading contact.'),('NE09-final-v2','Returned right-leading step instead of left contact.'),('NE09-final-v3','Correct legs but oversized figure, replaced by reframedv4.'),('NE07-final-v3','Returned right-leading opposite phase; not selected.')]:
 d=G/b
 if d.exists() and (d/'raw.png').exists():rejects.append({'batch':b,'reason':reason,'historical_raw_sha256':sha(d/'raw.png'),'exact_prompt':(d/'prompt.txt').read_text(encoding='utf-8-sig'),'generation_record':read(d/'raw.png.generation.json'),'receipt':read(d/'generation-receipt.json'),'tool_result':read(d/'tool-result.json')})
write(H/'NE_DELIVERY.json',{'schema':'06-ne-direction-delivery-v1','createdAt':datetime.now(timezone.utc).isoformat(),'character':'06_thunder_caster_boy','direction':'NE','walk_frames':16,'selected_new_this_subtask':14,'selected_prior_raw':2,'builtin_generation_calls_this_subtask':17,'paid_api_calls':0,'final_files':files,'rejected_versions':rejects,'current_images_may_be_deleted_after_root_assembly':True,'textual_provenance_self_contained':True,'no_unity_or_game_client_verification':True})
art=read(H/'review/artifacts.json');review={'status':'passed_offline_direction_review','scope':'NE only, root must bind combined8-direction package separately','reviewedAt':datetime.now(timezone.utc).isoformat(),'reviewed_manifest_sha256':sha(O/'manifest.json'),'reviewed_qc_sha256':sha(O/'qc.json'),'reviewed_artifacts':{x['path']:x['sha256'] for x in art['files']},'checks':{'sixteen_distinct_true_generated_frames':True,'anatomical_contacts_01_09':True,'alternating_support_and_swing':True,'staff_right_plaque_left':True,'normal_size_dark_light':True,'enlarged_native_raw_and_seam':True,'seam_15_16_01_02':True,'transparent_edges_no_visible_residue':True,'output_no_alpha_boundary_pixels':True,'gifs_16_by_30ms':True,'browser_play_pause_step_zoom':True},'notes':['01 right-leading contact,05 left high swing,09 left-leading contact,13 right high swing; two independent leg cycles.', 'All generated raw seen at native1254 before export; final contacts and enlarged seam inspected on dark/light backgrounds.', 'Browser rendered normal384px and enlarged768px mode; stepped15,16,01,02 and observed changing30ms playback states. GIF encoded timing is exact; browser scheduling is display-dependent.', 'Figure secondary motion varies mildly; numeric body-scale CV0.024811<0.08, all support anchors normalized to [512,942].'], 'numeric_verification':'review/numeric-verification.json','gif_artifacts':art['gifs'],'unity_client_verified':False,'formal_runtime_publication':False}
write(H/'review/visual-review.json',review)
print(json.dumps({'delivery':str(H/'NE_DELIVERY.json'),'selected':len(files),'rejected':len(rejects),'manifest_sha256':review['reviewed_manifest_sha256']},indent=2))
