from pathlib import Path
import importlib.util,json
HERE=Path(__file__).resolve().parent;TOOLS=HERE.parent;REC=TOOLS.parent;ROOT=REC.parents[1]
s=importlib.util.spec_from_file_location('arc',TOOLS/'archive_generation.py');arc=importlib.util.module_from_spec(s);s.loader.exec_module(arc)
todo={
7:('NE06-final-v3','Only change the screen-LEFT boot and its connected shin: extend the shin a little forward away toward upper-right and lower its boot toward the floor, but still suspended at y87%. Rotate this small left boot so its top/side is visible instead of its brown bottom. Keep screen-RIGHT boot lower at y93%, right heel raised showing brown sole. Do not swap the screen sides. Right boot remains the trailing boot nearest viewer. Keep the torso and head scale in image1.'),
8:('NE09-final-v4','Make one tiny gait instant before image1: the screen-LEFT small flat boot lifts a little off its current floor at y88%, toe angled slightly upward, shin a little less extended. The screen-RIGHT boot remains back toward viewer at y93%, brown sole still visible. The right boot must stay LOWER and RIGHT of the left boot. Keep same left-forward/right-back step. Do not turn this into the opposite step. Slightly different cloth folds responding to the instant before contact.'),
10:('NE09-final-v4','Make one instant after image1: the screen-LEFT small flat boot remains forward and planted, its knee bends slightly under the weight. The screen-RIGHT rear boot tilts to raise its heel slightly more and show more brown sole while toe stays at y93%. Right boot stays LOWER and RIGHT of left boot. Keep left-forward/right-back step. Very small downward settling of torso and related coat folds, not a neutral stance or opposite step.'),
11:('NE09-final-v4','Transfer the weight to the screen-LEFT boot: its leg straightens nearly vertical, boot planted flat at y93%. Bend the screen-RIGHT knee so its heel and toe lift off the ground behind to y89%, brown sole remains visible on RIGHT. Screen-RIGHT boot is now higher than left planted boot, at toe-off moving toward hip. Do not switch hands or camera or mirror. Two connected distinct legs; right airborne and left planted.'),
12:('NE13-walk-v1','Make the moment just before image1 right high swing: Keep screen-LEFT boot lowest and grounded at y93%. Screen-RIGHT knee is bent forward in the air, its boot hangs at y88%, slightly LOWER and farther back than in image1, clearly not touching ground. Left boot remains planted, right boot remains raised. A lower knee lift than reference1. Newly articulate leg joints and natural coat drape for this passing pose.'),
16:('NE01-walk-v1','Make the last instant before image1 right contact. Keep screen-LEFT boot trailing closest to viewer with brown sole visible and toe reaches y93%. The screen-RIGHT boot is forward in the distance with its heel barely above the floor at y92%, toe a little raised, knee a little less extended than image1. Keep right-forward/left-back step, never opposite. Preserve upper body shape and cloth shapes close to image1 while drawing a unique pre-contact pose so16 to01 is smooth.')}
out={}
for n,(batch,action) in todo.items():
 prompt=f'''Edit image1 into one new genuine walking sprite for06_thunder_caster_boy, NE direction, frame{n:02d}/16. Preserve its exact identity, high quality rendering, costume, big head/chibi proportions, rear-right camera with back visible and tiny cheek visible, staff in RIGHT hand on screen-right, rectangular talisman in LEFT hand on screen-left. Image2 immutable identity, image3 exact NE direction, image4 primary approved polished handpainted Daoist chibi style. Retain warm gold/ivory robe, navy trousers, brown ponytail, turquoise details.
Exact new leg articulation: {action}
NO opposite-leg replacement: obey the stated screen-space boot positions. Keep all other design unchanged apart from gentle walking secondary motion. Two distinct legs anatomically connected. No copying, mirroring, interpolating or warping an earlier image; redraw the new articulated pose.
Strict framing: complete figure 86% of square height with7% transparent margin above tallest hair and7% below lowest boot, head top at7%, floor at93%. Match canvas-relative head size of image1; no enlargement. Every hair, boot, ribbon, staff and plaque fully contained. Exactly one native square PNG at least1024x1024, true transparency, no checkerboard, background, ground plane/shadow, glow, particles, colored fringe, label, watermark, grid or sheet. Highest available final quality.'''
 refs=[REC/'06-generation'/batch/'raw.png',ROOT/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',ROOT/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/idle/NE.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
 out[n]=arc.prepare(f'NE{n:02d}-final-v3',prompt,refs)
print(json.dumps(out,ensure_ascii=False))
