from pathlib import Path
import importlib.util, json, re
HERE=Path(__file__).resolve().parent;TOOLS=HERE.parent;REC=TOOLS.parent;ROOT=REC.parents[1]
s=importlib.util.spec_from_file_location('archive06',TOOLS/'archive_generation.py');archive=importlib.util.module_from_spec(s);s.loader.exec_module(archive)
phases={
2:('NE01-walk-v1','The RIGHT boot on screen-right stays forward and planted, its knee flexes slightly under weight. LEFT boot on screen-left trails behind with lifted heel and toes still at ground, a little closer to hip than the target image. Both feet separate. Soft down position.'),
3:('NE01-walk-v1','The RIGHT boot on screen-right is planted at y94%. LEFT boot on screen-left has just lifted off the ground, its toe curled and knee bent, boot bottom at y91% with a real air gap. LEFT thigh begins to move forward. No tiptoe contact for left boot.'),
4:('NE05-final-v2','LEFT far knee swings forward beside the planted RIGHT leg, LEFT boot tucked higher but not yet at its maximum, boot bottom y87%, clearly off ground. The RIGHT boot on screen-right remains the lowest grounded boot at y94%. Distinct from target05: left boot is lower and slightly farther left; coat folds follow its passing motion.'),
6:('NE05-final-v2','From target05 high LEFT swing, begin extending the LEFT shin downward and forward into distance. LEFT boot on screen-left must be at y86%, smaller in perspective, its sole rotates away so its toe faces upper-right. RIGHT near boot on screen-right reaches y94%, heel begins rising but toes are planted. Left foot remains airborne. Do not lift right leg.'),
7:('NE09-final-v4','Approach target09 contact but LEFT foot has not touched: screen-LEFT boot heel is at y87%, leg stretching forward away to upper-right and visibly airborne. RIGHT trailing boot screen-right at y94% is tiptoe supporting with heel raised and partial brown sole visible. Slightly shorter stride than target09.'),
8:('NE09-final-v4','One instant BEFORE target09. LEFT small forward boot screen-left is just a hair above its future floor y89%, heel leading, toe raised a little. RIGHT screen-right trailing boot extends back toward viewer, toe at y94%, heel raised and brown sole toward viewer. Distinct pose with left knee just less extended and coat tails modestly delayed.'),
10:('NE09-final-v4','One instant AFTER target09. LEFT forward small screen-left boot now rolls flat accepting weight; its knee softly bends. RIGHT screen-right rear heel lifts higher with toe still at ground. The right brown sole remains visible on screen-right. Slightly compressed supporting hip and natural delayed cloth, no side swap.'),
11:('NE09-final-v4','LEFT boot on screen-left is firmly planted under forward body, final floor y94%. RIGHT boot on screen-right has just left the ground behind, heel and toes lifted, knee bends; its bottom rises to y91% with a real air gap. Right sole visible but foot drawing upward, moving toward hip. This is right toe-off.'),
12:('NE13-walk-v1','RIGHT near knee on screen-right bends and swings forward beside supporting LEFT leg. RIGHT boot fully airborne bottom y88%, not yet as high as target13. LEFT screen-left boot firmly planted at y94%, with supporting knee nearly straight. Keep two separate boot shapes, do not lift left foot.'),
14:('NE13-walk-v1','RIGHT near shin begins unfolding from high swing, RIGHT boot screen-right extends forward into distance and descends to y88%. LEFT screen-left supporting heel starts lifting with toes at y94%, some brown sole visible. RIGHT still airborne, two separate legs. Less knee bend than target13.'),
15:('NE01-walk-v1','Approach target01: RIGHT near boot screen-right extends forward away toward upper-right but its heel is still above ground at y90%, no contact. LEFT boot screen-left trails behind on toe at y94%, heel lifted exposing brown sole. Right knee relaxed, not fully extended yet. Distinct articulation from target01.'),
16:('NE01-walk-v1','Last instant BEFORE target01. RIGHT forward screen-right heel is a hair above future contact at y93%, toe slightly raised; LEFT screen-left trailing toe is at y94%, heel up showing brown sole. Just a little less right extension than target01. Hair and coat secondary motion return close to target01 with subtle differences. Smooth16 to01 transition, do not duplicate target01.'),
}
out={}
for n,(batch,screen) in phases.items():
 original=(REC/'work-N-NE/plans/NE'/f'{n:02d}.prompt.txt').read_text(encoding='utf-8-sig')
 phase=next(x for x in original.splitlines() if x.startswith('Exact leg phase'))
 prompt=f'''Use case: identity-preserve / newly articulated game sprite. Draw one complete NE walk frame{n:02d} of16 for06_thunder_caster_boy. Image1 is the edit target and matching render/scale reference; change the articulated legs, appropriate coat folds and gentle secondary walking motion to the new phase below. Keep the rear-right NE camera, head and shoulders and original chibi anatomy. No copy/flip/interpolation/warping to fake a new frame. One newly drawn native single frame.
Image2 is immutable identity, image3 the exact NE direction and costume construction, image4 the primary approved style reference from designs. Match clean luminous rounded hand-painted Daoist chibi finish, soft volume, warm gold/ivory robe, navy pants, brown hair with gold ribbon, turquoise ornaments, rear gold lightning motif. Staff always in anatomical RIGHT hand on screen-right, rectangular yin-yang plaque in LEFT hand on screen-left. Never swap hands or equipment.
{phase}
CRITICAL VISIBLE LEG BLOCKING: {screen}
Walking away to upper-right, slightly elevated game camera, back with tiny right cheek visible. Keep the exact overall scale of image1, never enlarge the head or body. Full figure tallest hair6-7% and lowest support sole93-94% of square canvas, generous transparent margin all around, approximately86-88% subject height. Upright torso with very subtle bob, restrained props. Natural small cloth/hair differences only.
Native square PNG at least1024x1024, preferably1536 if available. Truly transparent alpha beyond the silhouette, clean fine antialiasing, no color fringe, no painted checkerboard, no ground plane/shadow, no halo, glow or effects. No text, border, watermark, grid or collage. Highest available polished finish. Two legs, two distinct boots, full staff, complete ribbons, no crop.'''
 refs=[REC/'06-generation'/batch/'raw.png',ROOT/'qdao_original_roster_v13/references/06_thunder_caster_boy/original-identity-1024.png',ROOT/'qdao_original_roster_v13/candidate/06_thunder_caster_boy/idle/NE.png',ROOT/'designs/jubaozhai-ui/02-characters.png']
 out[n]=archive.prepare(f'NE{n:02d}-final-v2',prompt,refs)
print(json.dumps(out,ensure_ascii=False))
