from pathlib import Path
from prepare_frame import prepare

GEN=Path(__file__).resolve().parent.parent/'06-generation'
groups=[([2,3,4],'SW01-single-v1','SW05-single-v1','RIGHT far leg supports on picture LEFT, LEFT near leg lifts from picture RIGHT behind and swings toward the body. Keep left and right thighs unambiguously separate, no crossing. Image 4 is right contact, image 5 left-swing passing.'),([6,7,8],'SW05-single-v1','SW09-single-v2','RIGHT far leg stays the rear supporting leg. LEFT near thigh swings forward from picture RIGHT hip to lower LEFT foreground, progressively extending the left knee and lowering its boot. Image 4 is left swing, image 5 left forward contact. Distinct phase between these actual endpoints.'),([10,11,12],'SW09-single-v2','SW13-single-v1','LEFT near leg is weight-bearing and eventually picture RIGHT support; RIGHT far leg lifts from behind picture RIGHT and swings toward picture LEFT. Image 4 left contact has near left thigh crossing in FRONT of far right leg; image 5 is lifted RIGHT far foot on picture LEFT with LEFT near boot planted picture RIGHT. Preserve correct leg ownership.'),([14,15,16],'SW13-single-v1','SW01-single-v1','LEFT near leg supports, RIGHT far leg swings forward toward lower LEFT. Image 4 right swing passing has RIGHT far boot lifted on picture LEFT with LEFT near boot planted picture RIGHT; image 5 is right forward contact. Extend and lower RIGHT far boot progressively toward image 5, keeping LEFT near foot as ground support and correct leg ownership.')]
for frames,a,b,detail in groups:
    for n in frames:
        prepare('SW',n,1,[GEN/a/'raw.png',GEN/b/'raw.png'],f'Image 4 and 5 are actual keyframes bounding this exact three-frame transition. {detail} This is frame {n:02d}; follow the exact locomotion phase above. Lock character size, upper body proportions, brushwork, face and viewpoint to those endpoints. Both boots readable, fully grounded walking, no jump.')
print('Prepared exactly 12 SW missing-frame requests')
