async function(direction,frame,target,phase,attempt=1){
const R='D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/characters/02_fire_talisman_boy';
const key=`full-limb-north-20261005-${direction}${String(frame).padStart(2,'0')}-a${String(attempt).padStart(2,'0')}`;
const refs=[target,'D:/work/image/q_daoist_character_pack_4096/02_fire_talisman_boy_transparent_4096.png','D:/work/image/designs/jubaozhai-ui/02-characters.png',R+`/frames/run/W/${String(frame-1).padStart(2,'0')}.png`,R+`/frames/run/W/${String(frame+1).padStart(2,'0')}.png`];
const prompt=`Use case: identity-preserve. Edit ONE transparent full body sprite at native square 1024px or larger. Image1 exact EDIT TARGET: keep its framing, camera, head, body, BOTH LEGS, ankle-shoe axes and ground contact points unchanged. Image2 character identity only. Image3 approved painted style. Image4 previous animation frame and Image5 next frame; these explain hand trajectory only, do not copy their legs or torso. Only edit the anatomical RIGHT arm and its fan. Anatomical LEFT arm holds one bronze bell and must stay unchanged. RIGHT hand holds exactly five red talisman cards as ONE fan. Two arms two legs, no duplicate wrist or extra hand. The right shoulder-elbow-wrist chain must remain anatomically connected. Keep short chibi proportion, expressive painted style, all clothing details and alpha. No shadows/effects/floor. Do not zoom, crop or recenter. Make the right fan wrist pass through an intermediate position close to the SIDE OF THE TORSO instead of jumping directly from fully-forward to fully-back. Some natural occlusion is acceptable; do not extend fan arm to an endpoint just to reveal the fan.\nPOSE EDIT: ${phase}`;
const req={slot:`run/${direction}/${String(frame).padStart(2,'0')}`,candidateKey:key,requestedAt:new Date().toISOString(),configSnapshot:{model:'gpt-image-2.5-sunburst',quality:'max',builtin_product:'ChatGPT Images 2.5',verified_on:'2026-10-01',sources:{release:'https://openai.com/index/introducing-chatgpt-images-2-5/',model:'https://developers.openai.com/api/docs/models/gpt-image-2.5-sunburst'}},tool:'image_gen__imagegen',route:'builtin',submittedParameters:{model:null,quality:null,transparent_background:true,referenced_image_paths:refs},actualModel:null,actualQuality:null,unverifiedReason:'host managed, no model/quality selector or returned confirmation',prompt,references:refs.map((path,i)=>({path,role:['edit target','identity','approved style','previous frame: right wrist trajectory only','next frame: right wrist trajectory only'][i]})),status:'requested'};
for(const ref of req.references){const h=await tools.exec_command({cmd:`(Get-FileHash -LiteralPath '${ref.path}' -Algorithm SHA256).Hash`,max_output_tokens:100});ref.sha256=h.output.trim().toLowerCase();}
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/records/'+key+'.request.json\n+'+JSON.stringify(req,null,2).split('\n').join('\n+')+'\n*** End Patch');
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/prompts/'+key+'.txt\n+'+prompt.split('\n').join('\n+')+'\n*** End Patch');
const result=await tools.image_gen__imagegen({prompt,referenced_image_paths:refs,transparent_background:true});generatedImage(result);
const receipt={receivedAt:new Date().toISOString(),output_hint:result.output_hint,actualModel:null,actualQuality:null};
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/records/'+key+'.receipt.json\n+'+JSON.stringify(receipt,null,2).split('\n').join('\n+')+'\n*** End Patch');
const ex=await tools.exec_command({cmd:`& 'C:/Users/luyua/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe' '${R}/tools/run_north_grounding_candidate_export.py' '${key}'`,max_output_tokens:1000});text(ex);return key;
}
