async function(direction,frame,target,phase,attempt=1){
const R='D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/characters/02_fire_talisman_boy';
const key=`full-limb-north-20261005-${direction}${String(frame).padStart(2,'0')}-a${String(attempt).padStart(2,'0')}`;
const refs=[target,'D:/work/image/q_daoist_character_pack_4096/02_fire_talisman_boy_transparent_4096.png','D:/work/image/designs/jubaozhai-ui/02-characters.png',R+'/frames/run/N/08.png'];
const prompt=`Use case: identity-preserve. Edit ONE transparent full body character sprite, native square 1024px or larger. Image1 exact EDIT TARGET; preserve its camera, head size, canvas registration, direction, face, colors and all upper body identity. Image2 identity only, Image3 approved painted style, Image4 same character's adjacent frame; use its planted shoe's northward toe axis and rear heel view only, do not copy its pose. Anatomical RIGHT hand holds exactly five red cards as one fan, anatomical LEFT one bronze bell and tassel. Same torso, sleeve-wrist chains, short chibi proportions. Two arms two legs. Shoes knees and ankles align with travel axis, never externally rotated. No effects, floor, shadow, labels. Keep alpha. No zoom or recenter. This is a small local ankle/shoe-axis correction ONLY, not a new pose. Preserve original knee location, ankle location, planted heel contact height and the other airborne foot exactly. Do not move or straighten the knees or lower legs. Do not change the existing gait pose. Preserve all outside the planted shoe/ankle.\nPOSE EDIT: ${phase}`;
const req={slot:`run/${direction}/${String(frame).padStart(2,'0')}`,candidateKey:key,requestedAt:new Date().toISOString(),configSnapshot:{model:'gpt-image-2.5-sunburst',quality:'max',builtin_product:'ChatGPT Images 2.5',verified_on:'2026-10-01',sources:{release:'https://openai.com/index/introducing-chatgpt-images-2-5/',model:'https://developers.openai.com/api/docs/models/gpt-image-2.5-sunburst'}},tool:'image_gen__imagegen',route:'builtin',submittedParameters:{model:null,quality:null,transparent_background:true,referenced_image_paths:refs},actualModel:null,actualQuality:null,unverifiedReason:'host managed, no model/quality selector or returned confirmation',prompt,references:refs.map((path,i)=>({path,role:['edit target','identity','approved style','adjacent correct ankle roll reference'][i]})),status:'requested'};
for(const ref of req.references){const h=await tools.exec_command({cmd:`(Get-FileHash -LiteralPath '${ref.path}' -Algorithm SHA256).Hash`,max_output_tokens:100});ref.sha256=h.output.trim().toLowerCase();}
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/records/'+key+'.request.json\n+'+JSON.stringify(req,null,2).split('\n').join('\n+')+'\n*** End Patch');
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/prompts/'+key+'.txt\n+'+prompt.split('\n').join('\n+')+'\n*** End Patch');
const result=await tools.image_gen__imagegen({prompt,referenced_image_paths:refs,transparent_background:true});generatedImage(result);
const receipt={receivedAt:new Date().toISOString(),output_hint:result.output_hint,actualModel:null,actualQuality:null};
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/records/'+key+'.receipt.json\n+'+JSON.stringify(receipt,null,2).split('\n').join('\n+')+'\n*** End Patch');
const ex=await tools.exec_command({cmd:`& 'C:/Users/luyua/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe' '${R}/tools/run_north_grounding_candidate_export.py' '${key}'`,max_output_tokens:1000});text(ex);return key;
}
