async (action,direction,frame,target,phase,attempt=1,replace=false,poseReference=null)=>{
const root="D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/characters/02_fire_talisman_boy";
const refs=[{path:target,role:"EDIT TARGET: fixed framing, camera, rendering, anatomical connections and global scale"},{path:"D:/work/image/q_daoist_character_pack_4096/02_fire_talisman_boy_transparent_4096.png",role:"committed character identity, anatomical right fan and left bell",sha256:"8df2760a5a80eb54ea21558abace8bcbaeca7f7ae6f64de022b6a8b1919c854a"},{path:"D:/work/image/designs/jubaozhai-ui/02-characters.png",role:"approved painted art style",sha256:"7a95140fc3c7a0ae6562ec6dff51d5296edd15116375152a8b22502c7107e879"}];
if(poseReference){const h=await tools.exec_command({cmd:"(Get-FileHash -Algorithm SHA256 -LiteralPath '"+poseReference+"').Hash.ToLowerInvariant()",max_output_tokens:100});refs.push({path:poseReference,role:"Same-direction support-pose reference: mechanics only; not identity, props, scale or anatomical leg selection",sha256:h.output.trim()});}const hashResult=await tools.exec_command({cmd:"(Get-FileHash -Algorithm SHA256 -LiteralPath '"+target.replace(/'/g,"''")+"').Hash.ToLowerInvariant()",max_output_tokens:100});
refs[0].sha256=hashResult.output.trim();
if(!/^[a-f0-9]{64}$/.test(refs[0].sha256))throw new Error("Cannot record edit target SHA before generation");
const prompt="Edit the FIRST attached image to correct this animation asset for Fire Talisman Boy, "+action+"/"+direction+"/"+frame+". Preserve first image camera and framing, head and body pixel size, proportions, virtual floor and root. Identity in image2: chestnut high ponytail, red-gem gold crown, amber eyes, red-gold flame Daoist short robe, ivory cuffs, black trousers, red-black-gold shoes and yin-yang belt. ANATOMICAL RIGHT hand permanently holds exactly FIVE distinct red-gold flame talismans, ANATOMICAL LEFT hand holds one bronze bell with red tassel. Image3 is the approved painted style. Follow connected shoulder-elbow-wrist anatomy, correct near/far occlusion, exactly two arms and two legs. Do not exchange props between arms as the arms swing. "+phase+" Full body square transparent RGBA native at least1024. Preserve the existing full canvas; never zoom or bbox scale. Preserve the FIRST image virtual floor and native head pixel size. The pelvis may lower through newly drawn knee and hip flexion, never by translating or scaling the whole sprite. Fourth image only shows contact mechanics, not the boy body shape or props. Keep existing unclipped prop margins and all original body proportions. Change only the requested parts; preserve all other image details exactly. For a pose request draw articulated joint motion and cloth/hair response. No added particles/trails/skill effects/shadow/text; no mirroring, repeated image, warping or pose interpolation. Project target GPT Image2.5 Sunburst/max, host-managed highest available quality.";
const id=action+"-"+direction+"-"+String(frame).padStart(2,"0")+"-20261004-position-pairs-"+String(attempt).padStart(2,"0");
const record={call_id:id,requested_slot:action+"/"+direction+"/"+String(frame).padStart(2,"0"),submittedAt:new Date().toISOString(),userTimezone:"America/New_York",route:"builtin",tool:"image_gen.imagegen",configSnapshot:{model:"gpt-image-2.5-sunburst",quality:"max",builtin_product:"ChatGPT Images 2.5",verified_on:"2026-10-01",batchContinued:true},submittedParameters:{model:null,quality:null,transparent_background:true,referenced_image_paths:refs.map(x=>x.path)},actualModel:null,actualQuality:null,prompt:"prompts/"+id+".txt",references:refs,status:"submitted",outputFiles:[]};
const initial=JSON.stringify(record);
await tools.apply_patch("*** Begin Patch\n*** Add File: "+root+"/prompts/"+id+".txt\n+"+prompt+"\n*** Add File: "+root+"/records/"+id+".json\n+"+initial+"\n*** End Patch");
let result;
try {result=await tools.image_gen__imagegen({prompt,referenced_image_paths:refs.map(x=>x.path),transparent_background:true});}
catch(e){record.status="failed";record.endedAt=new Date().toISOString();record.rawError=String(e);await tools.apply_patch("*** Begin Patch\n*** Update File: "+root+"/records/"+id+".json\n@@\n-"+initial+"\n+"+JSON.stringify(record)+"\n*** End Patch");text({slot:record.requested_slot,error:String(e)});return{ok:false,slot:record.requested_slot,error:String(e)};}
generatedImage(result);
const path=result.output_hint?.match(/as ([^\r\n]+\.png) by default/)?.[1];
if(!path){text({slot:record.requested_slot,error:"No parseable local output path; actual returned metadata must be inspected"});return{ok:false,slot:record.requested_slot,error:"No parseable local output path"};}
await tools.apply_patch("*** Begin Patch\n*** Add File: "+root+"/records/"+id+".receipt.json\n+"+JSON.stringify({call_id:id,returnedAt:new Date().toISOString(),nativePath:path,output_hint:result.output_hint,actualModel:null,actualQuality:null,toolResultKeys:Object.keys(result)})+"\n*** End Patch");
return{ok:true,slot:record.requested_slot,path,record:"records/"+id+".json",action,direction,frame,replace};
}
