async function(direction,frame,phase,attempt=1){
const R='D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/characters/02_fire_talisman_boy';
const key=`video-axis-${direction}${String(frame).padStart(2,'0')}-a${String(attempt).padStart(2,'0')}`;
const refs=[R+`/frames/run/${direction}/${String(frame).padStart(2,'0')}.png`,'D:/work/image/q_daoist_character_pack_4096/02_fire_talisman_boy_transparent_4096.png','D:/work/image/designs/jubaozhai-ui/02-characters.png','D:/work/image/qdao_original_roster_v14_hd/action-remake-20261001/reference-motion-review-20261004/character-detail.jpg'];
const prompt=`Use case: precise-object-edit. Edit one transparent fullbody square game sprite, native1024 or larger. Image1 exact EDIT TARGET. Image2 identity only, Image3 approved painted finish, Image4 video movement reference only for the straight limb track; do not copy its colors/identity/camera. Preserve the exact fullcanvas framing, head/hair/face, torso, costume, arm poses, anatomical RIGHT hand five red cards, anatomical LEFT hand one bronze bell+tassel. Keep two arms, two legs; retain original support foot and exact running phase, natural knee bend and perspective. User needs feet running in straight parallel anatomical tracks: hip-knee-ankle-heel/second toe stay in the same sagittal plane, no ankle inversion/eversion, no toe pointing sideways. Repaint joints as needed, never flatten/rotate/warp the original image. Do not change canvas registration or add floor/shadow/effects. Transparent alpha. SINGLE TARGETED CHANGE: ${phase}`;
const req={slot:`run/${direction}/${String(frame).padStart(2,'0')}`,candidateKey:key,requestedAt:new Date().toISOString(),configSnapshot:{model:'gpt-image-2.5-sunburst',quality:'max',builtin_product:'ChatGPT Images 2.5',verified_on:'2026-10-01',sources:{release:'https://openai.com/index/introducing-chatgpt-images-2-5/',model:'https://developers.openai.com/api/docs/models/gpt-image-2.5-sunburst'}},tool:'image_gen__imagegen',route:'builtin',submittedParameters:{model:null,quality:null,transparent_background:true,referenced_image_paths:refs},actualModel:null,actualQuality:null,unverifiedReason:'host managed; no model/quality selectors or returned confirmation',prompt,references:refs.map((path,i)=>({path,role:['edit target','identity','approved style','user video limb track only'][i]})),status:'requested'};
for (const ref of req.references){const h=await tools.exec_command({cmd:`(Get-FileHash -LiteralPath '${ref.path}' -Algorithm SHA256).Hash`,max_output_tokens:100});ref.sha256=h.output.trim().toLowerCase();}
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/records/'+key+'.request.json\n+'+JSON.stringify(req,null,2).split('\n').join('\n+')+'\n*** End Patch');
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/prompts/'+key+'.txt\n+'+prompt.split('\n').join('\n+')+'\n*** End Patch');
const result=await tools.image_gen__imagegen({prompt,referenced_image_paths:refs,transparent_background:true});generatedImage(result);
const receipt={receivedAt:new Date().toISOString(),output_hint:result.output_hint,actualModel:null,actualQuality:null};
await tools.apply_patch('*** Begin Patch\n*** Add File: '+R+'/records/'+key+'.receipt.json\n+'+JSON.stringify(receipt,null,2).split('\n').join('\n+')+'\n*** End Patch');
text(await tools.exec_command({cmd:`& 'C:/Users/luyua/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe' -X utf8 '${R}/tools/run_north_grounding_candidate_export.py' '${key}'`,max_output_tokens:300}));return key;
}
