from pathlib import Path
from datetime import datetime,timezone
from collections import defaultdict
import json,hashlib
import numpy as np
from PIL import Image
OUT=Path(__file__).resolve().parent;TILE=OUT.parent
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def main():
 final=OUT/'core4096.png';assert sha(final)=='36fda33daf0f3d2b3c9842b269f0f95a877c2cada23bd4a92ef39f63925bb9c5'
 geom=json.loads((OUT/'processing.json').read_text(encoding='utf-8'));tone=json.loads((OUT/'tone-processing.json').read_text(encoding='utf-8'))
 fp=OUT/'wall-column-flow.npz';old=np.load(fp);fields={k:old[k] for k in old.files};names=['shadow_plane','diagonal_bottom','pillar_outline'];denom=sum(fields[n+'_weight'] for n in names);masks=[]
 for name in names:
  dx=(fields[name+'_dx_uncombined']/np.maximum(1,denom)).astype(np.float32);fields[name+'_dx_applied']=dx;fields[name+'_dy_applied']=np.zeros_like(dx);mask=abs(dx)>1e-7;fields[name+'_actual_support_mask']=mask
  full=np.zeros((4096,4096),np.uint8);x0,y0,x1,y1=fields['support_box'];full[y0:y1,x0:x1]=mask*255;p=OUT/(name+'-support-mask.png');Image.fromarray(full).save(p)
  masks.append({'feature':name,'file':str(p),'sha256':sha(p),'maxAppliedDx':float(abs(dx).max()),'maxAppliedDy':0,'supportPixels':int(mask.sum())})
 np.savez_compressed(fp,**fields)
 geom['geometryStageOutput']=dict(geom.pop('output'));geom['geometryStageOutput']['file']=None;geom['geometryStageOutput']['status']='Transient stage pixels replaced in place by bounded tone stage; retained hash records provenance, not a live image reference'
 geom['finalOutput']=tone['output'];geom['flow']['sha256']=sha(fp);geom['perFeatureActualMasks']=masks
 for m in geom['masks']:m['sha256']=sha(m['file'])
 geom['masks'][-1]['role']='Final combined geometry plus tone changed pixels relative to v3'
 geom['qaBoards']=tone['qaBoards'];geom['qaBoardsStage']='Final v4 geometry plus tone, replacing transient geometry-only boards at same paths'
 geom['visualInspectionPerformed']=True;geom['script']['sha256']=sha(OUT/'finish_wall.py');geom['features'][-1]['additionalAnchors']='Existing normalized half-depth ink boundaries on each side plus dark center; all 3 measured per row; applied dx/dy fields saved separately'
 write(OUT/'processing.json',geom);tone['visualInspectionPerformed']=True;write(OUT/'tone-processing.json',tone)
 review={'reviewedAt':datetime.now(timezone.utc).isoformat(),'source':geom['source'],'output':tone['output'],'formalAccepted':False,'method':'Actual view_image of native integer-crop before/after boards; no resized review, no metrics-only pass','boardsViewed':tone['qaBoards'],'supportGeometry':geom['supportRectangleLTRB'],'supportTone':tone['toneSupportRectangleLTRB'],'maxNewDx':geom['maxDx'],'maxNewDy':0,'maxNewRGB':tone['maxNewAppliedRGB'],'maxCumulativeRGB':tone['maxCumulativeRGB'],'previousDarkGrooveAndOuterBevelPreservedByteExactly':True,'seamY':2048,'completeWallColumnReviewBox':[2400,1920,3328,2176],'segments':[
 {'roi':[2400,1920,2720,2176],'classification':'Normal foliage, bevel highlights and broad low-contrast stone brush variation','observed':'Leaves, ivory rail and soft shading cross the reviewed horizontal range without a newly introduced gap or straight color cut. No operation here.'},
 {'roi':[2720,1970,2880,2130],'classification':'Previously repaired dark groove and wide gray bevel outer contour','observed':'Both contour slopes remain continuous in final full-wall board. Output pixels x<2880 equal v3 input; no previous flow is reapplied.'},
 {'roi':[2904,2016,2942,2080],'classification':'Existing gray shadow-plane contour misregistration; no missing structure','observed':'The original near-8px rectangular jog at y2048 is removed. Shadow boundary is continuous through the seam and fades naturally toward original contour outside support. Some low-contrast broad paint variation remains; no straight horizontal cut remains apparent at native scale. Requested displacements above4 were capped at4; no apparent visible notch remains.'},
 {'roi':[2936,2034,2968,2080],'classification':'Existing diagonal dark bottom-edge misregistration plus slight ink-tone discontinuity','observed':'Diagonal now crosses y2048 continuously with its slope retained. Existing small ink-weight variation remains, without a visible displaced edge or detached line. Local RGB modifies the already-existing stroke only.'},
 {'roi':[2960,2016,2992,2090],'classification':'Existing pillar-outline misregistration and darker lower ink','observed':'Pillar left contour and both ink boundaries now connect. Small natural ink width and opacity variation remain; there is no visible rectangular edge step at y2048. No new geometry or fake line was painted.'},
 {'roi':[2992,1920,3328,2176],'classification':'Existing pillar planes, bright chamfers, and floor transition; unchanged','observed':'No additional horizontal contour discontinuity at y2048 was seen. Vertical gray-face boundary near x3072 remains exactly unchanged; prior vertical QA classifies it as a narrow chamfer. This limited y2048 review does not claim to reclassify that separate vertical feature.'}
 ],'missingStructureDetected':False,'newStraightToneBandDetected':False,'remainingKnownY2048Defect':'No clearly displaced contour or hard horizontal color step remains apparent in the actual native-scale final boards. Natural shading, small ink-weight and brush variations are retained. Final selection and whole-tile validation remain root responsibility.','provenance':{'geometryReport':str(OUT/'processing.json'),'toneReport':str(OUT/'tone-processing.json'),'flow':{'file':str(fp),'sha256':sha(fp)},'tone':tone['toneField']},'onePassResamplingDisclosure':'One NEW cv2.INTER_LINEAR subpixel geometry pass on v3 current RGB, then bounded RGB additions. No image blur, full-cell shift, prior-flow replay, or hallucinated object.'}
 write(OUT/'review.json',review)
 v3=json.loads((TILE/'geometry-v3-local/processing.json').read_text(encoding='utf-8'));v3review={'reviewedAt':review['reviewedAt'],'source':v3['source'],'output':v3['output'],'boardsViewed':v3['qaBoards'],'observed':'Actual native-scale root-focus, full-support and outer-edge detail boards showed the former x2830 outer-bevel triangular notch removed while the darker inner groove remained unchanged. Full wall review then found separate right shadow/pillar issues, now handled in v4.','darkCenterUnchanged':True,'formalAccepted':False,'supersededBy':str(OUT/'review.json')};write(TILE/'geometry-v3-local/review.json',v3review)
 oldqa=TILE/'qa/horizontal-and-guide-review.json';q=json.loads(oldqa.read_text(encoding='utf-8'));q.setdefault('lateDetailedCorrections',[]).append({'reviewedAt':review['reviewedAt'],'seam':'y2048 full wall/column','correction':'Earlier broad-range statements about this entire wall being continuous were too coarse. Subsequent native detail inspection established additional existing contour displacements at x2830, x2920/2928, x2953/2954 and x2971/2973. v3/v4 locally corrected those; no missing structure was detected.','report':str(OUT/'review.json'),'outputSha256':sha(final),'formalAccepted':False});write(oldqa,q)
 inventory=[]
 for folder in sorted(p for p in TILE.iterdir() if p.is_dir()):
  images=[p for p in folder.rglob('*') if p.is_file() and p.suffix.lower() in {'.png','.jpg','.jpeg','.webp'}];records=[p for p in folder.rglob('*') if p.is_file() and p.suffix.lower() in {'.json','.jsonl','.md','.txt','.py','.npz'}]
  inventory.append({'directory':str(folder),'imageFiles':len(images),'imageBytes':sum(p.stat().st_size for p in images),'recordFiles':len(records),'recommendedDisposition':'Keep while selected/final artifact is not confirmed; then root may remove superseded images according to user retention preference, preserving provenance records and required integration files'})
 check={'createdAt':review['reviewedAt'],'mode':'Read-only inventory and handoff; no files deleted','currentBestInternalInput':tone['output'],'rootMustCombineWith':'Current west repair/selection pipeline; v4 already includes internal tone-v2 plus geometry-v3 and new v4 corrections. Do not replay old flow.','keepUntilSelection':['geometry-v4-local/core4096.png','geometry-v4-local/*.json','geometry-v4-local/*.npz','geometry-v4-local/*mask.png','geometry-v4-local/qa/*before-after.png','geometry-v4-local/*.py'],'permanentTextProvenance':'Retain per-image model/quality/source evidence, all prompt and reference hashes, processing/review/selection records. Historical image paths can be marked deliberately removed after final selection; do not falsify their source hashes.','geometryAndToneReproducibility':'Keep saved v2, v3, v4 displacement fields and tone fields if selected processing provenance requires them; these are processing data rather than picture backups.','deletionPreconditions':['Root final selected game PNG exists and dimensions/hash are verified','Current import/export/runtime dependencies point to the selected final artifact','Active root scripts no longer require candidate or intermediate PNG input','Preserve needed design and source record files; no deletion of original assets outside task'], 'selectedPresentAtAudit':(TILE/'selected/core4096.png').exists(),'inventory':inventory,'formalAccepted':False};write(OUT/'cleanup-preflight.json',check)
 print(json.dumps({'core':tone['output'],'reviewSha':sha(OUT/'review.json'),'flowSha':sha(fp),'preflight':str(OUT/'cleanup-preflight.json'),'deletedFiles':0}))
if __name__=='__main__':main()
