from pathlib import Path
import sys,json,numpy as np,datetime,runpy
from PIL import Image
R=Path(__file__).resolve().parent;sys.path.insert(0,str(R/'repairs/internal'));import quilt as q
now=datetime.datetime.now(datetime.timezone.utc).isoformat();Q=R/'qa';Q.mkdir(exist_ok=True)
northpath=R/'repairs/north/handoff-north-v1.json';north=json.loads(northpath.read_text(encoding='utf8'));railpath=R/'qa-independent/rail-finish/merge-manifest-v1.json';rail=json.loads(railpath.read_text(encoding='utf8'));src=Path(north['outputs']['self']['file']);im=Image.open(src).convert('RGB');a=np.asarray(im).copy();x,y=rail['origin'];cp=Path(rail['composite']);mask=Path(rail['mask']);base=Path(rail['base']);assert q.sha(base)==rail['baseSHA256'];assert q.sha(cp)==rail['compositeSHA256'];assert q.sha(mask)==rail['maskSHA256'];patch=np.asarray(Image.open(cp));alpha=np.asarray(Image.open(mask));basecrop=np.asarray(Image.open(base).crop((x,y,x+1254,y+1254)));assert np.array_equal(a[y:y+1254,x:x+1254],basecrop);assert np.array_equal(patch[alpha==0],basecrop[alpha==0]);im.paste(Image.open(cp).convert('RGB'),(x,y));dest=R/'tiles/r11_c15-candidate-final.png';im.save(dest);q.record(dest,[src,cp,mask],{'method':'exact already-composited native1254 patch paste once; outside alpha support identical; no repeated alpha','patchOrigin':[x,y],'globalRectXYWH':[57344,40960,4096,4096],'noResampling':True,'noImageBlur':True,'formalAccepted':False})
final=np.asarray(im);masks={}
for label,bp in [('all',R/'tiles/r11_c15-candidate.png'),('internal-v5',base),('north-candidate',src)]:
 orig=np.asarray(Image.open(bp).convert('RGB'));diff=np.any(final!=orig,axis=2);mp=Q/f'final-vs-{label}-actual-diff-mask.png';mi=Image.fromarray((diff*255).astype('uint8'));mi.save(mp);q.record(mp,[bp,dest],{'method':'exact binary RGB pixel difference','outsideMaskChanges':0});masks[label]={'base':str(bp),'baseSha256':q.sha(bp),'file':str(mp),'sha256':q.sha(mp),'changedPixels':int(diff.sum()),'bboxLTRB':mi.getbbox()}
preview=R/'preview-final.png';im.resize((1254,1254),Image.Resampling.LANCZOS).save(preview);q.record(preview,[dest],{'method':'preview only downscale; final is native4096','neverFinalArt':True})
q.O=Q;q.qa(final,'final',dest)
qadata={'checkedAt':now,'internalLines':['x1024','x2048','x3072','y1024','y2048','y3072'],'internalJunctionCount':9,'internalIndependentReview':'repair_southeast reviewed v5, returned two rail highlight corrections and exact mask; composite replay validated','northIndependentReview':'repair_southeast reviewed seam and both return strips without visible discontinuity or artificial color band','northSharedLine':627,'northReturnLines':[390,940],'northAIOverlapReviewed':[1100,2140,3000],'nativeDetailPatches':16,'nativeDimensions':[1254,1254],'nativeFinal':[4096,4096],'finalResampling':False,'westSharedEdge':'pending neighbor r11_c14 completion and root joint integration','northwestFourCorner':'root integration pending; use final self and north proposal as sources','formalAccepted':False,'wholeCityComplete':False}
(Q/'final-review.json').write_text(json.dumps(qadata,indent=2),encoding='utf8')
manifest={'tile':'r11_c15','globalRectXYWH':[57344,40960,4096,4096],'status':'local_internal_and_north_complete_ready_for_root_integration','candidate':{'file':str(dest),'sha256':q.sha(dest),'dimensions':[4096,4096]},'preview':str(preview),'nativeDirectory':str(R/'native'),'nativePatchCount':16,'coreLTRB':[115,115,1139,1139],'halo':115,'finalUpscaling':False,'north':north,'northManifest':str(northpath),'northManifestSha256':q.sha(northpath),'lastRailRepair':rail,'lastRailRepairManifest':str(railpath),'lastRailRepairManifestSha256':q.sha(railpath),'selfExactDifferenceMasks':masks,'qa':str(Q/'final-review.json'),'generationRecordIndex':str(R/'generation-record-index.json'),'modelEvidence':str(R/'evidence/model-verification.json'),'actualModel':None,'actualQuality':None,'formalAccepted':False,'wholeCityComplete':False,'clientAccepted':False,'pending':['root merge using exact north neighbor mask','west shared edge with r11_c14 when neighbor ready','northwest four-tile corner QA after root integration'],'retention':'Active provenance and intermediate dependencies remain until root has integrated and exported the final game resources; then apply user final-only image cleanup without removing current references.'}
(R/'handoff-final.json').write_text(json.dumps(manifest,indent=2),encoding='utf8')
for name in ['progress.json','current-work.json']:
 p=R/name;d=json.loads(p.read_text(encoding='utf8'));d.update(stage='local_internal_and_north_complete_ready_for_root_integration',updatedAt=now,finalCandidate=str(dest),finalSha256=q.sha(dest),formalAccepted=0,next='root_merge_neighbor_mask_and_future_west_joint',preview=str(preview));p.write_text(json.dumps(d,indent=2),encoding='utf8')
runpy.run_path(str(R/'audit_sources.py'),run_name='__main__');idx=json.loads((R/'generation-record-index.json').read_text(encoding='utf8'));assert not idx['issues'],idx['issues'];manifest['AIImageCountStored']=idx['AIImageCount'];manifest['PNGRecordsAudited']=idx['PNGCount'];manifest['AIImageCountInFinalDependencyChain']=35;(R/'handoff-final.json').write_text(json.dumps(manifest,indent=2),encoding='utf8');print(json.dumps({'final':str(dest),'sha256':q.sha(dest),'northProposal':north['outputs']['north'],'manifest':str(R/'handoff-final.json')},indent=2))
